makerdao-ses/ecosystem-dashboard

- src/stories/components/sidebar/sidebar.tsx
- src/stories/components/svg/logo.tsx
[Trello-19](https://trello.com/c/V3zDi4b4/19-layout-cu-table)
Fixed Topbar Logo position
> [Trello-19] Fix on sidebar logo

- LICENSE
[SES-33](https://trello.com/c/K9sSQBPy/33-replace-license)
Replaced License file for the repo
> [SES-33] Replace License

- src/stories/components/sidebar/sidebar.tsx
This to disable the side bar click navigation
> disable-side-bar-click

- src/stories/components/markdown/markdown.scss
- src/stories/components/markdown/markdown.stories.tsx
- src/stories/components/markdown/md-view-container.tsx
- src/stories/components/markdown/md-view.tsx
- src/stories/components/markdown/renderUtils.ts
- src/stories/containers/header/Header.tsx
- src/stories/pages/page/cu-about/cu-about.tsx
This to fix error in the deploy
> SES-FIX-deploy-fail

- src/stories/components/markdown/markdown.scss
- src/stories/components/markdown/md-view.tsx
- src/stories/components/title-navigation-cu-about/title-navigation-cu-about.tsx
- src/stories/pages/page/cu-about/cu-about.tsx
Correct relate with margin and letter in markdown
> Fix some issues icons

- .github/workflows/validate-pr.yaml
- src/App.tsx
[SES-48](https://trello.com/c/bJlqCN1x/48-configure-eslint)
Create a Github action to check branches before being merged to master. It should check the lint, the tests and the production build of the solution. 
Created a Github action to:
- Check the code using eslint without --fix
- Run tests for the solution
- Build the production deploy to check if everything it's ok
Tested the Github action uploading code with errors.
> [SES-48] Configure eslint

- src/stories/components/relate-mips/relate-mips.stories.tsx
- src/stories/components/relate-mips/relate-mips.tsx
- src/stories/components/title-navigation-cu-about/title-navigation-cu-about.stories.tsx
- src/stories/components/title-navigation-cu-about/title-navigation-cu-about.tsx
- src/stories/containers/cu-about/cu-about-container.tsx
- src/stories/containers/cu-about/cu-about-slice.ts
- src/stories/containers/cu-about/cu-about.api.ts
This is to resolve the problem find in connect API core unit about
https://trello.com/c/HhHmPDJQ/45-connect-cu-about-to-the-api
> Ses-fix-issues-realte-cu-about-api

- src/core/utils/use-outside-click.ts
- src/stories/components/custom-multi-select-2/custom-multi-select-2.scss
- src/stories/components/custom-multi-select-2/custom-multi-select-2.stories.tsx
- src/stories/components/custom-multi-select-2/custom-multi-select-2.tsx
- src/stories/components/custom-multi-select/custom-multi-select.tsx
- src/stories/components/svg/select-chevron-down.tsx
[SES-47](https://trello.com/c/DzZsWfLA/47-refine-the-layout-of-cu-table)
Created new custom select to match new design
> [SES-47] Created new custom select

- src/stories/containers/cu-about/cu-about-container.tsx
This is try to fix bugs in production, correct the name to Uppercase.
> correct-name-sub-header-image

- src/stories/containers/cu-about/cu-about-container.tsx
- src/stories/containers/cu-about/cu-about-slice.ts
Fix the problem with the routes with migrate to nextjs
> Fix problem core unit about production

- .storybook/main.js
- .storybook/preview.js
- package.json
- src/stories/components/cu-table-column-links/cu-table-column-links.tsx
- src/stories/containers/cu-about/cu-about.stories.tsx
- src/stories/containers/cu-table/cu-table.stories.tsx
- src/stories/containers/cu-table/cu-table.tsx
- yarn.lock
[SES-47](https://trello.com/c/DzZsWfLA/47-refine-the-layout-of-cu-table)
Fixed issues remarked by the tester
> [SES-47] issues fix

- src/stories/components/card-info-member/card-info-member.tsx
- src/stories/components/card-navegation/card-navigation.tsx
- src/stories/components/markdown/md-view.tsx
- src/stories/components/markdown/renderUtils.tsx
- src/stories/components/title-navigation-cu-about/title-navigation-cu-about.tsx
- src/stories/containers/cu-about/cu-about-container.tsx
SES-fix-issues-find-by-tester
fix-issues-relate-header-card-navigation
Merge master
> Ses fix issues find by tester

- src/stories/components/card-info-member/card-info-member.tsx
This is small change card, when the image came from APi
> small-change-relate-space

- src/stories/components/footer/description-footer.tsx
- src/stories/components/footer/footer-contact.tsx
- src/stories/components/footer/footer-link.tsx
- src/stories/components/footer/footer.tsx
- src/stories/components/footer/iconsData.tsx
https://trello.com/c/U1flxIpy/61-layout-footer
Add correct size column
Add icon size
> Ses refine footer space

- src/core/business-logic/__tests__/core-units.tests.ts
- src/core/business-logic/builders/mip-41.builder.ts
- src/core/business-logic/core-units.ts
- src/core/models/dto/core-unit.dto.ts
- src/core/models/facilitator.model.ts
- src/stories/components/cu-table-column-team-member/cu-table-column-team-member.stories.tsx
- src/stories/components/cu-table-column-team-member/cu-table-column-team-member.tsx
- src/stories/components/custom-button/custom-button.tsx
- src/stories/components/custom-multi-select/custom-multi-select.tsx
- src/stories/components/svg/telegram.tsx
- src/stories/containers/cu-table/cu-table.api.ts
- src/stories/containers/cu-table/cu-table.slice.ts
- src/stories/containers/cu-table/cu-table.stories.states.ts
- src/stories/containers/cu-table/cu-table.stories.tsx
- src/stories/containers/cu-table/cu-table.tsx
Changing api fetch operation due to change on db
> [SES-47] Fix due to db changes

- src/stories/components/footer/footer.tsx
To fix space in 1920 don't look good
> fix-space-1920-don't-look-good

- src/stories/components/footer/description-footer.tsx
- src/stories/components/footer/footer.tsx
> Change space between columns

- src/stories/components/footer/description-footer.tsx
- src/stories/components/footer/footer-contact.tsx
- src/stories/components/footer/footer.tsx
This fix color title in footer
> change-color-footer

- src/stories/components/card-navegation/card-navigation.tsx
- src/stories/components/cu-table-column-links/cu-table-column-links.tsx
- src/stories/components/markdown/md-view.tsx
- src/stories/components/relate-mips/relate-mips.tsx
- src/stories/components/team-members/team-member.tsx
- src/stories/components/title-navigation-cu-about/title-navigation-cu-about.tsx
- src/stories/containers/cu-about/cu-about-container.tsx
fix-issues-relate-landing-page
> fix-issues-relate-landing-page

- src/stories/components/inner-table/inner-table.tsx
- src/stories/containers/transparency-report/transparency-actuals/transparency-actuals.tsx
- src/stories/containers/transparency-report/transparency-mkr-vesting/transparency-mkr-vesting.tsx
[SES-51](https://trello.com/c/szlXePBd/51-layout-cu-finance-transparency-reporting-view)
Fixes related to margin on inner table component
> [SES-51] transparency reporting fixes

- src/stories/components/card-navegation/card-navigation.tsx
- src/stories/components/cu-table-column-links/cu-table-column-links.tsx
- src/stories/containers/cu-about/cu-about-container.tsx
> fix-issues-relate-space-card-scrolling

- src/core/utils/date.utils.ts
- src/core/utils/string.utils.ts
- src/stories/components/custom-link/custom-link.tsx
- src/stories/components/wallet-table-cell/wallet-table-cell.tsx
- src/stories/containers/transparency-report/transparency-actuals/transparency-actuals.mvvm.ts
- src/stories/containers/transparency-report/transparency-actuals/transparency-actuals.tsx
- src/stories/containers/transparency-report/transparency-forecast/transparency-forecast.mvvm.ts
- src/stories/containers/transparency-report/transparency-forecast/transparency-forecast.tsx
- src/stories/containers/transparency-report/transparency-report.mvvm.ts
[SES-52](https://trello.com/c/5Ii1ofJc/52-connect-cu-finance-transparency-reporting-to-the-api)
Fixed issues with values on forecast table
> SES 52 connect transparency report

- src/stories/containers/transparency-report/transparency-actuals/transparency-actuals.tsx
- src/stories/containers/transparency-report/transparency-forecast/transparency-forecast.mvvm.ts
- src/stories/containers/transparency-report/transparency-forecast/transparency-forecast.tsx
[SES-52](https://trello.com/c/5Ii1ofJc/52-connect-cu-finance-transparency-reporting-to-the-api)
Removing empty line items and other minor fixes
> [SES-52] Removing empty lines

- src/stories/components/footer/description-footer.tsx
- src/stories/components/footer/footer-contact.tsx
- src/stories/components/footer/footer-link.tsx
- src/stories/components/footer/footer.tsx
- src/stories/components/footer/iconsData.tsx
https://trello.com/c/U1flxIpy/61-layout-footer
Add correct padding and width of each column
> Add correct padding and width of each column

- src/stories/components/button/big-button/big-button.tsx
- src/stories/components/card-navegation/card-navigation.tsx
- src/stories/components/pagination/bread-crumb.tsx
- src/stories/components/relate-mips/relate-mips.tsx
- src/stories/components/status-chip/status-chip.tsx
- src/stories/components/team-members/team-member.tsx
- src/stories/components/title-navigation-cu-about/title-navigation-cu-about.tsx
- src/stories/containers/cu-about/cu-about-container.tsx
This is to add fonts to Cu-landing page.
Add fonts page
> add-fonts-page

- src/stories/components/footer/footer.tsx
Fix issues in padding in the view
> fix-padding-view

- styles/globals.scss
> add-fonts-footer

- src/stories/containers/cu-about/cu-about-container.tsx
This pr is for resolve issues  relate with header
Quick fix to problem find in the meeting with the client
> add-wrapper-also-border-correct-div

- src/stories/components/core-unit-summary/core-unit-summary.tsx
- src/stories/components/markdown/md-view.tsx
- src/stories/containers/cu-about/cu-about-container.tsx
This add correct padding when the description have two lines
> Ses fix cu landing page final iteration

- src/stories/containers/transparency-report/transparency-report.tsx
https://trello.com/c/szlXePBd/51-layout-cu-finance-transparency-reporting-view
> Ses 51 Latest fixes

- src/stories/components/card-navegation/card-navigation.tsx
- src/stories/components/markdown/renderUtils.tsx
- src/stories/components/pagination/bread-crumb.tsx
- src/stories/components/title-navigation-cu-about/title-navigation-cu-about.tsx
No ticket
Fix problems bread-crumb for new header component
> fix-issues-header-and-breadCrumb

- src/core/models/dto/core-unit.dto.ts
- src/stories/containers/transparency-report/transparency-audit/transparency-audit.mvvm.ts
- src/stories/containers/transparency-report/transparency-audit/transparency-audit.tsx
- src/stories/containers/transparency-report/transparency-report.api.ts
- src/stories/containers/transparency-report/transparency-report.tsx
https://trello.com/c/5Ii1ofJc/52-connect-cu-finance-transparency-reporting-to-the-api
Added integration to audit reports tab
> [SES-52] Connected audit reports to API

- .env
- .github/workflows/dev-deploy.yaml
- .github/workflows/staging-deploy.yaml
- README.md
- package.json
- src/config/endpoints.ts
https://trello.com/c/AR8SRsLG/73-create-the-environments-dev-staging-and-prod
Added the configuration for the staging environment
> [SES-73] create the environments

- src/stories/components/custom-link/custom-link.tsx
- src/stories/components/footer/footer-contact.tsx
- src/stories/components/header/select-link-website/select-link.tsx
- src/stories/components/markdown/renderUtils.tsx
- src/stories/components/relate-mips/relate-mips.tsx
- src/stories/components/svg/link-icon.tsx
- src/stories/components/title-navigation-cu-about/title-navigation-cu-about.tsx
No ticket
Add some tag in md-viewer
> fix-tag-md-view-icon-space

- src/core/utils/string.utils.ts
Fix on formatted wallet address
> [NO-TICKET] Fix on formatted wallet address missing last character

- src/stories/components/header/select-link-website/item-select/item-website.tsx
- src/stories/components/header/select-link-website/select-link.tsx
> fix-colors

- .github/workflows/production-deploy.yaml
- .github/workflows/staging-deploy.yaml
https://trello.com/c/AR8SRsLG/73-create-the-environments-dev-staging-and-prod
Created the production environment and deployment
> [SES-73] Create the frontend environments

- src/stories/containers/transparency-report/transparency-report.api.ts
Removed unneeded fields from GRAPHQL API call
> [SES-52] Removed unneeded API call

- src/stories/components/card-navegation/card-expenses.tsx
- src/stories/containers/cu-about/cu-about-container.tsx
#No-Ticket
This is to card take text dinamically
> fix-card-take-text-dynamically

- src/core/context/ThemeContext.tsx
- src/core/utils/filters.ts
- src/stories/components/button/switch-button/switch-buttom.tsx
- src/stories/components/custom-button/custom-button.tsx
- src/stories/components/custom-link/custom-link.tsx
- src/stories/components/footer/footer.tsx
- src/stories/components/header/header.stories.tsx
- src/stories/components/header/header.tsx
- src/stories/components/header/select-link-website/item-select/item-website.tsx
- src/stories/components/header/select-link-website/select-link.tsx
- src/stories/components/search-input/search-input.tsx
- src/stories/components/svg/close.tsx
- src/stories/components/svg/select-chevron-down.tsx
- src/stories/components/svg/three-dots.tsx
- src/stories/components/top-bar-select/top-bar-select.tsx
- src/stories/containers/cu-table/cu-table-filters.tsx
- src/stories/containers/cu-table/cu-table.tsx
- src/stories/containers/dashboard-wrapper/header-wrapper.tsx
- src/stories/containers/transparency-report/transparency-report.tsx
https://trello.com/c/GOwDLF4X/89-implement-responsive-solution-for-cu-index-table
Added fixes to footer responsiveness
Added header responsiveness
> [SES-89] implement responsive solution for cu index table

- feature-flags/feature-flags.staging.ts
- src/stories/containers/cu-about/cu-about-container.tsx
#Not Ticket 
Fix the first three elements of the
85-general-qc-round-v-10-r
> fix-three-first-items-space

- src/core/business-logic/__tests__/core-units.tests.ts
- src/core/business-logic/builders/core-units.builder.ts
- src/core/business-logic/core-unit-about.ts
- src/core/business-logic/core-units.ts
- src/core/models/dto/core-unit.dto.ts
- src/stories/components/card-info-member/card-info-member.tsx
- src/stories/components/circle-avatar/circle-avatar.tsx
- src/stories/components/cu-table-column-expenditures/cu-table-column-expenditures.tsx
- src/stories/components/cu-table-column-links/cu-table-column-links.tsx
- src/stories/components/cu-table-column-summary/cu-table-column-summary.tsx
- src/stories/components/cu-table-column-team-member/cu-table-column-team-member.stories.tsx
- src/stories/components/cu-table-column-team-member/cu-table-column-team-member.tsx
- src/stories/components/custom-multi-select/custom-multi-select.tsx
- src/stories/components/custom-popover/custom-popover.module.scss
- src/stories/components/custom-popover/custom-popover.tsx
- src/stories/components/footer/description-footer.tsx
- src/stories/components/select-item/select-item.tsx
- src/stories/containers/cu-table/cu-table-filters.tsx
- src/stories/containers/cu-table/cu-table.api.ts
- src/stories/containers/cu-table/cu-table.tsx
- src/stories/containers/transparency-report/transparency-report.tsx
- styles/globals.scss
https://trello.com/c/JjqOb7qz/81-review-state-of-components-as-per-the-final-design-v-10
Updated the components used on core units table
Now uses contributor commitment to get the facilitator
Updated tests
> [SES-81] Review state of components as per the final design v 10

- src/core/business-logic/__tests__/core-units.tests.ts
- src/stories/components/category-chip/category-chip.tsx
- src/stories/components/custom-button/custom-button.tsx
- src/stories/components/custom-multi-select/custom-multi-select.tsx
- src/stories/components/header/header.tsx
- src/stories/components/header/select-link-website/select-link.tsx
- src/stories/components/select-item/select-item.tsx
- src/stories/containers/cu-table/cu-table-filters.tsx
https://trello.com/c/TVtQIcGF/86-implement-dark-mode-for-coreunitoverviewtable-v-10
Fix issues detected in the table in dark mode
fix-some-style-multiselect-color-logo
Add highLigth select fix colors problem
fix-lint-warning
> Fix issues 86 implement dark mode for Core Unit Overview Table v 10

- src/stories/components/custom-popover/custom-popover.tsx
#No ticket
Fix error pop-over in dark mode
> Fix-border-add-pop-over-dark-light

- src/stories/components/audit-status-chip/audit-status-chip.tsx
- src/stories/components/core-unit-summary/core-unit-summary.tsx
- src/stories/components/custom-link/custom-link.tsx
- src/stories/components/custom-pager/custom-pager.tsx
- src/stories/components/inner-table/inner-table.tsx
- src/stories/components/number-cell/number-cell.tsx
- src/stories/components/table-cell/table-cell.tsx
- src/stories/components/tabs/tabs.tsx
- src/stories/components/transparency-card/transparency-card.tsx
- src/stories/components/wallet-table-cell/wallet-table-cell.tsx
- src/stories/containers/transparency-report/transparency-actuals/transparency-actuals.tsx
- src/stories/containers/transparency-report/transparency-audit/transparency-audit.tsx
- src/stories/containers/transparency-report/transparency-forecast/transparency-forecast.tsx
- src/stories/containers/transparency-report/transparency-mkr-vesting/transparency-mkr-vesting.tsx
- src/stories/containers/transparency-report/transparency-report.tsx
- src/stories/containers/transparency-report/transparency-transfer-request/transparency-transfer-request.tsx
https://trello.com/c/RdukhnO0/88-implement-dark-mode-for-coreunitfinancestransparencyreporting-v-10
Dark mode for finances
Add dark mode in inner table
Add dark mode in table_Cell and NumberCell component
Add dark mode for the transparency actual tab
Add dark mode audi report correct colors and border audi reports
Add dark mode forescat and actuals add lineHeith to CustomLink
Add dark transparency mk vesting
Add dark to the transfarence request tab
Add some lineHeight that are missing in dark mode
Add dark mode transparency card for mobile
Correct lineHeight in the links footer for the card mobile of the view
Fix some lineHeight and correct colors
> Ses 88 implement dark mode for coreunitfinancestransparencyreporting v 10

- src/core/business-logic/core-units.ts
> [NO-TICKET] Fix on FTEs calculation

- src/stories/components/markdown/md-view-container.tsx
- src/stories/components/markdown/md-view.tsx
#No Ticket
No show img when the null values in the bd
> no show nothhing when img is null

- src/stories/components/core-unit-card/categories-skeleton.tsx
- src/stories/components/cu-table-column-expenditures/cu-table-column-expenditures-skeleton.tsx
- src/stories/components/cu-table-column-links/cu-table-column-links-skeleton.tsx
- src/stories/components/cu-table-column-summary/cu-table-column-summary-skeleton.tsx
- src/stories/components/cu-table-column-team-member/cu-table-column-team-member-skeleton.tsx
- src/stories/components/custom-table/placeholder.tsx
- src/stories/containers/cu-table/cu-table.tsx
https://trello.com/c/BbCfGieE/101-implement-empty-state-for-coreunitoverviewtable-v-10
Fixes on empty state
> [SES-101] Fixes on empty state

- src/stories/components/inner-table/inner-table.tsx
- src/stories/containers/transparency-report/placeholders/transparenct-empty-audit.tsx
- src/stories/containers/transparency-report/placeholders/transparency-empty-table.tsx
- src/stories/containers/transparency-report/transparency-actuals/transparency-actuals.tsx
- src/stories/containers/transparency-report/transparency-audit/transparency-audit.tsx
- src/stories/containers/transparency-report/transparency-forecast/transparency-forecast.tsx
- src/stories/containers/transparency-report/transparency-mkr-vesting/transparency-mkr-vesting.tsx
- src/stories/containers/transparency-report/transparency-transfer-request/transparency-transfer-request.tsx
https://trello.com/c/zYJLO8mN/103-implement-empty-state-for-coreunitfinancestransparencyreporting-v-10
Added empty states for tables and audit reports on transparency report
> [SES-103] implement empty state for transparency reporting

- pages/_app.tsx
- src/stories/containers/cu-table/cu-table.tsx
- src/stories/containers/transparency-report/transparency-report.tsx
Fixes on descriptions and adding image link and title
> [SES-95] [SES-97]

- src/stories/containers/cu-about/cu-about-container.tsx
Added metadata for core unit about
> [SES-96] Added metadata for core unit about

- src/stories/components/inner-table/inner-table.tsx
- src/stories/containers/transparency-report/placeholders/transparency-empty-table.tsx
- src/stories/containers/transparency-report/transparency-actuals/transparency-actuals.tsx
- src/stories/containers/transparency-report/transparency-forecast/transparency-forecast.tsx
- src/stories/containers/transparency-report/transparency-mkr-vesting/transparency-mkr-vesting.tsx
- src/stories/containers/transparency-report/transparency-transfer-request/transparency-transfer-request.tsx
https://trello.com/c/zYJLO8mN/103-implement-empty-state-for-coreunitfinancestransparencyreporting-v-10
Fixes according to designer observation
> [SES-103] Implement empty state for transparency

- src/stories/containers/transparency-report/placeholders/transparency-empty-table.tsx
https://trello.com/c/zYJLO8mN/103-implement-empty-state-for-coreunitfinancestransparencyreporting-v-10
Fixes for moblie view
> [SES-103] Fixes on transparency empty state

- next.config.js
- pages/_app.tsx
- src/stories/components/cu-table-header-skeleton/header-skeleton.tsx
- src/stories/components/custom-table/custom-table-header.skeleton.tsx
- src/stories/components/custom-table/custom-table.tsx
- src/stories/containers/cu-table/cu-table.tsx
Affected card: https://trello.com/c/v0E3jURU/85-general-qc-round-v-10-r
- Fixed CoreUnitOverviewTable: Loading Page
- Fixed styles flicker on load when a page is loaded or refreshed
> Fix issues general qc round

- src/stories/components/header/header.tsx
- src/stories/components/inner-table/inner-table.tsx
- src/stories/components/tabs/tabs.tsx
- src/stories/components/title-navigation-cu-about/title-navigation-cu-about.tsx
- src/stories/containers/cu-table/cu-table.tsx
https://trello.com/c/RdukhnO0/88-implement-dark-mode-for-coreunitfinancestransparencyreporting-v-10
Fix issues in dark mode transparency reports
fix-issues-find-tester
> Fix ses 88 implement dark mode for coreunitfinancestransparencyreporting v 10

- src/stories/pages/page/cu-about/cu-about.stories.tsx
- src/stories/pages/page/cu-about/cu-about.tsx
#Ticket
Fix problem when make deploy, for conflict in the name
> fix-problem-name-story-book

- pages/_app.tsx
- src/stories/components/markdown/renderUtils.tsx
- src/stories/containers/cu-about/cu-about-container.tsx
- src/stories/containers/cu-table/cu-table.tsx
https://trello.com/c/7rHczu6t/96-create-metadata-for-links-for-coreunitaboutpage-v-10
Add metadata for landing page
Delete tag image from the _app to can show different tag for other page
Add metadata for Cu-Landing-Page
> Ses 96 create metadata for links for coreunitaboutpage v 10

- src/core/business-logic/__tests__/core-units.tests.ts
- src/core/business-logic/core-units.ts
The clients requested to show the 3 last months "with data", not based on the current date but on the last data input it was made. 
Made a function to look for a month with data, and from that one go backwards another 2 months.
> [NO-TICKET] Fix on logic to calculate the chart values

- src/stories/components/core-unit-card/categories-skeleton.tsx
- src/stories/components/cu-table-column-expenditures/cu-table-column-expenditures-skeleton.tsx
- src/stories/components/cu-table-column-links/cu-table-column-links-skeleton.tsx
- src/stories/components/cu-table-column-summary/cu-table-column-summary-skeleton.tsx
- src/stories/components/cu-table-column-team-member/cu-table-column-team-member-skeleton.tsx
- src/stories/components/cu-table-header-skeleton/header-skeleton.tsx
- src/stories/components/custom-table/custom-table-header.skeleton.tsx
- src/stories/containers/cu-table/cu-table.tsx
#No Ticket
Add loading dark mode state
add categories dark
add-dark-mode-skeleton-component
> Ses loading state dark mode cu over view table

- src/stories/containers/transparency-report/placeholders/transparency-empty-table.tsx
#No ticket
Add correct color of the line
> correct-color-line

- src/stories/components/custom-bar-chart/custom-bar-chart.tsx
- src/stories/containers/cu-about/cu-about-container.tsx
Fixed the last bar of the component looks slimmer that the others
> [FIX-85] Fix UI issue in the expenditure graph

- README.md
- feature-flags/feature-flags.development.ts
- feature-flags/feature-flags.interface.ts
- feature-flags/feature-flags.production.ts
- feature-flags/feature-flags.staging.ts
- pages/sitemap.xml.tsx
- public/robots.txt
- src/config/routes.ts
- src/core/utils/sitemap.ts
https://trello.com/c/trpIoYYf/108-implement-seo-elements-v-10
A sitemap of all the existing urls was implemented. The sitemap can be disabled using feature flags according to the environment
- created a sitemap builder to generate the sitemap content
- added two new environment variables
- cached sitemap content on the client side (1h)
- updated readme.md
> [SES-108] add sitemap

- .github/workflows/dev-deploy.yaml
- .github/workflows/production-deploy.yaml
- .github/workflows/staging-deploy.yaml
Added the following variables to the GitHub workflow files:
- NEXT_PUBLIC_BASE_URL
- ENABLE_SITEMAP
> add missing env vars in github workflows

- src/core/hooks/useUrlAnchor.ts
- src/core/utils/query-string.utils.ts
- src/core/utils/sitemap.ts
- src/stories/components/core-unit-summary/core-unit-summary.tsx
- src/stories/components/tabs/tabs.tsx
- src/stories/containers/cu-about/cu-about-container.tsx
- src/stories/containers/cu-table/cu-table.tsx
- src/stories/containers/transparency-report/transparency-actuals/transparency-actuals.tsx
- src/stories/containers/transparency-report/transparency-forecast/transparency-forecast.tsx
- src/stories/containers/transparency-report/transparency-report.tsx
- src/stories/containers/transparency-report/transparency-transfer-request/transparency-transfer-request.tsx
https://trello.com/c/trpIoYYf/108-implement-seo-elements-v-10
The deep links using anchor in the URL (#id) are changed when the user clicks on the target element but the rest of the work is done using TS to prevent default behavior and  wrong placement of the scroll
- removed unused URL params
- implement deep links for the transparency tab
- implement deep links for transparency actuals and transparency forecast tabs
> [SES-108] Deep links

- .github/workflows/production-deploy.yaml
- .gitignore
- .vscode/settings.json
- README.md
- package.json
- pages/_app.tsx
- pages/_document.tsx
- src/core/utils/gtag.ts
- yarn.lock
https://trello.com/c/trpIoYYf/108-implement-seo-elements-v-10
Add support for Google Analytics
- Add google analytics support
- Add env variable to the production environment to support Google Analytics
> [SES-108] Google Analytics

- src/core/business-logic/core-unit-about.ts
- src/stories/components/tabs/tabs.tsx
- src/stories/containers/transparency-report/transparency-forecast/transparency-forecast.tsx
https://trello.com/c/QJFWbzL0/110-general-issues-detected-in-the-uat-coreunitaboutpage-r
- Fix jumps between tabs
- Fix social links in card info members
> [SES-110] FIX uat issues cu about page

- src/stories/components/404/not-found-component-404.tsx
#Not ticket
#Description
Fix error after deploy to make in the wrong branch
> fix-error-after-deploy

- pages/core-unit/[code]/index.tsx
- src/core/hooks/useUrlAnchor.ts
- src/stories/components/card-info-member/card-info-member.tsx
- src/stories/components/markdown/md-view.tsx
- src/stories/components/markdown/renderUtils.tsx
- src/stories/containers/cu-about/cu-about-container.tsx
- src/stories/containers/transparency-report/transparency-report.tsx
https://trello.com/c/QJFWbzL0/110-general-issues-detected-in-the-uat-coreunitaboutpage-r
Fixed several issues
> [FIX-110] uat issues cu about page

- src/stories/components/core-unit-card/core-unit-card.tsx
- src/stories/components/cu-table-column-expenditures/cu-table-column-expenditures.tsx
- src/stories/components/cu-table-column-summary/cu-table-column-summary.tsx
- src/stories/components/cu-table-column-team-member/cu-table-column-team-member.tsx
- src/stories/components/cu-table-header-skeleton/header-skeleton.tsx
- src/stories/components/markdown/md-view.tsx
- src/stories/components/relate-mips/relate-mips.tsx
- src/stories/containers/cu-about/cu-about-container.tsx
- src/stories/containers/cu-table/cu-table.tsx
Fixed several issues found in general round QC
> [FIX-85] Fix issues general qc round

- src/core/business-logic/core-units.ts
- src/stories/components/circle-avatar/circle-avatar.tsx
- src/stories/components/core-unit-card/core-unit-card.tsx
- src/stories/components/cu-table-column-summary/cu-table-column-summary.tsx
- src/stories/components/custom-link/custom-link.tsx
- src/stories/components/tabs/tabs.tsx
- src/stories/containers/transparency-report/transparency-actuals/transparency-actuals.mvvm.ts
- src/stories/containers/transparency-report/transparency-forecast/transparency-forecast.mvvm.ts
- src/stories/containers/transparency-report/transparency-report.tsx
https://trello.com/c/nn8ks7J1/111-general-issues-detected-in-the-uat-coreunitfinancestransparency-r
Fixes to issues detected during UAT
> [SES-111] General issues detected in the uat coreunitfinancestransparency r

- src/core/business-logic/core-unit-about.ts
- src/core/enums/expenditure-level.enum.ts
- src/stories/components/cu-table-column-summary/cu-table-column-summary.tsx
- src/stories/components/cu-table-column-team-member/cu-table-column-team-member.tsx
- src/stories/components/custom-bar-chart/custom-bar-chart.tsx
- src/stories/components/header/header.tsx
- src/stories/components/search-input/search-input.tsx
- src/stories/components/svg/close.tsx
- src/stories/containers/cu-table/cu-table-filters.tsx
https://trello.com/c/KfjSlKiE/107-general-issues-detected-in-the-uat-coreunitoverviewtable-r
correct-name
correct-align-arrow
popover for the bar char items with new design
Add x close svg for the search bar
correct-input-error-if-no-exist
correct-indentation-problem
add-design-there-is-no-data-dark-mode
> Fix 107 general issues detected in the  core-unit-over-view-table round two

- src/stories/components/card-info-member/card-info-member.tsx
- src/stories/components/core-unit-summary/core-unit-summary.tsx
- src/stories/components/team-members/team-member.tsx
- src/stories/containers/cu-about/cu-about-container.tsx
- src/stories/containers/transparency-report/transparency-report.tsx
Fixed several issues
- change the font size for the team size header
- reduce font size for contact information title
- change the font family for the contributor name
- increase the size of the members img in the info card
- fix breadcrumb in mobile devices
> [SES-85] Fix issues general qc round

- src/stories/components/search-input/search-input.tsx
#No ticket
Change size icon mobile
> fix-size-icon

- src/stories/components/seo-head/seo-head.tsx
- src/stories/containers/cu-about/cu-about-container.tsx
- src/stories/containers/transparency-report/transparency-report.tsx
https://trello.com/c/ATfg3vql/115-general-issues-detected-in-the-uat-seo-r
Use the right image and preview format in CU about
> [SES-115] Improve share links previews for cu about page

- src/stories/components/custom-bar-chart/custom-bar-chart.tsx
- src/stories/components/custom-popover/custom-popover.tsx
- src/stories/components/footer/footer.tsx
https://trello.com/c/KfjSlKiE/107-general-issues-detected-in-the-uat-coreunitoverviewtable-r
Resolving issues
avoid-hover-on-touch-device
fix-small-margin-detail
> Fix 107 general issues detected in the uat coreunitoverviewtable round four

- src/stories/components/seo-head/seo-head.tsx
> removed canocical url from og metas

- src/stories/components/404/not-found-component-404.tsx
- src/stories/components/team-members/team-member.tsx
- src/stories/components/title-navigation-cu-about/title-navigation-cu-about.tsx
- src/stories/containers/cu-about/cu-about-container.tsx
correct-font-family
change-font-family
> Fix 85 general qc round v 10 r one

- src/stories/components/core-unit-card/core-unit-card.tsx
- src/stories/components/relate-mips/relate-mips.tsx
- src/stories/components/search-input/search-input.tsx
- src/stories/components/team-members/team-member.tsx
- src/stories/components/transparency-card/transparency-card.tsx
- src/stories/containers/cu-about/cu-about-container.tsx
- src/stories/containers/transparency-report/transparency-mkr-vesting/transparency-mkr-vesting.tsx
- src/stories/containers/transparency-report/transparency-report.tsx
fix-align-mobile
fix-text-decoration-FTEs
> Fix 85 general qc round v 10 r two

- src/stories/components/card-info-member/card-info-member.tsx
- src/stories/components/card-navegation/card-expenses.tsx
- src/stories/components/card-navegation/card-somethig-wrong.tsx
- src/stories/components/core-unit-summary/core-unit-summary.tsx
- src/stories/components/markdown/renderUtils.tsx
- src/stories/components/seo-head/seo-head.tsx
- src/stories/components/svg/discord.tsx
- src/stories/components/svg/forum.tsx
- src/stories/components/svg/linkedin.tsx
- src/stories/components/svg/twitter.tsx
- src/stories/components/svg/www.tsx
- src/stories/components/svg/youtube.tsx
- src/stories/components/title-navigation-cu-about/title-navigation-cu-about.tsx
- src/stories/containers/cu-about/cu-about-container.tsx
https://trello.com/c/QJFWbzL0/110-general-issues-detected-in-the-uat-coreunitaboutpage-r
fix issues found on UAT
> [SES-110] Uat issues cu about page

- src/stories/containers/transparency-report/transparency-report.tsx
No ticket
fix-space-data-from-api
> fix-space-data-from-API

- src/stories/components/cu-table-column-links/cu-table-column-links.tsx
> fix column icons

- src/stories/components/core-unit-card/core-unit-card.tsx
- src/stories/components/cu-table-column-summary/cu-table-column-summary.tsx
- src/stories/components/cu-table-column-team-member/cu-table-column-team-member.tsx
https://trello.com/c/5eYTX48I/116-issues-pending-of-r1-v-20
Fix UI issues in Core Unit Card
> [SES-116] Fix UI CU card

- src/stories/components/markdown/md-view.tsx
- src/stories/components/relate-mips/relate-mips.tsx
- styles/globals.scss
116-issues-pending-of-r1-v-20
add fonts Inter for FTEs
> FIX-116-issues-pending-of-r1-v-20

- src/stories/components/circle-avatar/circle-avatar.tsx
- src/stories/components/core-unit-card/core-unit-card.tsx
- src/stories/components/core-unit-summary/core-unit-summary.tsx
- src/stories/components/custom-button/custom-button.tsx
- src/stories/components/relate-mips/relate-mips.tsx
- src/stories/containers/cu-table/cu-table-filters.tsx
- styles/globals.scss
https://trello.com/c/5eYTX48I/116-issues-pending-of-r1-v-20
fix-view-iphone-12-mini
Add correct color card and fix lint error in code
more-consistency-way-fix-gap-problem-safary
fix-Inter-import-in-sass-file
fix-lineHeight
fix-iphone-mini-filter-buttom-aling
delete-gap-add-lobotomizada
> Fix 116 issues pending of r1 v 20

- src/stories/components/seo-head/seo-head.tsx
> color-dark-mode

- src/stories/components/cu-table-column-last-modified/cu-table-column-last-modified.tsx
- src/stories/containers/transparency-report/transparency-report.mvvm.ts
- src/stories/containers/transparency-report/transparency-report.tsx
https://trello.com/c/Uopvky02/153-changetracking-v1-budgetstatementlastupdate-element
Added last update date to transparency report
> [SES-153] Changetracking v1 budgetstatementlastupdate element

- src/stories/components/card-navegation/card-expenses.tsx
- src/stories/components/cu-table-column-summary/cu-table-column-summary.tsx
- src/stories/containers/cu-about-2/cu-about-container-2.tsx
- src/stories/containers/transparency-report/transparency-report.tsx
SES-146-change-font-of-the-app-inter-v-20
Fix fonts different view
> Fix fonts differents view

- src/stories/components/cu-activity-table/cu-activity-item.tsx
- src/stories/components/cu-activity-table/cu-activity-table.tsx
- src/stories/components/custom-button/custom-button.tsx
- src/stories/containers/cu-activity/cu-activity.mvvm.ts
- src/stories/containers/cu-activity/cu-activity.tsx
https://trello.com/c/2oUtOCfG/143-changetracking-v1-coreunitactivityfeed-page
Added sort
Added darkmode
Fix on links target
> [SES-143] Activity feed

- src/stories/components/cu-table-column-summary/cu-table-column-summary.tsx
- src/stories/components/markdown/renderUtils.tsx
PlaceHolder empty state dark mode and not data in transparency report
fix-alignment-and-some-fonts
> FIX-Aligment-and-some-fonts

- feature-flags/feature-flags.development.ts
- feature-flags/feature-flags.interface.ts
- feature-flags/feature-flags.production.ts
- feature-flags/feature-flags.staging.ts
- src/core/business-logic/core-units.ts
- src/core/models/dto/core-unit.dto.ts
- src/stories/components/card-navegation/card-expenses.tsx
- src/stories/components/markdown/md-view-container.tsx
- src/stories/components/markdown/md-view.tsx
- src/stories/containers/cu-about-2/cu-about-container-2.tsx
- src/stories/containers/cu-about-2/cu-about.mvvm.ts
- src/stories/containers/cu-about/cu-about-container.tsx
- src/stories/containers/transparency-report/transparency-comments/transparency-comments.tsx
- src/stories/containers/transparency-report/transparency-report.mvvm.ts
- src/stories/containers/transparency-report/transparency-report.tsx
150-coreunitfinancestransparencyreporting-v2-budget-line-item-comments
Add feature flags for the new tab
Add function to get comments
Add link to activity view
>  SES- 150 coreunitfinancestransparencyreporting v2 budget line item comments

- src/stories/components/relate-mips/relate-mips.tsx
- src/stories/containers/transparency-report/transparency-report.tsx
SES-146-userexperience-v1-implement-new-font-and-spacing-for-better-ux
Fix issues relate mips and others fonts
> Fix issues relate mips and others fonts

- src/stories/containers/transparency-report/transparency-audit/transparency-audit.tsx
SES-156-navigation-v2-navigate-to-makerburn-from-empty-state-of-cufinance-page
Add correct empty state
> Add correct empty state

- src/stories/components/relate-mips/relate-mips.tsx
#No Ticket
#Action:
Fix-padding
> Fix-padding

- feature-flags/feature-flags.development.ts
- src/stories/components/card-navegation/card-expenses.tsx
- src/stories/components/card-navegation/information-card.tsx
- src/stories/components/markdown/md-view-container.tsx
- src/stories/components/markdown/md-view.tsx
- src/stories/components/relate-mips/relate-mips.tsx
- src/stories/containers/cu-about-2/cu-about-container-2.tsx
- src/stories/containers/cu-about/cu-about-container.tsx
- src/stories/containers/transparency-report/transparency-report.mvvm.ts
SES-154-changetracking-v1-activity-feed-navigation-element-button-on-coreunitabout-page
Fix height card with 190px
> Fix issues new card

- src/stories/components/core-unit-summary/core-unit-summary.tsx
- src/stories/components/relate-mips/relate-mips.tsx
SES-146-userexperience-v1-implement-new-font-and-spacing-for-better-ux
Fix-spacing-fix-style
> SES-Fix-spacing-fix-style

- src/stories/containers/transparency-report/transparency-report.tsx
SES-153-changetracking-v1-budgetstatementlastupdate-element
Update-BudgetStatementLastUpdate-element
> SES-153-changetracking-v1-budgetstatementlastupdate-element

- src/stories/components/core-unit-card/core-unit-card.tsx
- src/stories/components/cu-activity-table/cu-activity-item.tsx
- src/stories/components/cu-activity-table/cu-activity-table.tsx
- src/stories/containers/cu-activity/cu-activity.tsx
https://trello.com/c/2oUtOCfG/143-changetracking-v1-coreunitactivityfeed-page
> [SES-143] Activity Feed Fixes

- src/stories/containers/transparency-report/transparency-report.tsx
> fix-letter-spacing

- src/core/enums/button-type.enum.ts
- src/stories/components/404/not-found-component-404.tsx
- src/stories/components/card-navegation/card-expenses.tsx
- src/stories/components/card-navegation/information-card.tsx
- src/stories/components/custom-button/custom-button.tsx
- src/stories/components/header/select-link-website/item-select/item-website.tsx
- src/stories/components/markdown/md-view.tsx
- src/stories/components/markdown/renderUtils.tsx
- src/stories/containers/cu-table/cu-table-2.tsx
- src/stories/containers/cu-table/cu-table-filters.tsx
SES-154-changetracking-v1-activity-feed-navigation-element-button-on-coreunitabout-page
Refactoring custom button
Fix-error-card
resolving-activity-hover
> Fix issues card and letter

- src/stories/components/card-navegation/card-expenses.tsx
- src/stories/components/cu-activity-table/cu-activity-table.placeholder.tsx
- src/stories/components/cu-table-column-summary/cu-table-column-summary.tsx
- src/stories/components/custom-table/placeholder.tsx
- src/stories/components/markdown/md-view.tsx
- src/stories/components/markdown/renderUtils.tsx
- src/stories/components/transparency-card/transparency-card.tsx
154-changetracking-v1-activity-feed-navigation-element-button-on-coreunitabout-page
Fix-fonts-tooltip
Add button width
> SES-154-changetracking-v1-activity-feed-navigation-element-button-on-coreunitabout-page

- src/core/utils/sitemap.ts
- src/stories/components/core-unit-card/core-unit-card.tsx
- src/stories/components/custom-multi-select/custom-multi-select.tsx
- src/stories/components/custom-sort-select/custom-sort-select.tsx
- src/stories/components/custom-sort-select/sort-item.tsx
- src/stories/components/custom-table/custom-table-2.tsx
- src/stories/components/reset-button/reset-button.tsx
- src/stories/components/search-input/search-input.tsx
- src/stories/components/svg/check.tsx
- src/stories/components/svg/filter.tsx
- src/stories/components/svg/triangle-down.tsx
- src/stories/components/svg/triangle-up.tsx
- src/stories/components/svg/triangles.tsx
- src/stories/containers/cu-activity/cu-activity.tsx
- src/stories/containers/cu-table/cu-table-2.mvvm.ts
- src/stories/containers/cu-table/cu-table-2.tsx
- src/stories/containers/cu-table/cu-table-filters.tsx
- src/stories/containers/cu-table/cu-table.tsx
https://trello.com/c/VIVEx6Sp/114-qa-bug-findings-v-20-r
> [SES-114] New filter and sort for responsive

- feature-flags/feature-flags.production.ts
- feature-flags/feature-flags.staging.ts
- src/core/business-logic/core-units.ts
- src/core/models/dto/core-unit.dto.ts
- src/stories/components/core-unit-card/core-unit-card.tsx
- src/stories/containers/cu-about/cu-about-slice.ts
- src/stories/containers/cu-table/cu-table-2.mvvm.ts
- src/stories/containers/cu-table/cu-table.api.ts
- src/stories/containers/cu-table/cu-table.renders.tsx
- src/stories/containers/transparency-report/transparency-report.api.ts
- src/stories/containers/transparency-report/transparency-report.mvvm.ts
Now uses last activity field from the API to show the changes
> Last Modified Date

- src/stories/components/markdown/md-view.tsx
#No ticket
#Actions
Fix-height
> fix-card-expenses

- src/stories/components/markdown/renderUtils.tsx
#No ticket
#Action
fix-space-list
> fix-space-list

- src/stories/components/cu-activity-table/cu-activity-table.placeholder.tsx
- src/stories/components/custom-button/custom-button.tsx
> FIX-correct button Style in Empty

- src/stories/components/advanced-inner-table/advanced-inner-table.tsx
- src/stories/containers/transparency-report/transparency-actuals/transparency-actuals-2.mvvm.ts
- src/stories/containers/transparency-report/transparency-forecast/transparency-forecast-2.mvvm.ts
- src/stories/containers/transparency-report/transparency-report.tsx
Add bold to the subtotal and height
> SES-159-qa-bug-findings-v-30-r

- src/stories/components/advanced-inner-table/advanced-inner-table.tsx
- src/stories/containers/transparency-report/transparency-actuals/transparency-actuals-2.mvvm.ts
- src/stories/containers/transparency-report/transparency-forecast/transparency-forecast-2.mvvm.ts
> fix-subtotal-line

- src/stories/components/advanced-inner-table/advanced-inner-table.tsx
> fix-error-duplicate-line

- pages/cookies-policy/index.tsx
- src/core/utils/const.ts
- src/stories/components/footer/iconsData.tsx
- src/stories/containers/cookies-policy/cookies-policy-container.tsx
SES-175-analytics-v1-cookies-policy-page
Add data and the index page
Add container of page
> SES 175 analytics v1 cookies policy page

- pages/activity-feed/index.tsx
- src/stories/components/cu-activity-table/cu-activity-item.tsx
- src/stories/components/cu-activity-table/cu-activity-table.tsx
- src/stories/containers/cu-activity/cu-activity.tsx
- src/stories/containers/global-activity/global-activity.api.ts
- src/stories/containers/global-activity/global-activity.mvvm.ts
- src/stories/containers/global-activity/global-activity.tsx
https://trello.com/c/EXCDxj9c/171-feature-changetracking-v2
All but the filters done
> [SES-171] changetracking v2 globalactivityfeed page

- package.json
- pages/_app.tsx
- src/core/hooks/scroll-hooks.ts
- src/core/hooks/useLocalStorage.ts
- src/core/utils/new-activity-handler.ts
- src/stories/components/check-box/check-box.tsx
- src/stories/components/cu-activity-table/cu-activity-table.tsx
- src/stories/components/footer/description-footer.tsx
- src/stories/components/footer/footer.tsx
- src/stories/components/footer/iconsData.tsx
- src/stories/components/svg/check-on-new.tsx
- src/stories/containers/cookies-policy/cookies-policy-banner.mvvm.ts
- src/stories/containers/cookies-policy/cookies-policy-banner.tsx
- src/stories/containers/cookies-policy/cookies-policy-container.tsx
- src/stories/containers/cu-table/cu-table-2.tsx
- yarn.lock
PlaceHolder empty state dark mode and not data in transparency report
Add checkbox component
Add banner for cookies
Add dark mode and some change svg
> Ses 176 banner analytics v1 cookies policy

- src/stories/components/markdown/md-view.tsx
> Add primary button

- src/stories/containers/transparency-report/transparency-report.api.ts
> Add id to query

- src/core/business-logic/core-units.ts
- src/stories/components/custom-pager/custom-pager.tsx
- src/stories/components/pagination/InsidePagination.tsx
- src/stories/components/pagination/bread-crumb-mobile.tsx
- src/stories/components/svg/ArrowLeft.tsx
- src/stories/components/svg/ArrowMobileLeft.tsx
- src/stories/components/svg/ArrowMobileRight.tsx
- src/stories/components/svg/ArrowRight.tsx
- src/stories/containers/transparency-report/transparency-report.mvvm.ts
- src/stories/containers/transparency-report/transparency-report.tsx
https://trello.com/c/VV4dX1cU/158-qc-round-v-30-r
Add previous stop go back in months
> Add previous stop go back in months

- src/stories/components/custom-button/custom-button.tsx
- src/stories/containers/cookies-policy/cookies-policy-banner.mvvm.ts
- src/stories/containers/cookies-policy/cookies-policy-banner.tsx
- src/stories/containers/cookies-policy/cookies-policy-container.tsx
FIXES::::::175-feature-analytics-v1
Add with button and default checkbox state
Add dark border and mobile border color permanent
> Fix issues cookies page

- src/core/enums/button-type.enum.ts
- src/stories/components/custom-button/custom-button.tsx
- src/stories/components/markdown/md-view.tsx
- src/stories/containers/cookies-policy/cookies-policy-container.tsx
#NO Ticket
Actions:
Fix-color and letter
> Fix-color and letter

- src/stories/components/advanced-inner-table/advanced-inner-table.tsx
> correct line dark mode

- pages/_app.tsx
- src/stories/components/footer/description-footer.tsx
- src/stories/containers/cookies-policy/cookies-policy-banner.tsx
No ticket
Add links footer and navigation in page for cookies
> Add links footer and navigation in page for cookies

- pages/_app.tsx
- src/core/context/ThemeContext.tsx
- src/stories/components/footer/description-footer.tsx
- src/stories/components/footer/footer.tsx
- src/stories/components/footer/iconsData.tsx
- src/stories/components/header/header.tsx
Add router in Header delete a link
Fix links router in footer
> Fix issues rehidratation banner policy 2

- styles/theme/dark.ts
- styles/theme/light.ts
#No ticket
Add default Inter for the body
Add default fonts for the body
> Add default fonts for the body

- src/stories/components/core-unit-card/core-unit-card.tsx
> Social icons align

- src/stories/components/cu-table-column-links/cu-table-column-links.tsx
- src/stories/components/footer/description-footer.tsx
- src/stories/components/header/select-link-website/select-link.tsx
- src/stories/components/title-navigation-cu-about/title-navigation-cu-about.tsx
> Delete gap property

- src/core/business-logic/core-units.ts
- src/stories/components/seo-head/seo-head.tsx
- src/stories/components/title-navigation-cu-about/title-navigation-cu-about.tsx
- src/stories/containers/cu-table/cu-table.renders.tsx
https://trello.com/c/VNad2EW2/193-feature-coreunitabout-v3
Add new condition obsolete and also to disable zooms
> Add new condition obsolete and also to disable zooms

- src/core/business-logic/core-units.ts
- src/stories/components/seo-head/seo-head.tsx
- src/stories/components/title-navigation-cu-about/title-navigation-cu-about.tsx
- src/stories/containers/cu-table/cu-table.renders.tsx
Reverts DSpotDevelopers/makerdao-ses-dashboard#369
> Revert "Add new condition obsolete and also to disable zooms"

- src/core/business-logic/core-units.ts
- src/stories/components/seo-head/seo-head.tsx
- src/stories/components/title-navigation-cu-about/title-navigation-cu-about.tsx
- src/stories/containers/cu-table/cu-table.renders.tsx
#Hot-fix
#Actions
Fix-hot-offboarding
> Fix-hot-offboarding

- src/stories/containers/cu-table/cu-table-2.mvvm.ts
> Fix-count-pop-over

- src/core/hooks/useThemeMode.ts
#No ticket
#Actions
Default theme light
> Default theme light

- src/core/business-logic/core-units.ts
- src/core/models/dto/core-unit.dto.ts
- src/stories/containers/transparency-report/transparency-comments/comment-item.tsx
- src/stories/containers/transparency-report/transparency-comments/comments-list.tsx
- src/stories/containers/transparency-report/transparency-comments/transparency-comments.tsx
- src/stories/containers/transparency-report/transparency-report.api.ts
https://trello.com/c/s87DZLZr/188-feature-coreunitfinancestransparencyreporting-v3
Function get comments and number comments
Correct change from the API in the view
> SES 188 feature core unit finances transparency reporting v3 API

- src/core/business-logic/core-units.ts
- src/core/enums/cu-job.enum.ts
- src/core/hooks/useThemeMode.ts
- src/core/utils/color.utils.ts
- src/stories/containers/transparency-report/transparency-comments/comment-item.tsx
- src/stories/containers/transparency-report/transparency-report.tsx
188-feature-coreunitfinancestransparencyreporting-v3
Fix issues card comments
Add new color
> SES 158 qc round v 30 round four

- src/stories/components/pagination/bread-crumb-mobile.tsx
- src/stories/containers/cookies-policy/cookies-policy-banner.mvvm.ts
Qa-bug-findings-v-30-r
Fix cookies and Nav Bar mobile
> Fix cookies and navBar mobile

- src/stories/components/cu-activity-table/cu-activity-table.placeholder.tsx
- src/stories/components/pagination/bread-crumb-mobile.tsx
- src/stories/components/reset-button/reset-button.tsx
- src/stories/containers/global-activity/global-activity.tsx
Change name button place holder and add text button
Add correct gap and button text in mobile
> Fix qc round 5

- src/core/business-logic/core-units.ts
- src/stories/components/pagination/bread-crumb-mobile.tsx
- src/stories/components/reset-button/reset-button.tsx
#No ticket
Solver no data in obsolete value
> Fix-obsolte-no-vapue-delete-border

- src/core/business-logic/core-units.ts
- src/stories/components/relate-mips/relate-mips.tsx
- src/stories/containers/transparency-report/transparency-comments/comments-list.tsx
Add correct date for comment and also plural
> Fix comments QA session SES

- src/core/business-logic/core-units.ts
- src/stories/containers/transparency-report/transparency-comments/comments-list.tsx
- src/stories/containers/transparency-report/transparency-comments/transparency-comments.tsx
- src/stories/containers/transparency-report/transparency-report.mvvm.ts
- src/stories/containers/transparency-report/transparency-report.tsx
#No ticket
#Action
Add filters to comments
> Add filter in comments

- pages/_document.tsx
- pages/cookies-policy/index.tsx
- pages/index.tsx
https://dev.to/shinshin86/workaround-reference-the-cookie-value-in-document-js-in-next-js-32am
Analytic 
Add InitialProps in _document y SSR in all client side
> Add InitialProps in _document y SSR in all client side

- src/stories/components/text-input/text-input.tsx
- src/stories/containers/auth/change-password/change-password.tsx
- src/stories/containers/auth/delete-account/delete-account.tsx
- src/stories/containers/auth/enable-disable-accounts/enable-disable-accounts.tsx
- src/stories/containers/auth/login/login.tsx
Add dark mode and password through array
> Add dark mode and password through array

- src/stories/components/menu-navigation/swtich-buttom.tsx
> Correct click area

- feature-flags/feature-flags.development.ts
- feature-flags/feature-flags.interface.ts
- feature-flags/feature-flags.production.ts
- feature-flags/feature-flags.staging.ts
- src/stories/containers/transparency-report/transparency-report.mvvm.ts
- src/stories/containers/transparency-report/transparency-report.tsx
> Disabled MKR vesting and Audit Reports tabs

- src/stories/components/menu-navigation/menu-theme/menu-theme.tsx
- src/stories/components/menu-navigation/menu-user/menu-user.tsx
- src/stories/components/text-input/text-input.tsx
- src/stories/containers/users/create-account/create-account.mvvm.ts
- src/stories/containers/users/create-account/create-account.tsx
Fix the problem in the Contextual menu
> Fix the problem in the Contextual menu

- src/stories/components/menu-navigation/menu-theme/menu-theme.tsx
- src/stories/components/menu-navigation/menu-user/menu-user.tsx
- src/stories/containers/users/create-account/create-account.mvvm.ts
- src/stories/containers/users/enable-disable-accounts/enable-disable-accounts.tsx
Fix-order-message-error
Validate confirm password only again password
> SES fix issues 189 feature User Accounts

- src/stories/components/cu-activity-table/cu-activity-item.tsx
https://trello.com/c/0uXha5wy/202-qc-round-v-40-r
- Add `href` to activity items instead of `onClick`
> Fix Activity Feed SEO

- pages/auth/create-account/index.tsx
- pages/auth/enable-disable-accounts/index.tsx
- pages/auth/manage/index.tsx
- pages/auth/user-profile/index.tsx
- src/core/context/AuthContext.tsx
- src/core/utils/string.utils.ts
- src/stories/components/button/switch-toogle/switch-component.tsx
- src/stories/components/header/header.tsx
- src/stories/components/user-card/user-card.tsx
- src/stories/containers/auth/change-password/change-password.tsx
- src/stories/containers/users/delete-account/delete-account.mvvm.ts
- src/stories/containers/users/enable-disable-accounts/enable-disable-accounts.tsx
- src/stories/containers/users/user-profile/user-profile-container.tsx
- src/stories/containers/users/user-profile/user-profile.tsx
- src/stories/helpers/helpers.tsx
Show some page only if is admin
> Show some page only if is admin

- src/core/enums/role.enum.ts
- src/core/hooks/useIsAdmin.ts
- src/core/models/dto/auth.dto.ts
- src/core/utils/color.utils.ts
- src/core/utils/string.utils.ts
- src/stories/components/user-card/user-card.tsx
- src/stories/containers/users/user-profile/user-profile.tsx
Show all roles in view Profile
Show All roles in the view of Profile
> SES resolve discord issues manager account

- .vscode/settings.json
- pages/auth/manage/my-profile.tsx
- pages/login/index.tsx
- src/core/context/AuthContext.tsx
- src/core/utils/auth-storage.ts
- src/core/utils/fetcher.ts
- src/core/utils/routing.ts
- src/stories/components/user-card/user-card.tsx
- src/stories/containers/auth/change-password/change-password.mvvm.ts
- src/stories/containers/auth/change-password/change-password.tsx
- src/stories/containers/users/create-account/create-account.tsx
- src/stories/containers/users/manage-accounts/manage-accounts.mvvm.tsx
- src/stories/containers/users/user-profile/user-profile.tsx
- src/stories/containers/users/users-manager/manager-account-layout.mvvm.tsx
- create an auth fetcher to use when the request requires authentication and avoid code duplication
- added a black border to action buttons in small resolutions
- No validate old password in the Change Password form
- Use the Wrong Old Password error message when the old password is incorrect
- Go back instead home when the password is changed successfully
- Fix the avatar in the Change Password page
> [SES-189] Fix issues

- src/core/context/AuthContext.tsx
- src/stories/components/header/select-link-website/menu-items.tsx
- src/stories/components/header/select-link-website/select-link.tsx
- src/stories/containers/users/user-profile/user-profile.tsx
Add link in mobile resolution
Await for redirect to login
> SES issues manager account round 2

- src/stories/containers/auth/change-password/change-password.tsx
- src/stories/containers/users/create-account/create-account.mvvm.ts
- src/stories/containers/users/create-account/create-account.tsx
Correct the route after create user
Add correct color in dark mode
> SES issues manager account round 3

- src/stories/containers/auth/change-password/change-password.tsx
Fix problem change password view
> Fix problem change password view

- src/core/utils/form-validation.ts
- src/stories/containers/auth/change-password/change-password.mvvm.ts
- src/stories/containers/users/create-account/create-account.mvvm.ts
- Fix password validation in Create Account and Change Password
> Fix password validation

- src/stories/containers/users/user-profile/user-profile-container.tsx
- src/stories/containers/users/user-profile/user-profile.tsx
Add correct state of theme in view profile
> Add correct state of theme in view profile

- feature-flags/feature-flags.staging.ts
> feature-flags

- src/stories/containers/auth/change-password/change-password.tsx
- src/stories/containers/auth/login/login.mvvm.ts
- src/stories/containers/auth/login/login.tsx
- src/stories/containers/users/create-account/create-account.mvvm.ts
- src/stories/containers/users/delete-account/delete-account.tsx
- src/stories/containers/users/user-profile/user-profile.tsx
Fix more informative error if user is disable
> Wip-Fix more informative error if user is disable

- src/stories/containers/auth/login/login.mvvm.ts
- src/stories/containers/users/create-account/create-account.tsx
- src/stories/containers/users/managed-user-profile/managed-user-profile.tsx
- src/stories/containers/users/user-profile/user-profile.tsx
Fix message in depending user
Fix alignment in profile view and correct text in the profile
> SES issues manager account round 4

- src/stories/components/user-card/user-card.tsx
- src/stories/containers/users/delete-account/delete-account.mvvm.ts
- src/stories/containers/users/managed-user-profile/managed-user.profile.mvvm.ts
https://trello.com/c/ZaR0ufjt/195-qa-bug-findings-v-40-r
Fix-error-disable and remove client configuration
> Fix-error-disable and remove client configuration

- src/stories/containers/auth/change-password/change-password.mvvm.ts
- Changed confirmation password error message
> Change passowrd must match message

- .eslintrc.js
- src/core/utils/dictionary.js
- src/core/utils/string.utils.ts
- src/stories/components/notification/notification.tsx
- src/stories/containers/users/managed-user-profile/managed-user-profile.tsx
- styles/globals.scss
Fix two icons in safari
Fix size of notification and uncomment spell check
> Fix two icons in safari

- src/stories/containers/auth/change-password/change-password.tsx
- src/stories/containers/users/delete-account/delete-account.tsx
Add first letter uppercase and fix alignment in delete mobile
> Add first letter uppercase and fix alignment in delete mobile

- pages/auth/change-password/index.tsx
- src/stories/components/user-card/user-card.skeleton.tsx
- src/stories/containers/auth/change-password/change-password.tsx
- src/stories/containers/users/manage-accounts/manage-accounts.mvvm.tsx
- src/stories/containers/users/manage-accounts/manage-accounts.tsx
- src/stories/containers/users/user-profile/user-profile-container.tsx
- src/stories/containers/users/user-profile/user-profile.tsx
- src/stories/containers/users/users-manager/manager-account-layout.mvvm.tsx
- Add Skeleton loader to Manage Accounts relate pages
- Add correct margin to user profile and user change password cards
> Add Skeleton loader to Manage Accounts

- src/core/utils/dictionary.js
- src/stories/components/footer/iconsData.tsx
Fix the links
Add links to footer and put correct order
> Add links to footer and put correct orden

- pages/auth/delete-account/index.tsx
- pages/auth/manage/delete-my-account.tsx
- pages/auth/manage/user/[username]/delete-account.tsx
- src/stories/containers/users/delete-account/delete-account.mvvm.ts
- src/stories/containers/users/delete-account/delete-account.tsx
- src/stories/containers/users/manage-accounts/manage-accounts.mvvm.tsx
- src/stories/containers/users/managed-user-profile/managed-user.profile.mvvm.ts
- src/stories/containers/users/user-profile/user-profile.tsx
- Create separate pages for admin delete account, regular user account, and admin delete user account
- Display the admin related delete pages under the tabs
> [FIX-189] Add delete account under the tabs in the account manage

- src/stories/containers/users/delete-account/delete-account.mvvm.ts
- src/stories/containers/users/delete-account/delete-account.tsx
Fix Notifications
Fix multiples notifications
> Fix-multiples-notifications

- pages/auth/change-password/index.tsx
- pages/auth/delete-account/index.tsx
- src/stories/containers/auth/change-password/change-password.tsx
- src/stories/containers/users/delete-account/delete-account.tsx
- src/stories/containers/users/user-profile/user-profile-container.tsx
- src/stories/containers/users/user-profile/user-profile.tsx
- Set correct margins to the card of:
- user profile page
- user delete pages
- user change password page
> [FIX189] Fix margins

- src/stories/components/user-card/user-card.tsx
- src/stories/containers/users/managed-user-profile/managed-user-profile.tsx
Fix align when user name is too long
Fix size of user name
Correct when text is to long user name
> Correct when text is to long user name

- src/stories/components/menu-navigation/menu-theme/menu-item-theme.tsx
- src/stories/components/menu-navigation/menu-user/menu-item-user.tsx
- src/stories/containers/users/delete-account/delete-account.tsx
- src/stories/containers/users/managed-user-profile/managed-user-profile.tsx
Fix Align
Fix align in view profile
> fix alig in view profile

- src/stories/components/button/switch-toogle/switch-component.tsx
- src/stories/components/user-card/user-card.tsx
- src/stories/containers/users/managed-user-profile/managed-user-profile.tsx
- src/stories/containers/users/managed-user-profile/managed-user.profile.mvvm.ts
Disable the switches while the change is being done
> Fisable switch while a query is pending

- src/stories/containers/users/delete-account/delete-account.mvvm.ts
- src/stories/containers/users/delete-account/delete-account.tsx
> Disable delete btn while the request is being processed

- src/stories/containers/users/managed-user-profile/managed-user-profile.tsx
- src/stories/containers/users/managed-user-profile/managed-user.profile.mvvm.ts
> Fix to long text

- src/stories/components/footer/iconsData.tsx
> Fix the link

- src/stories/containers/auth/login/login.mvvm.ts
- src/stories/containers/users/delete-account/delete-account.tsx
Remove message error form server
> Remove message error form server

- src/core/utils/dictionary.js
- src/stories/containers/users/managed-user-profile/managed-user.profile.mvvm.ts
- Update the modified user in the user list
> Update user list when there's a change

- pages/_app.tsx
- src/stories/components/notification/notification.tsx
- src/stories/containers/auth/change-password/change-password.mvvm.ts
- src/stories/containers/users/delete-account/delete-account.tsx
- src/stories/helpers/helpers.tsx
https://trello.com/c/ZaR0ufjt/195-qa-bug-findings-v-40-r
- Create a new toast helper
- Show a success message after changing the password
> Show notification after successfully password change

- src/stories/components/notification/notification.tsx
> Add padding

- src/stories/containers/transparency-report/common/expense-report-status-indicator/expense-report-status-indicator.tsx
- src/stories/containers/transparency-report/transparency-auditor-comments/auditor-comment-card.tsx
- src/stories/containers/transparency-report/transparency-auditor-comments/comment-container/auditor-comments-container.tsx
- src/stories/containers/transparency-report/transparency-auditor-comments/comment-container/useCommentsContainer.ts
- src/stories/containers/transparency-report/transparency-auditor-comments/comment-form/comment-form.tsx
- src/stories/containers/transparency-report/transparency-auditor-comments/comment-form/useCommentForm.tsx
- src/stories/containers/transparency-report/transparency-auditor-comments/generic-comment-card.tsx
- src/stories/containers/transparency-report/transparency-auditor-comments/no-comments.stories.tsx
- src/stories/containers/transparency-report/transparency-auditor-comments/no-comments.tsx
- src/stories/containers/transparency-report/transparency-auditor-comments/participant-roles.stories.tsx
- src/stories/containers/transparency-report/transparency-auditor-comments/participant-roles.tsx
Added empty state when there are no comments and fixed a few issues
> [SES-203] Added empty state for the comments and fixed issues

- src/core/models/dto/core-unit.dto.ts
- src/stories/containers/transparency-report/transparency-auditor-comments/participant-roles.tsx
- src/stories/containers/transparency-report/transparency-report.api.ts
- src/stories/containers/transparency-report/transparency-report.mvvm.ts
Changed activity feed data from API to the BudgetStatement object
> [SES-203] Use activity feed from budget statement

- src/stories/components/card-navegation/card-expenses.tsx
> Add correct space

- src/core/context/CookiesContext.tsx
- src/core/hooks/useLastVisit.ts
- src/core/hooks/useLastVist.api.ts
- src/stories/components/cu-activity-table/cu-activity-table.tsx
- src/stories/components/tabs/tabs.tsx
- src/stories/containers/cookies-policy/cookies-policy-banner.mvvm.ts
- src/stories/containers/transparency-report/transparency-auditor-comments/comment-container/useCommentsContainer.ts
- src/stories/containers/transparency-report/transparency-auditor-comments/participant-roles.tsx
- src/stories/containers/transparency-report/transparency-report.mvvm.ts
- src/stories/containers/transparency-report/transparency-report.tsx
Show indicator when there are new comments since the last visit
- created `useLastActivity` hook
- improved cookies context types
- show activity indicator when required
> [SES-203] SES Expense Report new Audit Activity Indicator

- src/stories/containers/transparency-report/transparency-report.mvvm.ts
#No ticket
Fix the bugs navigation between months
> Fix-bugs-months-navigations

- src/core/utils/last-visit-handler.ts
- src/stories/components/cu-activity-table/cu-activity-table.tsx
- src/stories/containers/transparency-report/transparency-report.mvvm.ts
Mark the budget statements as visited when leaving the comments tabs and fixed some issues related to the activity indicator
> [SES-203] Fix activity indicator issues

- pages/_app.tsx
- src/core/hooks/useThemeMode.ts
- src/core/utils/date.utils.ts
- src/core/utils/types-helpers.ts
- src/stories/containers/cookies-policy/cookies-policy-banner.mvvm.ts
https://trello.com/c/vl1Dc2j6/222-feature-cookie-issue
Add theme Mode cookies object and add expires date for all cookies
> Fix-issue-relate-cookies

- src/core/context/AuthContext.tsx
- src/stories/components/header/header.tsx
- src/stories/containers/auth/login/login.mvvm.ts
- src/stories/containers/users/delete-account/delete-account.mvvm.ts
- src/stories/containers/users/user-profile/user-profile.tsx
No ticket
Fixed recursive redirect on login page
> Fix login issue

- pages/core-unit/[code]/activity-feed.tsx
- pages/core-unit/[code]/finances/reports/index.tsx
- pages/core-unit/[code]/index.tsx
- src/stories/components/core-unit-summary/core-unit-summary.api.ts
- src/stories/components/core-unit-summary/core-unit-summary.tsx
- src/stories/components/title-navigation-cu-about/title-navigation-cu-about.tsx
- src/stories/containers/cu-about-2/cu-about-container-2.tsx
- src/stories/containers/transparency-report/transparency-report.tsx
Improved the top section of the Expense report page
- removed unused code
- optimize handle scroll to avoid issues when hiding the CU summary
- Move the "Expense Report" text to the bottom of the page
- hide the cu summary from the cu activity feed and the expense report page
> [SES-225] Improved Expense Report Top Section Summary

- src/stories/components/cu-table-column-summary/cu-table-column-summary.tsx
https://trello.com/b/iebIfrww/ses-dashboard
Hidden pop over small devices
> Hidden pop-over in small devices

- feature-flags/feature-flags.development.ts
- feature-flags/feature-flags.production.ts
- feature-flags/feature-flags.staging.ts
> [SES-225] Disable Audit Reports tab

- pages/core-unit/[code]/finances/reports/index.tsx
- src/stories/components/header/header.tsx
- src/stories/containers/cu-about-2/cu-about.api-2.ts
- src/stories/containers/cu-about/cu-about.api.ts
- src/stories/containers/cu-activity/cu-activity.api.ts
- src/stories/containers/transparency-report/transparency-report.api.ts
Fix the queries due modifications in the API
> [SES-215] Fix queries

- src/stories/components/custom-table/custom-table-2.tsx
- src/stories/components/header/select-link-website/item-select/item-website.tsx
- src/stories/components/markdown/md-view.tsx
- src/stories/containers/cu-about-2/cu-about-container-2.tsx
- src/stories/containers/cu-about-2/cu-about.mvvm.ts
Fix code in the URL
Fix-console-error
> Fix issue inside links

- src/stories/containers/cu-about-2/cu-about-container-2.tsx
#No ticket
#Action
Hidden section when there is no data
> Hidden section when there is no data

- src/stories/components/footer/description-footer.tsx
- src/stories/components/header/header.tsx
- src/stories/components/menu-navigation/menu-user/menu-item-user.tsx
- src/stories/components/menu-navigation/menu-user/menu-user.tsx
- src/stories/components/title-navigation-cu-about/title-navigation-cu-about.tsx
https://trello.com/b/iebIfrww/ses-dashboard
Fix-link-login-screen
> Fix-issue-Links

- src/stories/components/custom-bar-chart/custom-bar-chart.tsx
Fixed the height of the budget charts
> [SES-215] Fix the budget chart

- src/stories/components/title-navigation-cu-about/title-navigation-cu-about.tsx
- src/stories/containers/transparency-report/transparency-forecast/transparency-forecast-2.tsx
- src/stories/containers/transparency-report/transparency-mkr-vesting/transparency-mkr-vesting-2.tsx
- src/stories/containers/transparency-report/transparency-transfer-request/transparency-transfer-request-2.tsx
Add missing status in Cu-about
Delete unnecessary space text with link in the tabs
> Fix QA finds release 6

- .storybook/preview.jsx
- src/core/utils/storybook/decorators.tsx
- src/core/utils/storybook/factories.tsx
No ticket
Fixed stories source code in the storybook docs tab
> [SES-NO-TICKET] Fixed storybook docs source code

- src/stories/components/seo-head/seo-head.tsx
- src/stories/containers/cu-table/cu-table-2.tsx
Fixed SEO metadata in the home page
> [SES-QA-231] Fix homepage SEO

- src/stories/components/card-navegation/card-expenses.stories.tsx
https://trello.com/c/vl1Dc2j6/222-feature-various-ux-improvements
Add storybook
> Add storybook

- src/stories/containers/cu-table/cu-table-2.mvvm.ts
- src/stories/containers/transparency-report/transparency-actuals/transparency-actuals-2.tsx
- src/stories/containers/transparency-report/transparency-forecast/transparency-forecast-2.tsx
- src/stories/containers/transparency-report/transparency-mkr-vesting/transparency-mkr-vesting-2.tsx
- src/stories/containers/transparency-report/transparency-transfer-request/transparency-transfer-request-2.tsx
Add default order when the list is order
> Add default order when the list is order

- src/stories/components/tabs/tabs.stories.tsx
https://trello.com/c/vl1Dc2j6/222-feature-various-ux-improvements
Add story for tab
> Add story for tab

- package.json
- src/stories/containers/transparency-report/transparency-auditor-comments/auditor-comment-card.stories.tsx
- yarn.lock
Upgrade the Figma addon for storybook to get a better match of the components in different breakpoints when they are different
> [SES-225] Upgrade figma addon for storybook

- src/stories/components/custom-bar-chart/custom-bar-chart.stories.tsx
Added the integration with the Figma comparator of the Custom Bar Chart (Dark mode variants)
> [SES-] Added the integration of the Custom Bar Chart with figma

- src/stories/components/custom-bar-chart/custom-bar-chart.tsx
> Fix error in the bars

- package.json
- src/core/business-logic/builders/core-units.builder.ts
- src/core/business-logic/builders/cu-mip.builder.ts
- src/core/utils/storybook/decorators.tsx
- src/stories/components/core-unit-summary/core-unit-summary.stories.tsx
- src/stories/components/core-unit-summary/core-unit-summary.tsx
- src/stories/components/title-navigation-cu-about/title-navigation-cu-about.tsx
Add the Core Unit Summary related stories
> [SES-225] Added Core Unit Summary stories

- package.json
- src/core/context/AuthContext.tsx
- src/core/utils/auth-storage.ts
- src/core/utils/const.ts
- src/core/utils/dictionary.js
- yarn.lock
When the Auth token is expired, the app force a logout of the user
> [SES-QA-231] Fix expired jwt tokens issue

- src/stories/components/top-bar-select/top-bar-select.tsx
Fix-behavior-click-menu-close-menu
> Fix-behavior-click-menu-close-menu

- feature-flags/feature-flags.development.ts
- feature-flags/feature-flags.interface.ts
- feature-flags/feature-flags.production.ts
- feature-flags/feature-flags.staging.ts
- pages/core-units.tsx
- pages/index.tsx
- src/config/endpoints.ts
- src/config/routes.ts
- src/stories/components/core-unit-summary/core-unit-summary.tsx
- src/stories/components/header/header.tsx
- src/stories/components/header/menu-items.ts
- src/stories/components/top-bar-select/top-bar-select.tsx
- src/stories/containers/cu-table/cu-table-2.mvvm.ts
- src/stories/containers/cu-table/cu-table-filters.tsx
- src/stories/containers/cu-table/cu-table.tsx
https://trello.com/c/KHEsSLd9/233-feature-coreunittransparencyreporting-v5
Allow to enable/disable the finances overview page using feature flags
> [SES-233] Add finances overview page feature flag

- src/core/business-logic/core-units.ts
> Fix-fts-field-per-last-month #Cu-table

- pages/index.tsx
- src/stories/containers/finances-overview/Components/ExpensesChart/ExpensesChart.tsx
- src/stories/containers/finances-overview/Components/ExpensesChartSection/ExpensesChartSection.tsx
- src/stories/containers/finances-overview/Components/QuarterCarousel/QuarterCarousel.tsx
- src/stories/containers/finances-overview/Components/YearPicker/YearPicker.tsx
- src/stories/containers/finances-overview/finances-overview.tsx
- src/stories/containers/finances-overview/useFinancesOverview.ts
- Added the container and page title
- Created base components to implement all the Finances Overview page
> [SES-225] Added title and mockup components

- src/stories/components/custom-bar-chart/custom-bar-chart.tsx
Delimit range when min and max are close
> Delimit range when min and max are close

- .vscode/settings.json
- src/core/utils/humanization.ts
- src/stories/containers/finances-overview/Components/HorizontalBudgetBar/HorizontalBudgetBar.tsx
- src/stories/containers/finances-overview/Components/QuarterCard/QuarterCard.stories.tsx
- src/stories/containers/finances-overview/Components/QuarterCard/QuarterCard.tsx
- src/stories/containers/finances-overview/Components/QuarterCarousel/QuarterCarousel.tsx
Mocked up the Quarter card and its Stories  on Storybook
> [SES-225] Mocked up the Quarter Card

- .vscode/settings.json
- package.json
- src/core/utils/dictionary.js
- src/stories/containers/finances-overview/Components/HorizontalBudgetBar/HorizontalBudgetBar.tsx
- src/stories/containers/finances-overview/Components/QuarterCard/QuarterCard.stories.tsx
- src/stories/containers/finances-overview/Components/QuarterCard/QuarterCard.tsx
- src/stories/containers/finances-overview/Components/QuarterCarousel/QuarterCarousel.tsx
- src/stories/containers/finances-overview/finances-overview.tsx
- yarn.lock
Added the Quarter Card Carousel (including responsive) and updated the Quarter card responsive UI and its corresponding stories
> [SES-225] Implemented Quarter Cards Carousel & Improved responsiveness

- .github/workflows/chromatic.yaml
- package.json
Add TurboSnap to reduce the number of snapshots and build time of chromatic
https://www.chromatic.com/docs/turbosnap
> [SES-215] Add TurboSnap

- package.json
- src/core/models/dto/graph.dto.ts
- src/stories/containers/finances-overview/Components/ExpensesChart/ExpensesChart.tsx
- src/stories/containers/finances-overview/Components/ExpensesChartSection/ExpensesChartSection.tsx
- src/stories/containers/finances-overview/finances-overview.tsx
- yarn.lock
Add mock for the graph
Correct text total and up mock data for chart
> Ses chart mock data

- pages/index.tsx
- src/core/models/dto/expenses.dto.ts
- src/stories/containers/finances-overview/Components/QuarterCarousel/QuarterCarousel.tsx
- src/stories/containers/finances-overview/api/queries.ts
- src/stories/containers/finances-overview/finances-overview.tsx
- tsconfig.json
Connect the Quarters carousel with the API and render the pages in the server
> [SES-] Connect the quarters carousel with the API

- src/stories/containers/finances-overview/finances-overview.tsx
Add "Core Units" button in the finances page
> [SES-225] Add Core Units button

- src/core/business-logic/core-units.ts
- src/stories/components/team-members/team-member.stories.tsx
- src/stories/components/team-members/team-member.tsx
- src/stories/containers/cu-about-2/cu-about-container-2.tsx
> Fix-correct-fts

- src/core/models/dto/chart.dto.ts
- src/stories/containers/finances-overview/Components/ExpensesChart/ExpensesChart.tsx
- src/stories/containers/finances-overview/useFinancesOverview.ts
> Add dark mode chart

- src/stories/containers/finances-overview/Components/ExpensesChart/ExpensesChart.tsx
- src/stories/containers/finances-overview/useFinancesOverview.ts
> Add border in each bar

- src/core/utils/dictionary.js
- src/stories/containers/finances-overview/Components/QuarterCard/QuarterCard.tsx
- src/stories/containers/finances-overview/Components/QuarterCarousel/QuarterCarousel.tsx
- src/stories/containers/finances-overview/Components/QuarterCarousel/useQuarterCarousel.ts
- src/stories/containers/finances-overview/finances-overview.tsx
- src/stories/containers/finances-overview/useFinancesOverview.ts
- src/stories/containers/finances-overview/utils/quarters.ts
Add a divider line between each Q4 and Q1 of the next year
> [SES-225] Add quarter card divider

- pages/index.tsx
- src/core/models/dto/chart.dto.ts
- src/stories/containers/finances-overview/Components/ExpensesChart/ExpensesChart.tsx
- src/stories/containers/finances-overview/Components/ExpensesChartSection/ExpensesChartSection.tsx
- src/stories/containers/finances-overview/finances-overview.tsx
- src/stories/containers/finances-overview/useFinancesOverview.ts
Add integration with Api add change total dai per year add correct margin
> Add integration with Api add change total dai per year

- src/stories/containers/finances-overview/useFinancesOverview.ts
https://trello.com/b/iebIfrww/ses-dashboard
Add state to change values chart
> Add state to change values chart

- src/core/utils/string.utils.ts
- src/stories/containers/finances-overview/Components/ExpensesChart/ExpensesChart.tsx
- src/stories/containers/finances-overview/useFinancesOverview.ts
> Add function to format yAxis

- src/stories/containers/finances-overview/Components/ExpensesChart/ExpensesChart.tsx
- src/stories/containers/finances-overview/Components/ExpensesChart/LegendItem.tsx
> Add function to format y axis

- src/stories/containers/finances-overview/Components/HorizontalBudgetBar/HorizontalBudgetBar.tsx
- src/stories/containers/finances-overview/Components/QuarterCarousel/QuarterCarousel.tsx
- src/stories/containers/finances-overview/Components/QuarterCarousel/useQuarterCarousel.ts
Display correctly the values in the Bars of the QuarterCard, reduce the margin between card dividers, and fix the issue of the flicker of the cards on the first load
> [SES-225] Render correctly the values in the Quarter Card Bar

- src/stories/containers/finances-overview/Components/HorizontalBudgetBar/HorizontalBudgetBar.stories.tsx
- src/stories/containers/finances-overview/Components/HorizontalBudgetBar/HorizontalBudgetBar.tsx
Added Stories for the `HorizontalBudgetBar` component
> [SES-225] Add HorizontalBudgetBar stories

- src/stories/containers/finances-overview/Components/QuarterCarousel/QuarterCarousel.tsx
Increase the height of the quarter divider line
> [SES-QA-231] Fix height of the Quarter Divider line

- src/stories/containers/finances-overview/finances-overview.tsx
Fix the spacing of the Core Unit button
> [SES-231] Fix spacing of the Core Unit button

- src/stories/containers/finances-overview/Components/ExpensesChart/ExpensesChart.tsx
- src/stories/containers/finances-overview/useFinancesOverview.ts
Delete mock data and border forecast
> Delete mock data and border forecast

- src/stories/containers/finances-overview/Components/HorizontalBudgetBar/HorizontalBudgetBar.tsx
- src/stories/containers/finances-overview/Components/QuarterCarousel/useQuarterCarousel.ts
No ticket
Show the divider line on the Quarter carousel when there is just the exact number of quarters than the amount that need to be shown
> [SES-NO_TICKET] Fix hidden line

- src/core/utils/number.utils.ts
- src/stories/containers/finances-overview/Components/ExpensesChart/ExpensesChart.tsx
- src/stories/containers/finances-overview/Components/ExpensesChartSection/ExpensesChartSection.tsx
- src/stories/containers/finances-overview/Components/YearPicker/YearPicker.tsx
- src/stories/containers/finances-overview/finances-overview.tsx
- src/stories/containers/finances-overview/useFinancesOverview.ts
> Fix style in chart section

- src/core/business-logic/builders/total-expense-reports.builder.ts
- src/stories/containers/finances-overview/Components/QuarterCard/QuarterCard.stories.tsx
- src/stories/containers/finances-overview/Components/QuarterCard/QuarterCard.tsx
- src/stories/containers/finances-overview/Components/QuarterCarousel/QuarterCarousel.stories.tsx
- src/stories/containers/finances-overview/Components/QuarterCarousel/QuarterCarousel.tsx
Added Quarter Carousel stories
> [SES-225] Added Quarter Carousel stories

- src/stories/containers/finances-overview/Components/YearPicker/YearPicker.stories.tsx
- src/stories/containers/finances-overview/Components/YearPicker/YearPicker.tsx
Complete YearPicker stories and fixed styles
> [SES-225] Complete YearPicker stories

- src/stories/components/custom-bar-chart/custom-bar-chart.tsx
> [SES-QA-231] Fixed custom bar chart

- src/stories/containers/finances-overview/useFinancesOverview.ts
Correct the full border variable
> [SES-225]Correct the full border variable

- src/stories/containers/finances-overview/Components/ExpensesChart/ExpensesChart.tsx
##Description:
Same number of character in each month
##Actions
Fix-month-name
> Fix-month-name

- src/stories/containers/finances-overview/Components/ExpensesChart/ExpensesChart.tsx
> Change color line chart

- src/stories/containers/finances-overview/finances-overview.tsx
No ticket
Removed the image background of the Finances page
> [SES-NO_TICKET] Changed the background of the Finances page

- src/stories/containers/finances-overview/finances-overview.tsx
No ticket
Added SEO metadata to the Finance overview page
> [SES-NO_TICKET] Added SEO metadata

- src/stories/containers/finances-overview/Components/QuarterCarousel/QuarterCarousel.tsx
- src/stories/containers/finances-overview/finances-overview.stories.tsx
- src/stories/containers/finances-overview/finances-overview.tsx
Added stories for the Finances Overview pages and integrate it with Figma
> [SES-225] Implemented Stories for the Finances Overview page

- .storybook/preview.jsx
- package.json
- src/stories/components/cu-activity-table/cu-activity-item.stories.tsx
- src/stories/components/cu-activity-table/cu-activity-item.tsx
- src/stories/containers/transparency-report/transparency-auditor-comments/auditor-comment-card.tsx
- yarn.lock
https://trello.com/c/211SLIYi/244-pending-storybooks-of-r6
Add Activity Feed items to the storybook
> [SES-244] Implemented Activity Item stories

- src/core/utils/storybook/decorators.tsx
- src/core/utils/storybook/factories.tsx
- src/stories/components/footer/footer.stories.tsx
https://trello.com/c/211SLIYi/244-pending-storybooks-of-r6
Added Footer stories
> [SES-244] Added Footer Stories

- src/stories/components/cu-activity-table/cu-activity-table.stories.tsx
https://trello.com/c/211SLIYi/244-pending-storybooks-of-r6
Added Activity Table Global and Core Units variant stories
> [SES-244] Added ActivityTable stories

- src/core/models/dto/chart.dto.ts
- src/core/utils/dictionary.js
- src/stories/containers/finances-overview/Components/ExpensesChart/ExpensesChart.stories.tsx
- src/stories/containers/finances-overview/Components/ExpensesChart/ExpensesChart.tsx
- src/stories/containers/finances-overview/Components/ExpensesChart/LegendItem.tsx
- src/stories/containers/finances-overview/finances-overview.tsx
- src/stories/containers/finances-overview/useFinancesOverview.ts
Correct size dot and some style
> [SES-225] Correct size dot and add chart stories

- src/core/business-logic/builders/activity.builder.ts
- src/core/business-logic/builders/core-units.builder.ts
- src/core/utils/storybook/loaders.ts
- src/core/utils/storybook/mocks/coreUnitsMocks.ts
- src/stories/components/core-unit-summary/core-unit-summary.stories.tsx
- src/stories/components/footer/footer.tsx
- src/stories/containers/cu-activity/cu-activity.stories.tsx
- src/stories/containers/cu-activity/cu-activity.tsx
- src/stories/containers/global-activity/global-activity.stories.tsx
- src/stories/containers/global-activity/global-activity.tsx
https://trello.com/c/211SLIYi/244-pending-storybooks-of-r6
Added stories for the Global and Core Unit Activity feed pages
> [SES-244] Added Activity Feed pages stories

- src/config/routes.ts
- src/stories/components/header/header.tsx
No ticket
Fixed Profile links due to it was displaying a "no permissions" message when regular users tried to go to their profile.
> [SES-NO_TICKET] Fix profile link

- src/stories/containers/transparency-report/transparency-transfer-request/transparency-transfer-request-2.mvvm.ts
> [SES-No-ticket] :Correct-total

- src/stories/containers/finances-overview/useFinancesOverview.ts
#Description
#Actions
Fix-bugs-in-chart-finances
> [SES-no-ticked] Fix-bugs-in-chart-finances

- pages/_app.tsx
- src/stories/components/footer/footer.tsx
- src/stories/components/text-input/text-input.tsx
- src/stories/containers/auth/login/login.stories.tsx
- src/stories/containers/auth/login/login.tsx
https://trello.com/c/YzBgSTpH/234-feature-useraccounts-v2
Added "Request Access" section in the login page and added the footer to the login and auth related pages
> [SES-234] Added Request Access to the login page

- src/stories/components/custom-bar-chart/custom-bar-chart.tsx
> [SES-no-ticket] Change-color-dark-mode

- src/stories/containers/finances-overview/Components/ExpensesChart/ExpensesChart.tsx
- src/stories/containers/finances-overview/finances-overview.stories.tsx
- src/stories/containers/finances-overview/finances-overview.tsx
- src/stories/containers/finances-overview/useFinancesOverview.ts
236-feature-delegatestransparencyreporting-v1
Add button in finances page and update storybook
> [SES-236-]Add button in finances page and update storybook

- src/stories/components/delegate-summary/delegate-summary.tsx
- src/stories/containers/recognized-delegates/recognized-delegates.stories.tsx
- src/stories/containers/recognized-delegates/recognized-delegates.tsx
Add delegate page to storybook
> [SES-236] Add delegate page to storybook

- src/core/utils/storybook/decorators.tsx
- src/stories/components/header/header.stories.tsx
- src/stories/components/header/header.tsx
- src/stories/components/top-bar-select/top-bar-select.tsx
https://trello.com/c/YzBgSTpH/234-feature-useraccounts-v2
Improve the header stories
> [SES-234] Improve Header stories

- src/stories/components/top-bar-select/top-bar-select.tsx
Fix the scroll when the pages are being navigated using the top-bar-select component
> [SES-QC-243] Fix body overflow when route changes using the bar-select component

- src/stories/components/custom-table/head-custom-table/head-custom-table-2.tsx
- src/stories/components/custom-table/row-item/item-core-unit.tsx
> [SES-no ticket] Fix align in cu-table

- public/google83d547242713d30e.html
No ticket
Added google site verification file on the root
> [SES-NO_TICKET] Added google site verification file

- pages/_document.tsx
- src/stories/components/top-bar-select/top-bar-select.tsx
- src/stories/containers/cu-table/cu-table-2.mvvm.ts
- styles/globals.scss
https://trello.com/c/HoJdcpkZ/242-qa-bug-findings-v-70
Fix the bounce scroll on apple devices
> [SES-QA-242] Fix bounce scroll

- src/stories/components/delegate-summary/delegate-summary.stories.tsx
- src/stories/components/delegate-summary/delegate-summary.tsx
- src/stories/containers/recognized-delegates/recognized-delegates.stories.tsx
- src/stories/containers/recognized-delegates/recognized-delegates.tsx
236-feature-delegatestransparencyreporting-v1
Add missing break-points in summary-delegate and breadcrumb
> [SES-236] Add missing break-points in summary-delegate and breadcrumb

- jest.config.js
- src/core/context/MainWrapper.tsx
- src/core/hooks/scroll-hooks.ts
- src/core/utils/dom.ts
- src/stories/components/custom-popover/custom-popover.tsx
- src/stories/components/top-bar-select/top-bar-select.tsx
- src/stories/containers/cu-table/cu-table-2.mvvm.ts
- src/stories/containers/cu-table/cu-table.tsx
- styles/globals.scss
https://trello.com/c/HoJdcpkZ/242-qa-bug-findings-v-70
Fix scroll behind navbar
> [SES-QA-242] Fix scroll behind navbar

- src/stories/containers/auth/login/login-modal/login-modal.tsx
- src/stories/containers/auth/login/login.mvvm.ts
https://trello.com/c/YzBgSTpH/234-feature-useraccounts-v2
The login page should not be shown on mobile devices, in that case, the login modal is the one that should be shown.
> [SES-234] Use login modal instead of page on mobile devices

- pages/_document.tsx
- src/core/utils/dom.ts
- styles/globals.scss
No ticket
Rollback the solution of the bounce scroll issue due to this introduced more issues on fixed position elements
> Rollback bounce scroll solution

- src/stories/containers/recognized-delegates/recognized-delegates.tsx
> Additional notes to the page

- src/stories/components/custom-pager/custom-pager.tsx
- src/stories/containers/recognized-delegates/recognized-delegates.tsx
- src/stories/containers/recognized-delegates/useRecognizedDelegates.mvvm.ts
#Description
#Action
Add page navigation month and last update
> [SES-236]Add page navigation month and last update

- src/stories/containers/recognized-delegates/delegates-actuals/delegates-actuals.tsx
- src/stories/containers/recognized-delegates/delegates-forecast/delegates-forecast.tsx
- src/stories/containers/recognized-delegates/recognized-delegates.tsx
- src/stories/containers/recognized-delegates/useRecognizedDelegates.mvvm.ts
> [SES-236] Added comments tab

- src/stories/components/cu-table-column-last-modified/cu-table-column-last-modified.stories.tsx
- src/stories/components/custom-table/custom-table.stories.tsx
- src/stories/components/custom-table/list-core-unit/list-core-unit.stories.tsx
No ticket
Set mocked date to CU table stories to prevent detecting changes by chromatic due date changes
> [NO TICKET] Fix CU table sotries date

- src/core/hooks/useBudgetStatementComments.ts
- src/stories/containers/recognized-delegates/recognized-delegates.tsx
- src/stories/containers/recognized-delegates/useRecognizedDelegates.mvvm.tsx
- src/stories/containers/transparency-report/transparency-auditor-comments/auditor-comment-card.tsx
- src/stories/containers/transparency-report/transparency-auditor-comments/comment-container/auditor-comments-container.tsx
- src/stories/containers/transparency-report/transparency-auditor-comments/comment-container/useCommentsContainer.ts
- src/stories/containers/transparency-report/transparency-auditor-comments/comment-form/comment-form.tsx
- src/stories/containers/transparency-report/transparency-auditor-comments/comment-list.tsx
- src/stories/containers/transparency-report/transparency-auditor-comments/no-comments.tsx
- src/stories/containers/transparency-report/transparency-auditor-comments/participant-roles.tsx
- src/stories/containers/transparency-report/transparency-report.mvvm.tsx
Add comments tab content on the delegates page.
> [SES-236] Add comments tab in delegates page

- src/stories/containers/auth/login/login.tsx
https://trello.com/c/YzBgSTpH/234-feature-useraccounts-v2
Add SEO metadata to the login page
> [SES-234] Add login SEO

- src/stories/containers/recognized-delegates/recognized-delegates.tsx
Add delegates page SEO metadata
> [SES-236] Add delegates SEO

- pages/recognized-delegates/finances/reports/index.tsx
- src/core/hooks/useBudgetStatementComments.ts
- src/stories/containers/recognized-delegates/recognized-delegates.tsx
- src/stories/containers/recognized-delegates/useRecognizedDelegates.mvvm.tsx
- src/stories/containers/transparency-report/transparency-auditor-comments/auditor-comment-card.tsx
- src/stories/containers/transparency-report/transparency-auditor-comments/comment-container/auditor-comments-container.tsx
- src/stories/containers/transparency-report/transparency-auditor-comments/comment-container/useCommentsContainer.ts
- src/stories/containers/transparency-report/transparency-auditor-comments/comment-form/comment-form.tsx
- src/stories/containers/transparency-report/transparency-auditor-comments/comment-list.tsx
- src/stories/containers/transparency-report/transparency-auditor-comments/no-comments.tsx
- src/stories/containers/transparency-report/transparency-auditor-comments/participant-roles.tsx
- src/stories/containers/transparency-report/transparency-report.mvvm.tsx
Allow to post new comments/change status of the budget statements on the Delegates page
> [SES-236] Feature/allow comment on delegates

- src/stories/containers/recognized-delegates/useRecognizedDelegates.mvvm.tsx
Show BudgetStatusIndicator CTA when the user is logged in
> [SES-236] Add BudgetStatusIndicator CTA

- src/stories/containers/recognized-delegates/recognized-delegates.tsx
Add a background to the Delegates page
> [SES-] Add delegates page background

- src/stories/containers/auth/login/login-form/login-form.tsx
https://trello.com/c/HoJdcpkZ/242-qa-bug-findings-v-70
Replaced the Discord link on "Request access" on the login page
> [SES-QA-242] Changed discord link

- src/stories/containers/transparency-report/transparency-forecast/transparency-forecast-2.tsx
Added more spacing in the Forecast tab
> [SES-QC-243] Add correct spacing

- src/stories/containers/recognized-delegates/delegates-actuals/delegates-actuals.tsx
- src/stories/containers/recognized-delegates/delegates-actuals/useDelegatesActuals.mvvm.ts
- src/stories/containers/recognized-delegates/delegates-forecast/delegates-forecast.tsx
- src/stories/containers/transparency-report/placeholders/transparency-empty-table.tsx
> remove tabs form actuals and forecast

- src/stories/components/breadcrumbs/customize-breadcrumbs/custom-breadcrums.tsx
- src/stories/components/delegate-summary/delegate-summary.tsx
- src/stories/components/tabs/tabs.tsx
- src/stories/containers/recognized-delegates/recognized-delegates.stories.tsx
- src/stories/containers/recognized-delegates/recognized-delegates.tsx
Fixed Delegates Summary layout and page container layout
> [SES-236] Fix Delegates Summary layout

- src/core/auth/delegates-extension.ts
- src/core/auth/permission-manager.ts
- src/core/enums/role.enum.ts
- src/stories/containers/transparency-report/transparency-auditor-comments/auditor-comment-card.tsx
- src/stories/containers/transparency-report/transparency-auditor-comments/comment-container/auditor-comments-container.tsx
- src/stories/containers/transparency-report/transparency-auditor-comments/comment-container/useCommentsContainer.ts
- src/stories/containers/transparency-report/transparency-auditor-comments/comment-form/comment-form.tsx
- src/stories/containers/transparency-report/transparency-auditor-comments/participant-roles.tsx
Delegates admin are the only ones that can add new comments. Fixed comments copies
> [SES-236] Improve commenting feature

- src/stories/containers/finances-overview/finances-overview.tsx
Changed the finances page title
> [SES-236] Changed Finances title

- src/stories/containers/recognized-delegates/delegates-actuals/delegates-actuals.tsx
#What solved
**(1)** Should fix text in the links delegate page (375)
Aling the text onchain transactions actual tab
> Aling the text onchain transactions actual tab

- src/core/utils/dictionary.js
- src/stories/components/advanced-inner-table/advanced-inner-table.tsx
- src/stories/components/custom-link/custom-link.tsx
- src/stories/components/number-cell/number-cell.tsx
- src/stories/components/text-cell/text-cell.tsx
- src/stories/components/transparency-card/transparency-card.tsx
- src/stories/components/wallet-table-cell/wallet-table-cell.tsx
#What solved
Should update all the fonts in the Delegate table  👍 
Add size fonts in text and number cell
> [SES-236] Add size fonts in text and number cell

- feature-flags/feature-flags.staging.ts
Enables the Recognized delegates feature on the Staging environment
> [NO TICKET] Enable delegates feature on Staging

- src/stories/components/cu-table-column-last-modified/cu-table-column-last-modified.tsx
- src/stories/components/cu-table-column-team-member/cu-table-column-team-member.tsx
- src/stories/containers/cu-table/cu-table-2.mvvm.ts
- src/stories/containers/cu-table/cu-table.renders.tsx
#Descriptions
https://trello.com/1/cards/63dbc95c19102cb39f3e5692/attachments/63f898bf1ce957db560ff7d0/download/image.png
Fix-align-core-unit-table
> [SES-243]Fix-align-core-unit-table

- src/stories/containers/recognized-delegates/delegates-actuals/delegates-actuals.tsx
- src/stories/containers/recognized-delegates/delegates-forecast/delegates-forecast.tsx
#Descriptions
Fix margin delegate
> [No ticket] Fix margin delegate

- src/stories/containers/auth/login/login.mvvm.ts
> [SES-QC-243] Fix login

- src/stories/components/card-navegation/card-expenses.tsx
Fix Core Units expenses card layout when it has several auditors
> [SES-QC-243] Fix CU expenses Card layout

- src/stories/components/core-unit-card/core-unit-card.tsx
- src/stories/components/cu-table-column-expenditures/cu-table-column-expenditures.tsx
- src/stories/components/cu-table-column-last-modified/cu-table-column-last-modified.tsx
- src/stories/components/cu-table-column-team-member/cu-table-column-team-member.tsx
#What solved
The data is not aligned with the header column
https://trello.com/1/cards/63dbc95c19102cb39f3e5692/attachments/63f898bf1ce957db560ff7d0/download/image.png
Add align to cu-table
> [No- ticket] Add align to cu-table

- src/stories/components/delegate-summary/delegate-summary.tsx
No Ticket
Fixed social links alignment in the Delegates summary
> Fix delegates social icons

- src/stories/containers/recognized-delegates/delegates-forecast/useDelegatesForeCast.mvvm.ts
#What solved
Text under forecast should be change 
Change text
> [No ticket] Change text under forecast tab in delegate page

- pages/_app.tsx
- src/core/utils/dictionary.js
- When pulling the page down on mobile in dark mode, a white area appears. [image.png](https://trello.com/1/cards/63c573b095f58802270f7e2b/attachments/63da3cfa7029e31482f41b1c/download/image.png)
Solve ios bounce issue using javascript
> [SES-QA-256] Fix ios scroll bouncing using js

- pages/_app.tsx
- src/core/utils/dictionary.js
trying to fix the Apple devices scroll bounce
> [SES-QA-256] Trying to fix Apple scroll bounce

- src/stories/containers/cu-table/useCoreUnitsTable.ts
#What solved
Should allow sorting the Last Modified column through the sort icons 
Add bigger with to the last modified column
> Add bigger with to the last modified column

- src/stories/components/TransparencyCard/TransparencyCard.tsx
- src/stories/components/svg/information.tsx
- src/stories/containers/TransparencyReport/transparencyReportUtils.tsx
#What solved
New Icon to show tooltip and add new style Target
Add new style for Target Balance
> Add new style for Target Balance

- feature-flags/feature-flags.development.ts
- feature-flags/feature-flags.interface.ts
- feature-flags/feature-flags.production.ts
- feature-flags/feature-flags.staging.ts
- src/stories/containers/TransparencyReport/components/TransparencyTransferRequest/TransparencyTransferRequest.tsx
#What solved
Add feature flag for comments
Show subtitle in the page
Add feature flags for comments and Add tittle in the page
> [No-ticket] Add feature flags for comments and Add tittle in the page

- package.json
- src/stories/containers/TransparencyReport/components/TransparencyForecast/useTransparencyForecast.ts
- src/stories/containers/TransparencyReport/components/TransparencyTransferRequest/components/ModalSheet/ModalSheetValueContent.tsx
- src/stories/containers/TransparencyReport/transparencyReportUtils.tsx
- yarn.lock
#What solved
Should create the `OverlayedTooltip` for actual mobile devices 
Show mobile modal-sheet when is real device
Show mobile modalsheet when is real device
> Show mobile modal-sheet when is real device

- src/stories/containers/FinancesOverview/FinancesOverviewContainer.stories.tsx
- src/stories/containers/FinancesOverview/FinancesOverviewContainer.tsx
- src/stories/containers/FinancesOverview/components/CostBreakdownFilter/CostBreakdownFilter.tsx
- src/stories/containers/FinancesOverview/components/CostBreakdownTable/ByBudgetTableHeader.tsx
- src/stories/containers/FinancesOverview/components/CostBreakdownTable/ByBudgetTableRow.tsx
- src/stories/containers/FinancesOverview/components/CostBreakdownTable/ByExpenseCategoryTableHeader.tsx
- src/stories/containers/FinancesOverview/components/CostBreakdownTable/ByExpenseCategoryTableRow.tsx
- src/stories/containers/FinancesOverview/components/CostBreakdownTable/CostBreakdownTable.tsx
- src/stories/containers/FinancesOverview/components/CostBreakdownTable/ExpenseCategoryGroup.tsx
- src/stories/containers/FinancesOverview/components/CostBreakdownTable/TableFooter.tsx
- src/stories/containers/FinancesOverview/components/CostBreakdownTable/TableHeaderItem.tsx
- src/stories/containers/FinancesOverview/components/ExpensesChart/ExpensesChart.tsx
- src/stories/containers/FinancesOverview/components/NavigationButtons/NavigationButtons.tsx
- src/stories/containers/FinancesOverview/components/RelativeBudgetBar/RelativeBudgetBar.tsx
- src/stories/containers/FinancesOverview/components/YearPicker/YearPicker.tsx
- src/stories/containers/FinancesOverview/useFinancesOverview.ts
- src/stories/containers/FinancesOverview/utils/tableColumnSizes.ts
https://trello.com/c/tqmW07KT/246-feature-delegatestransparencyreporting-v2
- Should add the Cost Breakdown Section having in count the responsiveness of the section and the Expenses Chart  Section
- Should Add the Cost Breakdown Table item (mobile)
- Should update the Finances page story
- Should Add the Cost Breakdown Table Header (dark mode) 
- Should Add the Cost Breakdown Table item (dark mode)
- Should Add the Cost Breakdown Table Total (dark mode)
> [SES-246] Cost breakdown responsiveness

- src/stories/containers/TransparencyReport/components/TransparencyAuditorComments/ParticipantRoles.tsx
- src/stories/containers/TransparencyReport/components/TransparencyMkrVesting/useTransparencyMkrVesting.ts
- src/stories/containers/TransparencyReport/transparencyReportUtils.tsx
#What solved
Rephrase: “Recognize Delegate is currently working without an auditor”
Change the UI so that the data for MKR Vesting is in chronological order
Fix align tooltip and QA-bugs
> Fix align tooltip and QA-bugs

- pages/auth/change-password/index.tsx
- pages/auth/delete-account/index.tsx
- pages/core-units.tsx
- src/stories/containers/AppLayout/AppLayout.tsx
- src/stories/containers/Auth/Login/LoginContainer.tsx
- src/stories/containers/CUAbout/CuAboutContainer.tsx
- src/stories/containers/CUActivity/CUActivityFeedContainer.tsx
- src/stories/containers/CUTable/CuTable.tsx
- src/stories/containers/FinancesOverview/FinancesOverviewContainer.tsx
- src/stories/containers/GlobalActivity/GlobalActivityFeedContainer.tsx
- src/stories/containers/RecognizedDelegates/RecognizedDelegatesContainer.tsx
- src/stories/containers/TransparencyReport/TransparencyReport.tsx
- src/stories/containers/Users/UserProfile/UserProfileContainer.tsx
- src/stories/containers/Users/UsersManager/UserManagerLayout.tsx
Fix white space on apple devices when scrolling down in dark mode (scroll bouncing)
> [SES-QA-256] Fix apple white space when scroll down

- src/stories/components/CoreUnitSummary/CoreUnitSummary.stories.tsx
- src/stories/containers/Auth/Login/LoginContainer.stories.tsx
- src/stories/containers/Auth/Login/LoginModal/LoginModal.stories.tsx
- src/stories/containers/CUActivity/CUActivityFeedContainer.stories.tsx
- src/stories/containers/FinancesOverview/FinancesOverviewContainer.stories.tsx
- src/stories/containers/FinancesOverview/components/YearPicker/YearPicker.stories.tsx
- src/stories/containers/GlobalActivity/GlobalActivityFeedContainer.stories.tsx
#What solved
Should be added chromatic as a parameter in the stories settings. 
Add chromatic as parameters in the stories
> Add chromatic as paramters in the stories

- src/stories/components/CookiesPolicyBanner/CookiesPolicyBanner.tsx
- src/stories/components/TopBarSelect/TopBarSelect.tsx
Should have the proper space between the "Reject all cookies" and "Accept configures cookies" buttons. 
Should have the proper space between the menu 
Fix-gap-iPad-devices
> Fix-gap-Ipad-devices

- src/stories/containers/TransparencyReport/components/TransparencyActuals/useTransparencyActuals.ts
- The Core Units > SES (or any other CU) > Expense Reports; change BUDGET CATEGORY into EXPENSE CATEGORY.
> [SES-QC-254] Changed breakdown column name

- src/stories/components/TransparencyCard/TransparencyCard.tsx
- src/stories/containers/TransparencyReport/components/ArrowPopoverTargetValue/ArrowPopoverTargetValueComponent.stories.tsx
- src/stories/containers/TransparencyReport/components/ArrowPopoverTargetValue/ArrowPopoverTargetValueComponent.tsx
- src/stories/containers/TransparencyReport/components/ArrowPopoverTargetValue/ArrowPopoverTargetValueContent.tsx
- src/stories/containers/TransparencyReport/transparencyReportUtils.tsx
https://trello.com/c/tixH6IkI/245-feature-onchaindatareconciliation-v1
#What solved
Should be aligned the info icon and the value with the Target Balance text. 
Fix align card target balance column
> Fix align card target balance column

- src/stories/components/Header/EssentialWebsites/ItemWebSite/ItemWebSite.tsx
- src/stories/components/MenuNavigation/SwitcherButton.tsx
#What solved
1-Should allow switching modes by clicking on the hover area. 
1-Should display properly the hover on the Visit Website button in the Voting Portal and MIPs Portal websites (Expenses component). 
Add correct height
> [SES-254] Fix issues qc round

- src/core/businessLogic/coreUnits.ts
- src/core/utils/filters.ts
- src/stories/components/CoreUnitCard/CoreUnitCard.tsx
- src/stories/components/TitleNavigationCuAbout/TitleNavigationCuAbout.tsx
- src/stories/containers/CUTable/CuTableRenders.tsx
- src/stories/containers/CUTable/useCoreUnitsTable.ts
Fixed existing typos in the code
- Fix typo in a code function
> [SES-QC-254] Fix identifier typo

- src/stories/components/Container/Container.tsx
- src/stories/components/Container/PageContainer.tsx
- src/stories/containers/FinancesOverview/FinancesOverviewContainer.stories.tsx
- src/stories/containers/FinancesOverview/FinancesOverviewContainer.tsx
- src/stories/containers/GlobalActivity/GlobalActivityFeedContainer.tsx
Created a reusable Container to be used in every page
- Create a reusable container for the existing pages a the new ones in the future
> [SES-QC-254] Create a reusable container

- src/stories/components/CustomPopover/CustomPopover.tsx
#What solved
Clear time in mouse in a popover
> Clear time in mose in popover

- src/stories/components/CustomPopover/CustomPopover.tsx
- src/stories/containers/TransparencyReport/transparencyReportUtils.tsx
#What solved
Add a variable that shows up or down popover
> Add variable that show up or down popover

- src/stories/containers/RecognizedDelegates/RecognizedDelegatesContainer.tsx
- src/stories/containers/RecognizedDelegates/useRecognizedDelegates.tsx
Upgrade the tabs on the Delegates page to allow to open tabs in a new browser tab. Also optimized the code in the MVVM hook of the delegates page with the workflow for the current `Tabs` component
- Should allow opening in a new browser tab when the user right click on the tabs on the Recognize delegates page
> [SES-257] Upgrade delegate's tabs

- src/stories/containers/TransparencyReport/components/BudgetReport/BudgetReport.tsx
- src/stories/containers/TransparencyReport/components/TransparencyMkrVesting/MkrVestingInfo.tsx
- src/stories/containers/TransparencyReport/components/TransparencyMkrVesting/MkrVestingTotalFTE.tsx
- src/stories/containers/TransparencyReport/components/TransparencyMkrVesting/TransparencyMkrVesting.tsx
- src/stories/containers/TransparencyReport/components/TransparencyMkrVesting/useTransparencyMkrVesting.ts
Added the Forecast section to the Budget Report tab.
- Should add the "MKR Vesting Overview" section in the new "Budget Report" tab
> [SES-257] Add "MKR Vesting" to the "Budget Report" tab

- src/stories/components/CUActivityTable/ActivityTable.stories.tsx
- src/stories/components/CUActivityTable/CUActivityItem.stories.tsx
- src/stories/components/CUActivityTable/CUActivityItem.tsx
- src/stories/containers/GlobalActivity/useGlobalActivity.ts
Fixed breaking changes in the API to allow to have delegates' activities. Update the table header too
- Global activity feed client side error
> [SES-QC-265] Fix global activity feed issue

- .github/workflows/dev-deploy.yaml
Fix Github action for dev stage deployment.
The error was due this issue on appleboy/scp-action: https://github.com/appleboy/scp-action/issues/113
> [SES-QC] Update appleboy/scp-action

- .github/workflows/production-deploy.yaml
- .github/workflows/staging-deploy.yaml
- .github/workflows/storybook-next-deploy.yaml
Fixed all the actions broken due an `appleboy/scp-action` update. The issue was originated here: https://github.com/appleboy/scp-action/issues/113
> [SES-QC-265] Fix github actions

- src/stories/containers/RecognizedDelegates/components/DelegateChart.stories.tsx
- src/stories/containers/RecognizedDelegates/components/DelegateChart.tsx
> [SES-258]Fix-problem-chart-834-view

- src/stories/components/TransparencyCard/TransparencyCard.tsx
- src/stories/containers/TransparencyReport/TransparencyReport.tsx
- src/stories/containers/TransparencyReport/components/ExpenseReport/ExpenseReport.tsx
- src/stories/containers/TransparencyReport/components/ExpenseReport/components/ExpenseSection/ExpenseSection.tsx
- src/stories/containers/TransparencyReport/components/ExpenseReport/components/SectionTitle/SectionTitle.stories.tsx
- src/stories/containers/TransparencyReport/components/ExpenseReport/components/SectionTitle/SectionTitle.tsx
- src/stories/containers/TransparencyReport/components/ExpenseReport/useExpenseReport.tsx
- src/stories/containers/TransparencyReport/components/TransparencyActuals/TransparencyActuals.tsx
- src/stories/containers/TransparencyReport/components/TransparencyMkrVesting/MkrVestingTotalFTE.tsx
Implemented the responsiveness in the auditor view
- Should the Budget section be responsive according to the design styles
> [SES-257] Expenses budget (Auditor view) responsive

- src/stories/containers/RecognizedDelegates/RecognizedDelegatesContainer.tsx
- src/stories/containers/RecognizedDelegates/components/DelegateExpenseBreakdownCard.tsx
Show the correct size icon breakdown card
Add correct with for card breakdown
> Add correct with for card breakdown

- src/stories/components/AdvancedInnerTable/AdvancedInnerTable.tsx
Added a top line in all the totals rows. Remove the font-weight bold from the numbers in the subtotals lines
- Should remove the font weight of the subtotal numbers in the breakdowns sections (actuals and forecast)
> [SES-257] Add totals top line & remove font weight from subtotals

- pages/delegates/index.tsx
- src/core/businessLogic/reconizedDelegate.ts
- src/stories/containers/RecognizedDelegates/RecognizedDelegatesContainer.tsx
- src/stories/containers/RecognizedDelegates/api/RecognizedDelegatesAPI.ts
- src/stories/containers/RecognizedDelegates/useRecognizedDelegates.ts
✅Add correct data for the chart 
✅Reflect the data in the chart when the filter
Add correct values to chart total delegates
> Add correct values to chart totalDelgates

- src/stories/containers/RecognizedDelegates/components/DelegateExpenseBreakdownCard.tsx
- src/stories/containers/RecognizedDelegates/components/MedianAnnualDai.tsx
✅Add the correct color and the correct line divider
Add correct color and the divider
> Add correct color and the divider

- src/stories/containers/RecognizedDelegates/components/DelegateExpenseBreakdownCard.tsx
No ticket
Make the delegates address go to ether scan
> Fix delegates address

- src/core/utils/typesHelpers.ts
- src/stories/components/CustomMultiSelect/CustomMultiSelect.tsx
- src/stories/components/TokenIcon/TokenIcon.tsx
- src/stories/components/svg/DAIIcon.tsx
- src/stories/components/svg/ETHIcon.tsx
- src/stories/components/svg/MKRIcon.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/CurrencyPicker/CurrencyItem.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/CurrencyPicker/CurrencyPicker.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/FundingOverview/FundingOverview.tsx
Add a showcase for the currencies in the MakerDAO Funding Overview section
- Should showcase the currency being is being used (without the ability to select further currencies)
> [SES-268] Add select currency showcase

- src/stories/containers/TransparencyReport/components/HeaderWithIcon/HeaderWithIcon.tsx
- src/stories/containers/TransparencyReport/components/TransparencyForecast/BarWithDottedLine.tsx
- src/stories/containers/TransparencyReport/components/TransparencyForecast/ProgresiveIndicator.tsx
- src/stories/containers/TransparencyReport/utils/budgetStatementsUtils.ts
- src/stories/containers/TransparencyReport/utils/forecastHelper.ts
✅Fix correct position dotted bars
✅Add the correct name for the month tooltip
Add correct name tooltip and logic doted bar
> Add correct name tooltip and logic doted bar

- src/stories/containers/TransparencyReport/components/HeaderWithIcon/HeaderWithIcon.tsx
✅Show the tooltip for real device
Add a tooltip for real-device mobile
> Add tooltip for real device mobile

- pages/testing.tsx
- src/stories/components/AdvanceTable/AdvanceTable.stories.tsx
- src/stories/components/AdvanceTable/AdvanceTable.tsx
- src/stories/components/AdvanceTable/BuiltIn/Cells/BasicCell.tsx
- src/stories/components/AdvanceTable/BuiltIn/Cells/BasicTHCell.tsx
- src/stories/components/AdvanceTable/BuiltIn/Cells/BoldTextCell.tsx
- src/stories/components/AdvanceTable/BuiltIn/Cells/DefaultCell.tsx
- src/stories/components/AdvanceTable/BuiltIn/Cells/NumberCell.tsx
- src/stories/components/AdvanceTable/BuiltIn/Cells/TextCell.tsx
- src/stories/components/AdvanceTable/BuiltIn/DefaultTBody.tsx
- src/stories/components/AdvanceTable/BuiltIn/DefaultTHead.tsx
- src/stories/components/AdvanceTable/BuiltIn/DefaultTR.tsx
- src/stories/components/AdvanceTable/types.ts
- src/stories/components/AdvanceTable/utils.ts
- styles/theme/light.ts
Created a more customizable and extendible table component
- Should create a new Table component
> [SES-268] New Advance table

- src/stories/containers/TransparencyReport/components/HeaderWithIcon/HeaderWithIcon.tsx
✅Delete all console
Delete unnecessary log
> [No Ticket] Delete unnecessary log

- src/stories/containers/TransparencyReport/components/HeaderWithIcon/HeaderWithIcon.tsx
- src/stories/containers/TransparencyReport/components/HeaderWithIcon/TooltipHeader.tsx
- src/stories/containers/TransparencyReport/components/TransparencyTransferRequest/components/ModalSheet/ModalSheetValueContent.tsx
✅Should show correct format in the tooltip icon (Mip Number)
Add correct format
> Add correct format

- src/core/businessLogic/builders/categoriesBuilders.ts
- src/stories/components/BasicModal/BasicModal.stories.tsx
- src/stories/components/BasicModal/CategoryItem/ArrowAccordionCategory.tsx
- src/stories/components/BasicModal/CategoryItem/CategoryItem.tsx
- src/stories/components/BasicModal/ChekBoxDescription/ChekBoxDescription.tsx
- src/stories/components/BasicModal/ContainerModal.tsx
- src/stories/components/CheckBox/CheckBox.tsx
- src/stories/components/svg/check-on-new.tsx
- src/stories/components/svg/checkbox-off.tsx
- src/stories/containers/TransparencyReport/utils/descriptionsConstants.ts
✅ Should have the modal Description title
✅Should  the modal have a close (x) option at the top right
Add property SVG and add Accordion for description 
Add builder and story for modal contained
> Feature/modal container modal UI

- src/stories/containers/FinancesOverview/FinancesOverviewContainer.stories.tsx
- src/stories/containers/FinancesOverview/FinancesOverviewContainer.tsx
- src/stories/containers/FinancesOverview/components/CostBreakdownTable/CostBreakdownTable.tsx
✅Add mobile buttom
This adds functionality to open the modal on mobile, this was missing
> Open modal in mobile

- pages/index.tsx
- src/core/models/dto/expenseCategoriesDTO.ts
- src/stories/containers/FinancesOverview/FinancesOverviewContainer.stories.tsx
- src/stories/containers/FinancesOverview/FinancesOverviewContainer.tsx
- src/stories/containers/FinancesOverview/api/queries.ts
- src/stories/containers/FinancesOverview/useFinancesOverview.ts
Fetch all the categories from the API and parse them to have a better structure to work with
> [SES-276] Fetch all expense categories

- src/stories/components/BasicModal/ContainerModal.tsx
- src/stories/containers/FinancesOverview/FinancesOverviewContainer.tsx
✅ The space displayed between the last category and the bottom of the modal is wrong
✅ The border-radius at the bottom should have 16 px as the rest of the borders
✅ Scrolling down until at the end, the header disappears.
Fix some issues relate with fix the header modal and border of the modal when scrolling
> Add correct place scroll and marginBottom

- src/stories/components/BasicModal/ContainerModal.tsx
✅Fix issues during the team call
Fix the borders in mobile, and add 100% mobile
> Fix border in mobile

- src/stories/components/BasicModal/CategoryItem/ArrowAccordionCategory.tsx
- src/stories/components/BasicModal/CategoryItem/CategoryItem.tsx
- src/stories/components/BasicModal/ContainerModal.tsx
Make modal adaptin when the browser resize
> [SES-No ticket] Make responsive adjust correct modal

- src/stories/components/BasicModal/CategoryItem/ArrowAccordionCategory.tsx
> [Not Ticket] Fix orientation of arrow

- src/stories/components/AdvancedInnerTable/AdvancedInnerTable.tsx
- src/stories/containers/TransparencyReport/components/TransparencyActuals/useTransparencyActuals.ts
- src/stories/containers/TransparencyReport/transparencyReportUtils.tsx
- src/stories/containers/TransparencyReport/utils/actualsTableHelpers.tsx
- src/stories/containers/TransparencyReport/utils/forecastTableHelpers.tsx
✅Should the link open the modal with the correct data
✅Should check the responsive table with the new icon
Add the icon to the card for each category
> Add icon in the card

- src/stories/components/BasicModal/ContainerModal.tsx
✅Scrolling down until the end, the scroll bar should be visible at the end 
This is for fixing the scroll until the bottom in the modal view
> Add correct height to the bar

- src/stories/components/CategoryChip/CategoryChip.tsx
✅The view should be properly loaded.
> [No ticket-278] Add mark in case the value do not exist

- src/core/enums/cuCategoryEnum.ts
- src/stories/components/CategoryChip/CategoryChip.tsx
✅The view displays an error.
Add default color when a new category is added
Fix the problem in Activity Global
> [No-ticket-278] Add default values in case new category is add

- feature-flags/feature-flags.development.ts
- feature-flags/feature-flags.interface.ts
- feature-flags/feature-flags.production.ts
- feature-flags/feature-flags.staging.ts
- pages/ecosystem-actors/index.tsx
- src/config/routes.ts
- src/core/models/dto/teamsDTO.ts
- src/stories/components/Header/Header.tsx
- src/stories/components/Header/menuItems.ts
- src/stories/containers/Actors/ActorsContainer.tsx
✅Add should scaffold for the new page
This should add a link to the header and should show all the parts of the page
> Add scalfod and link header

- package.json
- src/core/utils/dictionary.js
- src/stories/components/CustomTooltip/CustomTooltip.stories.tsx
- src/stories/components/CustomTooltip/CustomTooltip.tsx
- yarn.lock
Create a custom component to serve as common popover component with some of the required features
> [SES-268] Custom popper

- src/stories/components/BasicModal/CategoryItem/CategoryItem.tsx
- src/stories/containers/TransparencyReport/TransparencyReport.tsx
- src/stories/containers/TransparencyReport/components/ExpenseReport/ExpenseReport.tsx
- src/stories/containers/TransparencyReport/components/ExpenseReport/useExpenseReport.tsx
- src/stories/containers/TransparencyReport/components/TransparencyForecast/TransparencyForecast.tsx
- src/stories/containers/TransparencyReport/components/TransparencyForecast/useTransparencyForecast.tsx
- src/stories/containers/TransparencyReport/utils/forecastTableHelpers.tsx
✅Should remove the icon displayed in the Forecast tab, next to the Budget Category.
This is to delete the icon that appears Forecast tab
> [No-ticket-278]Delete-icon-budget-cap

- src/core/businessLogic/builders/accountSnapshot/accountSnapshotBuilder.ts
- src/core/businessLogic/builders/accountSnapshot/snapshotAccountBalanceBuilder.ts
- src/core/businessLogic/builders/accountSnapshot/snapshotAccountTransactionBuilder.ts
- src/core/models/dto/snapshotAccountDTO.ts
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/api/queries.ts
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/FundingOverview/FundingOverview.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Transaction/TransactionWalletInfo.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/TransactionList/TransactionList.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/WalletInfo/WalletInfo.tsx
Update the UI code to integrate with the new changes in the API
> [SES-268] Adjust the UI to new API changes

- src/stories/components/CustomTooltip/CustomTooltip.stories.tsx
- src/stories/components/CustomTooltip/CustomTooltip.tsx
Add stories for Custom tooltip usecases related with interactiveness and arrow placement
> [SES-268] Covering tooltip interactivity and arrow display

- pages/index.tsx
- src/core/context/CategoryModalContext.tsx
- src/stories/components/BasicModal/CategoryModalComponent.tsx
- src/stories/components/BasicModal/useModalCategory.ts
- src/stories/containers/FinancesOverview/FinancesOverviewContainer.tsx
- src/stories/containers/FinancesOverview/useFinancesOverview.ts
- src/stories/containers/TransparencyReport/TransparencyReport.tsx
- src/stories/containers/TransparencyReport/components/ExpenseReport/ExpenseReport.tsx
- src/stories/containers/TransparencyReport/components/ExpenseReport/useExpenseReport.tsx
- src/stories/containers/TransparencyReport/components/TransparencyActuals/TransparencyActuals.tsx
- src/stories/containers/TransparencyReport/components/TransparencyActuals/useTransparencyActuals.ts
This adds context to the modal of categories
> Add context for the modal categories

- src/stories/components/Header/Header.stories.tsx
- src/stories/components/Header/Header.tsx
- src/stories/containers/Actors/ActorsContainer.stories.tsx
- src/stories/containers/Actors/ActorsContainer.tsx
- src/stories/containers/Actors/useActors.ts
[X]-Should the subheader explain what ecosystem actors are
This adds the text description about the actors also fix some problems in the header
> Add need change in the header and add title and subtitle

- src/stories/containers/Actors/ActorsContainer.stories.tsx
- src/stories/containers/Actors/ActorsContainer.tsx
- src/stories/containers/Actors/components/ActorFilters/ActorFilters.tsx
- src/stories/containers/Actors/useActors.ts
This is for add the filter to the page
> Add the filter for actors view

- src/core/businessLogic/builders/actors/actorsBuilder.ts
- src/core/enums/actorScopeEnum.ts
- src/core/models/dto/teamsDTO.ts
- src/core/utils/colors.ts
- src/stories/components/CuTableColumnLinks/CuTableColumnLinks.tsx
- src/stories/containers/Actors/components/ActorItem/ActorItem.stories.tsx
- src/stories/containers/Actors/components/ActorItem/ActorItem.tsx
- src/stories/containers/Actors/components/ScopeChip/ScopeChip.tsx
- src/stories/containers/Actors/utils/utils.ts
> Add builder and item for actor list

- src/stories/components/CustomTooltip/CustomTooltip.stories.tsx
- src/stories/components/CustomTooltip/CustomTooltip.tsx
Adding styles and dark/light mode to tooltips according to the design
> [SES-268]Feat/custom tooltip styles

- package.json
- src/stories/components/CustomTooltip/CustomTooltip.stories.tsx
- src/stories/components/CustomTooltip/CustomTooltip.tsx
- yarn.lock
Adding fallbackPlacement property to support custom placement overflow fallback
> [SES-268] Feat/custom tooltip fallback placements

- package.json
- src/stories/components/CustomTooltip/CustomTooltip.stories.tsx
- src/stories/components/CustomTooltip/CustomTooltip.tsx
- yarn.lock
Adding support for styled CustomTooltip with default fallback to the tooltip component
> [SES-268] Custom tooltip customization

- src/core/utils/dictionary.js
- src/stories/containers/Actors/ActorsContainer.stories.tsx
- src/stories/containers/Actors/ActorsContainer.tsx
- src/stories/containers/Actors/components/ActorHeader/ActorsHeaderTable.tsx
- src/stories/containers/Actors/components/ActorItem/ActorItem.tsx
- src/stories/containers/Actors/components/ActorTable/ActorTable.tsx
- src/stories/containers/Actors/useActors.ts
- Should  have  responsive for the page
-  Add SEO to the page
This adds SEO for the page and checks for the responsive of the page
> Add SEO for the page

- src/stories/containers/TransparencyReport/utils/actualsTableHelpers.tsx
https://trello.com/c/FEo923dc/277-qa-bug-finding-r
This fix SAS subtotal doesn't show
> Add condition show values if some are different zero

- src/core/utils/sitemap.ts
This adds the new page to the site map
> Add new page to site map

- src/stories/components/NavigationCard/CardSomethingWrong.stories.tsx
- src/stories/components/NavigationCard/CardSomethingWrong.tsx
This adds stories for the card something was wrong
> Add stories for something wrong card

- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/BaseSkeleton/BaseSkeleton.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Cards/ExpensesComparisonRowCard/ExpensesComparisonRowCardSkeleton.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Cards/FundChangeCardSkeleton.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Cards/ReserveCardMobileSkeleton.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Cards/ReserveCardSkeleton.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Cards/SimpleStatCardSkeleton.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/ExpensesComparison/ComparisonTableSkeleton.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/NumberWithSignCard/NumberWithSignCardSkeleton.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/SVG/Equals.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/TransactionHistory/TransactionHistorySkeleton.tsx
Implemented dark mode in Account Snapshots skeletons
> [SES-268] Added dark mode in the Account Snapshots skeletons

- src/stories/components/NavigationCard/CardExpenses.tsx
- src/stories/containers/Actors/components/ActorItem/ActorItem.tsx
- src/stories/containers/ActorsAbout/ActorMdViewer/ActorMdViewPage.tsx
- src/stories/containers/ActorsAbout/ActorMdViewer/ActorMdViewer.tsx
- src/stories/containers/ActorsAbout/ActorSummary/ActorTitleAbout.tsx
- src/stories/containers/ActorsAbout/ActorSummary/ActorTitleWithDescription.stories.tsx
- src/stories/containers/ActorsAbout/ActorSummary/ActorTitleWithDescription.tsx
Improve the responsive in the header and add markdown
> Improve the responsive in table view

- pages/ecosystem-actors/[code]/index.tsx
- src/core/context/ActorContext.tsx
- src/stories/components/Markdown/renderUtils.tsx
- src/stories/components/NavigationCard/CardSomethingWrong.tsx
- src/stories/components/NavigationCard/InformationCard.tsx
- src/stories/containers/Actors/ActorsContainer.stories.tsx
- src/stories/containers/Actors/components/ActorItem/ActorItem.tsx
- src/stories/containers/Actors/utils/utils.ts
- src/stories/containers/ActorsAbout/ActorAboutContainer.tsx
- src/stories/containers/ActorsAbout/ActorSummary/ActorSummary.tsx
- src/stories/containers/ActorsAbout/ActorSummary/ActorTitleAbout.tsx
- src/stories/containers/ActorsAbout/ActorSummary/ActorTitleWithDescription.tsx
- src/stories/containers/ActorsAbout/ActorsAbout.stories.tsx
- src/stories/containers/ActorsAbout/BreadCrumbNavigation/BreadCrumbNavigation.tsx
- src/stories/containers/ActorsAbout/api/queries.ts
- src/stories/containers/ActorsAbout/useActorAbout.ts
Change the text Core Unit table and adjust the table
Add the link to each month
> Add logic for the render actor page

- pages/ecosystem-actors/[code]/index.tsx
- src/core/context/ActorContext.tsx
- src/stories/components/Markdown/renderUtils.tsx
- src/stories/components/NavigationCard/InformationCard.tsx
- src/stories/containers/Actors/ActorsContainer.stories.tsx
- src/stories/containers/Actors/components/ActorItem/ActorItem.tsx
- src/stories/containers/Actors/utils/utils.ts
- src/stories/containers/ActorsAbout/ActorAboutContainer.tsx
- src/stories/containers/ActorsAbout/ActorSummary/ActorSummary.tsx
- src/stories/containers/ActorsAbout/ActorSummary/ActorTitleAbout.tsx
- src/stories/containers/ActorsAbout/ActorSummary/ActorTitleWithDescription.tsx
- src/stories/containers/ActorsAbout/ActorsAbout.stories.tsx
- src/stories/containers/ActorsAbout/BreadCrumbNavigation/BreadCrumbNavigation.tsx
- src/stories/containers/ActorsAbout/api/queries.ts
- src/stories/containers/ActorsAbout/useActorAbout.ts
This adds a heading for the markdown component
> Feature add heading markdown

- src/core/businessLogic/builders/actors/actorsBuilder.ts
- src/core/models/dto/teamsDTO.ts
- src/stories/containers/Actors/components/ActorItem/ActorItem.tsx
- src/stories/containers/ActorsAbout/ActorAboutContainer.tsx
- src/stories/containers/ActorsAbout/ActorSummary/ActorSummary.tsx
- src/stories/containers/ActorsAbout/ActorSummary/ActorTitleWithDescription.stories.tsx
- src/stories/containers/ActorsAbout/ActorsAbout.stories.tsx
- src/stories/containers/ActorsAbout/BreadCrumbNavigation/BreadCrumbNavigation.tsx
- src/stories/containers/ActorsAbout/api/queries.ts
- src/stories/containers/ActorsTransparencyReport/ActorsTransparencyReportContainer.tsx
[Not-ticket-287]
This fixes the problem of component navigation
This fixed component navigation also add correct page navigation in actor about page
> [Not-ticket-287] Fix problem navigation component

- src/stories/components/Markdown/renderUtils.tsx
- src/stories/containers/ActorsAbout/ActorAboutContainer.tsx
This adds the correct floating right card for the responsive
> Add responsive (sticky card)

- src/stories/containers/Actors/components/ActorItem/ActorItem.tsx
- src/stories/containers/Actors/utils/utils.ts
Fix error in dev for a new actor
> [No-ticket] Add condition for null values

- .vscode/settings.json
- src/core/utils/string.ts
- src/stories/components/NavigationCard/CardExpenses.tsx
- src/stories/containers/ActorsAbout/ActorAboutContainer.tsx
- src/stories/containers/ActorsAbout/ActorMdViewer/ActorMdViewPage.tsx
- src/stories/containers/ActorsAbout/ActorMdViewer/ActorMdViewer.tsx
https://trello.com/c/KT93qSRs/288-user-story-ability-to-view-ecosystem-actor-expense-reports
Utilize the right texts for the expenses card in the ecosystem actors about page
> [SES-288] Fix the CardExpenses texts

- src/stories/containers/ActorsAbout/ActorMdViewer/ActorMdViewPage.tsx
- src/stories/containers/ActorsAbout/ActorSummary/ActorTitleWithDescription.tsx
Fix about layout when the device is less than 375
> [Not-Ticket] Issues/show correct low 375

- src/stories/components/CustomTable/TablePlaceholder.tsx
- src/stories/containers/Actors/ActorsContainer.tsx
- src/stories/containers/Actors/useActors.ts
This fixes the error when there are no filters that match
> Add image and correct text when not filter match

- src/core/models/interfaces/types.ts
- src/stories/components/CategoryChip/CategoryChip.tsx
- src/stories/containers/Actors/components/ActorFilters/ActorFilters.tsx
Add new required in the filter
> Add correct number filters and new colors

- src/stories/containers/Actors/components/ActorItem/ActorItem.tsx
- src/stories/containers/Actors/components/ActorLastModified/ActorLastModified.tsx
Fix issues in the LastModified column
> Fix colors and the hover in table

- src/stories/components/CUActivityTable/ActivityPlaceholder.tsx
- src/stories/components/CUActivityTable/ActivityTablePlaceholder.tsx
- src/stories/components/CUActivityTable/CUActivityItem.tsx
- src/stories/components/CUActivityTable/utils/helpers.ts
- src/stories/containers/GlobalActivity/GlobalActivityFeedContainer.tsx
[SES-not-ticket]
Fix the ActivityFeed for ecosystem actors
> [SES-not-ticket] Add other condition for delegates

- src/stories/components/CoreUnitSummary/CoreUnitSummary.tsx
- src/stories/components/DelegateSummary/DelegateSummary.tsx
- src/stories/containers/ActorsAbout/ActorAboutContainer.tsx
- src/stories/containers/ActorsAbout/ActorSummary/ActorSummary.tsx
- src/stories/containers/CUAbout/CuAboutContainer.tsx
https://trello.com/c/FEo923dc/277-qa-bug-finding-r
This is for hidden all information in the header when the user scroll, to make it easy to read the rest of the page
> Hidden complete header when user scroll

- src/stories/components/CoreUnitSummary/CoreUnitSummary.tsx
- src/stories/components/DelegateSummary/DelegateSummary.tsx
- src/stories/components/TitleNavigationCuAbout/TitleNavigationCuAbout.tsx
- src/stories/containers/ActorsAbout/ActorSummary/ActorSummary.tsx
- src/stories/containers/ActorsAbout/ActorSummary/ActorTitleAbout.tsx
- src/stories/containers/ActorsAbout/ActorSummary/ActorTitleWithDescription.tsx
- src/stories/containers/ActorsAbout/BreadCrumbNavigation/BreadCrumbNavigation.tsx
https://trello.com/c/FEo923dc/277-qa-bug-finding-r
This adds a better transition to the header component
> Add better transition in the header component

- src/stories/containers/TransparencyReport/components/TransparencyActuals/TransparencyActuals.tsx
- src/stories/containers/TransparencyReport/components/TransparencyActuals/useTransparencyActuals.ts
- src/stories/containers/TransparencyReport/components/TransparencyForecast/TransparencyForecast.tsx
- src/stories/containers/TransparencyReport/components/TransparencyForecast/useTransparencyForecast.tsx
- src/stories/containers/TransparencyReport/utils/helpers.tsx
No ticket
Fixed issue related to the Payment topup transform
> [SES] Fix payment topup

- src/stories/components/svg/CircleWithArrow.tsx
- src/stories/containers/Finances/FinacesContainer.tsx
- src/stories/containers/Finances/SeccionPages/CardChartOverview/CardChartOverview.tsx
- src/stories/containers/Finances/components/ReadMore.tsx
> Add read more button

- src/stories/containers/Finances/FinacesContainer.tsx
- src/stories/containers/Finances/SeccionPages/BreadcrumbYearNavigation.stories.tsx
- src/stories/containers/Finances/SeccionPages/BreadcrumbYearNavigation.tsx
- src/stories/containers/Finances/components/SelectYear.tsx
- src/stories/containers/Finances/useFinances.ts
Solving the issues for the first sections of the page
> [No-ticket] Fix-issues

- src/stories/containers/Endgame/components/KeyChangesSections/Sections/GovernanceSection.tsx
no ticket
Update some copies on the endgame page
> hotfix: Fix copies

- src/stories/containers/Finances/FinacesContainer.tsx
- src/stories/containers/Finances/FinancesContainer.stories.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/InformationBudgetCapOverView/InformationBudgetCapOverView.tsx
- src/stories/containers/Finances/components/OverviewCardMobile/OverviewCardMobile.stories.tsx
- src/stories/containers/Finances/components/OverviewCardMobile/OverviewCardMobile.tsx
- src/stories/containers/Finances/components/SeccionPages/BreadcrumbYearNavigation.stories.tsx
- src/stories/containers/Finances/components/SeccionPages/CardChartOverview/CardChartOverview.stories.tsx
- src/stories/containers/Finances/components/SeccionPages/CardChartOverview/CardChartOverview.tsx
- src/stories/containers/Finances/components/SeccionPages/CardsNavigation/CardsNavigation.stories.tsx
- src/stories/containers/FinancesOverview/components/HorizontalBudgetBar/HorizontalBudgetBar.tsx
> Add correct place for stories and add card resume for mobile

- src/stories/containers/Finances/FinacesContainer.tsx
- src/stories/containers/Finances/components/BreakdownTableFinances/BreakdownTableFinances.stories.tsx
- src/stories/containers/Finances/components/BreakdownTableFinances/BreakdownTableFinances.tsx
- src/stories/containers/Finances/components/FiltersTable/FilterTable.tsx
- src/stories/containers/Finances/components/SelectDropdown.tsx
- src/stories/containers/Finances/useFinances.tsx
- src/stories/containers/Finances/utils/types.ts
This add the filters for the table, add both filters and styled them
> Add filters style for menu dropdown

- src/stories/containers/Endgame/components/NavigationTabs/NavigationTabs.tsx
User Story: Detailed Insight into Endgame Budget Structure
- Should allow to smooth navigate through the browser buttons (on back/forward click)
> feat: endgame page browser buttons navigation

- src/stories/containers/Finances/FinacesContainer.tsx
- src/stories/containers/Finances/components/CardNavigationFinance/CardNavigationFinance.stories.tsx
- src/stories/containers/Finances/components/CardNavigationFinance/CardNavigationFinance.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/InformationBudgetCapOverView/InformationBudgetCapOverView.tsx
- src/stories/containers/Finances/components/OverviewCardMobile/OverviewCardMobile.stories.tsx
- src/stories/containers/Finances/components/SeccionPages/CardChartOverview/CardChartOverview.stories.tsx
- src/stories/containers/Finances/components/SeccionPages/CardChartOverview/CardChartOverview.tsx
- src/stories/containers/Finances/components/SeccionPages/CardsNavigation/CardsNavigation.stories.tsx
- src/stories/containers/Finances/components/SeccionPages/CardsNavigation/CardsNavigation.tsx
- src/stories/containers/Finances/utils/utils.ts
Should Add responsive for the card's navigations
> Add responsive for cards navigation and view

- src/stories/containers/Finances/FinacesContainer.tsx
- src/stories/containers/Finances/components/SeccionPages/DelegateExpenseTrendFinances/DelegateExpenseTrendFinances.stories.tsx
- src/stories/containers/Finances/components/SeccionPages/DelegateExpenseTrendFinances/DelegateExpenseTrendFinances.tsx
- src/stories/containers/Finances/components/SeccionPages/LatestExpenseReports.tsx
This add section for the Delegate Expense Trend
> Add title and description for expense Trend

- src/stories/containers/Endgame/components/EndgameIntroductionBanner/EndgameIntroductionBanner.tsx
- src/stories/containers/Endgame/components/EndgameIntroductionBanner/EndgameIntroductionEndgameIntroductionBanner.stories.tsx
No ticket
Make the image in the endgame banner fit the page container
> Fix endgame image

- src/stories/containers/Endgame/components/EndgameIntroductionBanner/EndgameIntroductionBanner.tsx
No ticket
Change image color by gradient
> Change color by gradient

- src/stories/components/svg/ArrowNavigationForCards.tsx
- src/stories/containers/Finances/components/CardNavigationMobile/CardNavigationMobile.stories.tsx
- src/stories/containers/Finances/components/CardNavigationMobile/CardNavigationMobile.tsx
- src/stories/containers/Finances/components/SeccionPages/CardsNavigation/CardsNavigation.stories.tsx
- src/stories/containers/Finances/components/SeccionPages/CardsNavigation/CardsNavigation.tsx
- src/stories/containers/Finances/useFinances.tsx
- src/stories/containers/Finances/utils/types.ts
Add style for the new styled in mobile card
> [SES-294] Add new style for navigation card in mobile

- src/stories/components/CircleAvatar/CircleAvatarWithIcon.tsx
- src/stories/components/svg/ArrowNavigationForCards.tsx
- src/stories/components/svg/MultiUsersMobile.tsx
- src/stories/containers/Finances/components/DelegateExpenseTrend/DelegateExpenseTrendItem.stories.tsx
- src/stories/containers/Finances/components/DelegateExpenseTrend/DelegateExpenseTrendItem.tsx
- src/stories/containers/Finances/components/ViewButton/ViewButton.tsx
- src/stories/containers/TransparencyReport/components/ExpenseReportStatusIndicator/ExpenseReportStatusIndicator.tsx
Should add item for the each expense report
Add item for expense report
> Add item in the expense report

- src/stories/containers/Endgame/EndgameContainer.tsx
- src/stories/containers/Endgame/components/BudgetStructureSection/BudgetStructureSection.tsx
- src/stories/containers/Endgame/components/BudgetTransitionStatusSection/BudgetTransitionStatusSection.tsx
- src/stories/containers/Endgame/components/NavigationTabs/NavigationTabs.tsx
- src/stories/containers/Endgame/useEndgameContainer.ts
Fixed the scroll on firefox and safari
> [SES-292] Fix scroll issue on firefox

- src/stories/containers/Finances/components/SeccionPages/DelegateExpenseTrendFinances/DelegateExpenseTrendFinances.stories.tsx
- src/stories/containers/Finances/components/SeccionPages/DelegateExpenseTrendFinances/DelegateExpenseTrendFinances.tsx
Should have the Latest Expense Reports  title and small description 
Add correct text to stories
> Add the correct text

- src/stories/components/CircleAvatar/CircleAvatarWithIcon.tsx
- src/stories/containers/Actors/components/ActorLastModified/ActorLastModified.tsx
- src/stories/containers/Finances/FinacesContainer.tsx
- src/stories/containers/Finances/components/DelegateExpenseTrend/DelegateExpenseTrendItem.stories.tsx
- src/stories/containers/Finances/components/DelegateExpenseTrend/DelegateExpenseTrendItem.tsx
- src/stories/containers/Finances/components/DelegateExpenseTrend/HeaderDelegateExpense.stories.tsx
- src/stories/containers/Finances/components/DelegateExpenseTrend/HeaderDelegateExpense.tsx
- src/stories/containers/Finances/components/SeccionPages/DelegateExpenseTrendFinances/DelegateExpenseTrendFinances.tsx
- src/stories/containers/Finances/useFinances.tsx
- src/stories/containers/Finances/utils/utils.ts
- styles/theme/light.ts
Add new breakpoints to component
> Responsive item for new breakpoints

- src/core/hooks/useHeaderSummary.ts
- src/stories/containers/ActorsAbout/ActorAboutContainer.tsx
- src/stories/containers/ActorsAbout/ActorSummary/ActorSummary.tsx
Fix the issue when user scroll on the header
> [No-ticket-278]Add forwardRef for the actor summary

- .eslintrc.js
- src/stories/containers/Actors/ActorsContainer.stories.tsx
- src/stories/containers/Endgame/components/BudgetDoughnutChart/BudgetDoughnutChart.tsx
- src/stories/containers/Endgame/components/BudgetStructureSection/BudgetStructureSection.stories.tsx
- src/stories/containers/Endgame/components/BudgetStructureSection/BudgetStructureSection.tsx
- src/stories/containers/Endgame/components/EndgameIntroductionBanner/EndgameIntroductionBanner.stories.tsx
- src/stories/containers/Endgame/components/EndgameIntroductionBanner/EndgameIntroductionBanner.tsx
- src/stories/containers/Endgame/components/IntroductoryHeadline/IntroductoryHeadline.stories.tsx
- src/stories/containers/Endgame/components/IntroductoryHeadline/IntroductoryHeadline.tsx
- src/stories/containers/Endgame/components/KeyChangeCard/KeyChangeCard.tsx
- src/stories/containers/Endgame/components/KeyChangesSections/KeyChangesSections.tsx
- src/stories/containers/Endgame/components/NavigationTabs/NavigationTabs.tsx
- src/stories/containers/Endgame/components/SectionHeader/SectionHeader.tsx
- src/stories/containers/Endgame/components/TotalBudgetContent/TotalBudgetContent.tsx
- src/stories/containers/Endgame/components/TransitionHeader/TransitionHeader.tsx
- src/stories/containers/Endgame/utils/index.ts
Migrated to the new endpoints in the first sections
> [SES-292] Migrate endgame first sections to use new endpoints

- src/core/utils/storybook/decorators.tsx
- src/stories/components/DelegateSummary/DelegateSummary.stories.tsx
- src/stories/components/DelegateSummary/DelegateSummary.tsx
- src/stories/containers/RecognizedDelegatesReports/RecognizedDelegatesReportContainer.tsx
- src/stories/containers/RecognizedDelegatesReports/useRecognizedDelegatesReport.tsx
https://trello.com/c/udGDe7fW/278-qc-round-1-r
Fix header in delegate
> [No-ticket] Solving issue header in delegate

- src/stories/containers/ActorsTransparencyReport/ActorsTransparencyReportContainer.tsx
https://trello.com/c/udGDe7fW/278-qc-round-1-r
Fix the issue in transparency report actor
> [SES-No-ticket-278]Add transparency actor

- src/stories/containers/FinancesOverview/components/NavigationButtons/NavigationButtons.tsx
https://trello.com/c/udGDe7fW/278-qc-round-1-r
Add actors button
> [SES-no-ticket-278] Add actors button

- pages/snapshots/[...data].tsx
- src/core/utils/string.ts
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/TemporaryContainer.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/api/queries.ts
https://trello.com/c/OTAKvqeH/308-user-story-delegates-and-keepers-snapshot-reports
Fix the copy in the tooltip
> [SES-308] Snapshots keepers tooltip

- src/stories/containers/Endgame/components/BudgetTransitionChart/BudgetTransitionChart.tsx
- src/stories/containers/Endgame/components/BudgetTransitionStatusSection/BudgetTransitionStatusSection.stories.tsx
- src/stories/containers/Endgame/components/BudgetTransitionStatusSection/BudgetTransitionStatusSection.tsx
https://trello.com/c/K6BCBa9u/293-user-story-visualization-of-budget-transition-status
Migrated the section "Budget Transition Status" to use the new breakpoints
> [SES-293] Migrate the breakpoints in the endgame transition section

- src/stories/containers/Finances/components/DelegateExpenseTrend/DelegateExpenseTrendItem.tsx
- src/stories/containers/Finances/components/ViewButton/ViewButton.tsx
Add the button View style and links
> Add hover for button

- src/stories/containers/Actors/useActors.ts
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
- src/stories/containers/Finances/utils/utils.ts
Show show correct legend item with the chart
> Feature styles overbudget chart

- src/stories/containers/Finances/components/CardNavigationFinance/CardNavigationFinance.stories.tsx
- src/stories/containers/Finances/components/CardNavigationFinance/CardNavigationFinance.tsx
- src/stories/containers/Finances/components/CardNavigationMobile/CardNavigationMobile.tsx
- src/stories/containers/Finances/components/SeccionPages/CardsNavigation/CardsNavigation.stories.tsx
- src/stories/containers/Finances/components/SeccionPages/CardsNavigation/CardsNavigation.tsx
- src/stories/containers/Finances/useFinances.tsx
Should have tooltip when hover with the correct structure
> Add correct size for the chart and adjust navigation cards

- src/stories/containers/Finances/components/CardNavigationMobile/CardNavigationMobile.tsx
- src/stories/containers/Finances/components/DelegateExpenseTrend/DelegateExpenseTrendItem.tsx
Correct some style in the mobile card
> Pass as props data in card mobile

- src/stories/components/CoreUnitSummary/CoreUnitSummary.tsx
- src/stories/components/DelegateSummary/DelegateSummary.tsx
- src/stories/containers/ActorsAbout/ActorSummary/ActorSummary.tsx
Removed the extra space in the Summaries
> [SES-310] Summaries extra space

- src/stories/containers/Endgame/useEndgameContainer.ts
no ticket
Improved the navigation on the endgame page, when the users scrolled down sometimes the correct item didn't get selected, now fixed
> [SES] Improve endgame navigation

- src/stories/containers/Finances/FinancesContainer.stories.tsx
- src/stories/containers/Finances/components/DelegateExpenseTrend/DelegateExpenseTrendItem.stories.tsx
- src/stories/containers/Finances/components/DelegateExpenseTrend/DelegateExpenseTrendItem.tsx
- src/stories/containers/Finances/components/DelegateExpenseTrend/HeaderDelegateExpense.stories.tsx
- src/stories/containers/Finances/components/DelegateExpenseTrend/HeaderDelegateExpense.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
- src/stories/containers/Finances/components/SeccionPages/CardChartOverview/CardChartOverview.stories.tsx
- src/stories/containers/Finances/utils/utils.ts
Should show the correct information in the section and fix responsive in the last expense report
> [Ticket-294] Issues/last expense report responsive

- src/stories/containers/Finances/FinancesContainer.stories.tsx
- src/stories/containers/Finances/components/FiltersTable/FilterTable.tsx
Fix issues, correct selector in the filter
> [Not-ticket] Select the correct element

- src/stories/containers/Finances/FinacesContainer.tsx
- src/stories/containers/Finances/components/ConditionalWrapper/ConditionalWrapper.tsx
- src/stories/containers/Finances/components/FiltersTable/FilterTable.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderQuarterly/CellQuarterly.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderQuarterly/HeaderQuarterly.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderTable.tsx
- src/stories/containers/Finances/components/SeccionPages/BreakdownTable.tsx
- src/stories/containers/Finances/useFinances.tsx
- src/stories/containers/Finances/utils/types.ts
- src/stories/containers/Finances/utils/utils.ts
Add header for quarterly when the period is selected
> Add header for quarterly

- src/stories/containers/FinancesOverview/FinancesOverviewContainer.stories.tsx
- src/stories/containers/FinancesOverview/FinancesOverviewContainer.tsx
- src/stories/containers/FinancesOverview/components/ExpensesChart/ExpensesChart.stories.tsx
- src/stories/containers/FinancesOverview/components/ExpensesChart/ExpensesChart.tsx
- src/stories/containers/FinancesOverview/components/ExpensesChart/LegendItem.tsx
- src/stories/containers/FinancesOverview/components/HorizontalBudgetBar/HorizontalBudgetBar.tsx
- src/stories/containers/FinancesOverview/components/NavigationButtons/NavigationButtons.tsx
- src/stories/containers/FinancesOverview/components/QuarterCard/QuarterCard.stories.tsx
- src/stories/containers/FinancesOverview/components/QuarterCard/QuarterCard.tsx
- src/stories/containers/FinancesOverview/components/QuarterCarousel/QuarterCarousel.stories.tsx
- src/stories/containers/FinancesOverview/components/QuarterCarousel/QuarterCarousel.tsx
- src/stories/containers/FinancesOverview/components/QuarterCarousel/useQuarterCarousel.ts
- src/stories/containers/FinancesOverview/components/YearPicker/YearPicker.stories.tsx
- src/stories/containers/FinancesOverview/components/YearPicker/YearPicker.tsx
- src/stories/containers/FinancesOverview/useFinancesOverview.ts
https://trello.com/c/NU2xBFF9/313-finances-homepage-breakpoints-changes
Adapt the Finances page to use the new Breakpoints
> [SES-313] Support new breakpoints finances

- src/stories/containers/Finances/components/HeaderTable/FinancesTable.tsx
Add different cells values with the different breakpoints
> Add style total row and fix number according dimensions

- src/stories/components/BasicModal/ContainerModal.tsx
- src/stories/containers/FinancesOverview/components/CostBreakdownTable/ByBudgetTableRow.tsx
- src/stories/containers/FinancesOverview/components/CostBreakdownTable/CostBreakdownTable.tsx
https://trello.com/c/NU2xBFF9/313-finances-homepage-breakpoints-changes
> Fix finances links

- src/stories/containers/Finances/components/FiltersTable/FilterTable.tsx
- src/stories/containers/Finances/components/FinacesTable/FinancesTable.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderAnnually/HeaderAnnually.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderMonthly/CellMonthly.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderMonthly/HeaderMonthly.tsx
Construct the table for monthly filter period
> Feature finaces table new filter option

- src/stories/containers/Finances/components/FinacesTable/FinancesTable.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderAnnually/HeaderAnnually.tsx
Add correct header for annually and construct the table for that filter
> Add responsive header for monthly and create table for it

- src/stories/containers/Finances/components/FinacesTable/CellTable.tsx
- src/stories/containers/Finances/useFinances.tsx
- src/stories/containers/Finances/utils/utils.ts
> Add responsive for table in monthly and add some default values

- src/stories/containers/RecognizedDelegates/RecognizedDelegatesContainer.tsx
- src/stories/containers/RecognizedDelegates/components/DelegateExpenseBreakdownCard.tsx
- src/stories/containers/RecognizedDelegates/useRecognizedDelegates.ts
Fix the progress bars on the delegates page that were showing no progress due to NaN values
> [SES-310] Fix delegates NaN values

- src/core/businessLogic/coreUnits.ts
- src/stories/containers/RecognizedDelegates/api/RecognizedDelegatesAPI.ts
- src/stories/containers/TransparencyReport/components/TransparencyAuditorComments/AuditorCommentCard.tsx
> fix: recognized delegates breaking issues

- package.json
- src/stories/components/SingleItemSelect/SingleItemSelect.stories.tsx
- src/stories/components/SingleItemSelect/SingleItemSelect.tsx
- yarn.lock
https://trello.com/c/lJtOvFKL/304-feature-breakdown-chart
Upgrade the MUI version and create a new Select component that has the same behavior and styles of the rest of the app, also it is highly and easily customizable following the SOLID principles
> [SES-304] Create a single item select component

- src/stories/containers/Finances/components/FiltersTable/FilterTable.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderAnnually/CellAnnually.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderQuarterly/CellQuarterly.tsx
Fix issues relate with the table and refactoring the code
> [SES-294] Fix issues in the breakdown table

- src/core/utils/typesHelpers.ts
- src/stories/components/CustomMultiSelect/CustomMultiSelect.tsx
- src/stories/components/SearchInput/SearchInput.tsx
- src/stories/containers/ActorProjects/ActorProjectsContainer.tsx
- src/stories/containers/ActorProjects/components/PageSubheader/PageSubheader.stories.tsx
- src/stories/containers/ActorProjects/components/PageSubheader/PageSubheader.tsx
- src/stories/containers/ActorProjects/components/ProjectFilters/ProjectFilters.tsx
- src/stories/containers/ActorProjects/useActorProjectsContainer.ts
https://trello.com/c/0oAK0jem/299-user-story-tpd-11-projects-overview-v1
Add the subheader to the projects page with the title and the filters
> [SES-299] Project page subheader

- .vscode/settings.json
- src/core/businessLogic/builders/actors/deliverableBuilder.ts
- src/core/businessLogic/builders/actors/projectBuilder.ts
- src/stories/containers/ActorProjects/api/query.ts
- src/stories/containers/ActorProjects/components/BudgetTypeBadge/BudgetTypeBadge.tsx
- src/stories/containers/ActorProjects/components/DeliverableCard/DeliverableCard.tsx
- src/stories/containers/ActorProjects/components/DeliverableStatusChip/DeliverableStatusChip.tsx
- src/stories/containers/ActorProjects/components/ProjectCard/ProjectCard.stories.tsx
- src/stories/containers/ActorProjects/components/ProjectCard/ProjectCard.tsx
- src/stories/containers/ActorProjects/components/ProjectProgress/ProjectProgress.tsx
- src/stories/containers/ActorProjects/components/ProjectStatusChip/ProjectStatusChip.tsx
- src/stories/containers/ActorProjects/components/SupportedTeamsAvatarGroup/SupportedTeamsAvatarGroup.tsx
- src/stories/containers/ActorProjects/utils/colors.ts
https://trello.com/c/0oAK0jem/299-user-story-tpd-11-projects-overview-v1
Add project progress, status, name, image, abstract and base for deliverables
> [SES-299] Project card name, progress & status

- src/stories/containers/ActorProjects/ActorProjectsContainer.tsx
- src/stories/containers/ActorProjects/components/PageSubheader/PageSubheader.stories.tsx
- src/stories/containers/ActorProjects/components/PageSubheader/PageSubheader.tsx
- src/stories/containers/ActorProjects/components/ProjectCard/ProjectCard.stories.tsx
- src/stories/containers/ActorProjects/components/ProjectCard/ProjectCard.tsx
- src/stories/containers/ActorProjects/components/ProjectFilters/ProjectFilters.tsx
- src/stories/containers/ActorProjects/useActorProjectsContainer.ts
Change the project filters UI on mobile in favor of a new design
> [SES-299] Update mobile filters

- src/stories/containers/EndgameBudgetContainerSecondLevel/EndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerSecondLevel/useEndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/Finances/FinacesContainer.tsx
- src/stories/containers/Finances/components/SectionPages/CardsNavigation/CardsNavigation.tsx
- src/stories/containers/Finances/useFinances.tsx
> Add the load more button and check the API

- src/core/businessLogic/builders/actors/deliverableBuilder.ts
- src/core/businessLogic/builders/actors/projectBuilder.ts
- src/core/models/interfaces/projects.ts
- src/stories/components/CustomLink/CustomLink.tsx
- src/stories/components/ExternalLink/ExternalLink.tsx
- src/stories/components/svg/external-link-arrow.tsx
- src/stories/containers/ActorProjects/api/query.ts
- src/stories/containers/ActorProjects/components/DeliverableCard/DeliverableCard.tsx
- src/stories/containers/ActorProjects/components/DeliverablePercentageBar/DeliverablePercentageBar.tsx
- src/stories/containers/ActorProjects/components/DeliverableStoryPointsBar/DeliverableStoryPointsBar.tsx
- src/stories/containers/ActorProjects/components/KeyResults/KeyResults.tsx
- src/stories/containers/ActorProjects/components/ProjectCard/ProjectCard.stories.tsx
- src/stories/containers/ActorProjects/components/ProjectCard/ProjectCard.tsx
Add the deliverable progress and key results
> [SES-299] Deliverable progress & key results

- src/stories/containers/ActorProjects/components/DeliverableCard/DeliverableCard.tsx
- src/stories/containers/ActorProjects/components/ProjectCard/ProjectCard.tsx
- src/stories/containers/ActorProjects/components/ViewAllButton/ViewAllButton.tsx
Added the "View all deliverables" button
- Should display the View all Deliverables expand button
> [SES-299] View all deliveries button

- src/stories/containers/Finances/FinacesContainer.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChart/BreakdownChart.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChartSection.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/useBreakdownChart.ts
- src/stories/containers/Finances/utils/types.ts
- src/stories/containers/Finances/utils/utils.ts
This add the borders dynamic , and process the data
Should prepare the bars taking into account the dynamic data.
> Add function to dynamic create borders

- src/stories/containers/Finances/FinacesContainer.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChart/BreakdownChart.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChartSection.stories.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChartSection.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/useBreakdownChart.ts
Add effect to hidden legend when is clicked
> Add effect to hidden legend when clicked

- src/stories/containers/Finances/components/FinacesTable/FinancesTable.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderMonthly/CellMonthly.tsx
> [SES-294] Fix total header in monthly and change size of others

- pages/finances/[codePath]/[...code]/index.tsx
- src/stories/containers/EndgameBudgetContainerSecondLevel/EndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerThirdLevel/EndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/EndgameBudgetContainerThirdLevel/useEndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/Finances/FinacesContainer.tsx
- src/stories/containers/Finances/components/CardCoreUnitThirdLevelBudget/CardCoreUnitThirdLevelBudget.tsx
- src/stories/containers/Finances/components/CardNavigationMobile/CardNavigationMobile.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/BreakdownTable.tsx
- src/stories/containers/Finances/utils/types.ts
This add the third level for the Finances Page
> Add mock for the third level

- src/stories/containers/EndgameBudgetContainerThirdLevel/useEndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderAnnually/CellAnnually.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderQuarterly/CellQuarterly.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderQuarterly/HeaderQuarterly.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/MakerDAOChartMetrics/MakerDAOChartMetrics.tsx
- src/stories/containers/Finances/utils/utils.ts
Fix issues when position revert
Fix the position revert in finances page, that made the legend float in wrong position
> [Not-ticket] Revert position absolute

- src/stories/containers/Finances/utils/utils.ts
Fix the issues when there is not name
Default text when there is not name
> [No-ticket] Fix when there is not name

- src/stories/containers/ActorProjects/components/DeliverableStoryPointsBar/DeliverableStoryPointsBar.tsx
- src/stories/containers/ActorProjects/components/ProjectFilters/ProjectFilters.tsx
- src/stories/containers/ActorProjects/components/ProjectStatusChip/ProjectStatusChip.tsx
- src/stories/containers/ActorProjects/useActorProjectsContainer.tsx
Fix Story Point status bar color and status items
> [SES-299] fix: project status filter

- src/stories/containers/ActorProjects/components/DeliverableCard/DeliverableCard.tsx
- src/stories/containers/ActorProjects/components/OwnerTooltipContent/OwnerTooltipContent.tsx
- src/stories/containers/ActorProjects/components/ProjectCard/ProjectCard.stories.tsx
- src/stories/containers/ActorProjects/components/ProjectCard/ProjectCard.tsx
- src/stories/containers/ActorProjects/components/ProjectFilters/ProjectFilters.tsx
- src/stories/containers/ActorProjects/components/SupportedTeamsAvatarGroup/SupportedTeamsAvatarGroup.tsx
- src/stories/containers/ActorsAbout/components/ActorNavigationOptions/ActorNavigationOptions.tsx
Fixed several issues related to the project page
> [SES-299] Fix: Project issues

- pages/finances/index.tsx
- src/core/businessLogic/builders/budgetAnalyticBuilder.ts
- src/core/models/interfaces/analytic.ts
- src/stories/containers/EndgameBudgetContainerSecondLevel/useEndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerThirdLevel/useEndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/Finances/FinancesContainer.stories.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
- src/stories/containers/Finances/useFinances.tsx
- src/stories/containers/Finances/utils/utils.ts
> feat: BSN-1 Budget Summary + Navigation (2)

- src/stories/containers/EndgameBudgetContainerSecondLevel/useEndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
- src/stories/containers/Finances/utils/types.ts
This is for connect API doughnut chart with the API in the first level
> Connect first level doughnut

- src/stories/containers/ActorProjects/components/ProjectCard/ProjectCard.tsx
> [TPD-1] Change deliverables title

- src/stories/containers/EndgamePhaseOneProgress/EndgamePhaseOneProgressContainer.tsx
- src/stories/containers/EndgamePhaseOneProgress/components/Breadcrumb/Breadcrumb.tsx
https://trello.com/c/HIe66Yme/297-emp-1-endgame-milestones-progress
Added a breadcrumb for the Phase 1 progress page
> [RMV-1] Phase 1 progress breadcrumb

- src/stories/containers/EndgamePhaseOneProgress/components/MilestoneCard/MilestoneCard.stories.tsx
- src/stories/containers/EndgamePhaseOneProgress/components/MilestoneCard/MilestoneCard.tsx
Created the Milestones cards for the roadmap
> [RMV-1] Milestones card

- src/stories/containers/EndgamePhaseOneProgress/components/MilestoneCard/MilestoneCard.tsx
- src/stories/containers/EndgamePhaseOneProgress/components/PageHeader/PageHeader.tsx
- src/stories/containers/EndgamePhaseOneProgress/components/RoadmapTimeline/RoadmapTimeline.tsx
- src/stories/containers/EndgamePhaseOneProgress/components/SectionTitle/SectionTitle.tsx
- src/stories/containers/EndgamePhaseOneProgress/components/sections/OverviewSection/OverviewSection.tsx
Created the UI for the milestones Roadmap
> [RMV-1] Milestones timeline

- pages/finances/index.tsx
- src/stories/containers/EndgameBudgetContainerSecondLevel/EndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerSecondLevel/useEndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerThirdLevel/EndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/EndgameBudgetContainerThirdLevel/useEndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChart/BreakdownChart.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChartFilter/BreakdownChartFilter.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChartSection.stories.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChartSection.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/useBreakdownChart.ts
- src/stories/containers/Finances/components/BreakdownChartSection/utis.ts
- src/stories/containers/Finances/useFinances.tsx
- src/stories/containers/Finances/utils/types.ts
- src/stories/containers/Finances/utils/utils.ts
https://trello.com/c/GLeuvMJI/323-bc-13-breakdown-chart-ability-to-change-granularity
Change the values in the chart when the granularity change
> [SES-323] Breakdown chart-ability-to-change-granularity

- src/stories/containers/EndgameBudgetContainerSecondLevel/EndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerSecondLevel/useEndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerThirdLevel/EndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/EndgameBudgetContainerThirdLevel/useEndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/EndgamePhaseOneProgress/components/MilestoneDetailsCard/MilestoneDetailsCard.stories.tsx
- src/stories/containers/EndgamePhaseOneProgress/components/MilestoneDetailsCard/MilestoneDetailsCard.tsx
- src/stories/containers/EndgamePhaseOneProgress/components/sections/DetailsSection/DetailsSection.tsx
- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/DelegateExpenseTrend/HeaderDelegateExpense.tsx
- src/stories/containers/Finances/components/SectionPages/DelegateExpenseTrendFinances/DelegateExpenseTrendFinances.tsx
- src/stories/containers/Finances/components/SectionPages/DelegateExpenseTrendFinances/ExpenseReportsFilters.tsx
- src/stories/containers/Finances/components/SectionPages/DelegateExpenseTrendFinances/useDelegateExpenseTrendFinances.tsx
- src/stories/containers/Finances/useFinances.tsx
> [MER-1] Finances expense reports filters

- .vscode/settings.json
- pages/finances/index.tsx
- src/core/models/interfaces/analytic.ts
- src/stories/components/SingleItemSelect/SingleItemSelect.tsx
- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/MakerDAOChartMetrics.stories.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/MakerDAOChartMetrics/MakerDAOChartMetrics.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/MakerDAOExpenseMetrics.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/TitleFilterComponent.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/useMakerDAOExpenseMetrics.tsx
- src/stories/containers/Finances/useFinances.tsx
- src/stories/containers/Finances/utils/types.ts
Integrate the MakerDAO Expense Metrics line chart with the API
> [EML-1] Integrate EML with API

- src/core/businessLogic/builders/analyticBuilder.ts
- src/stories/containers/EndgameBudgetContainerSecondLevel/EndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerSecondLevel/useEndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerThirdLevel/EndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/EndgameBudgetContainerThirdLevel/useEndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/Finances/FinancesContainer.stories.tsx
- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChart/BreakdownChart.tsx
- src/stories/containers/Finances/components/BreakdownTableFinances/BreakdownTableFinances.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderAnnually/HeaderAnnually.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderMonthly/HeaderMonthly.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderQuarterly/HeaderQuarterly.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderSemiAnnual/HeaderSemiAnnual.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderTable.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/BreakdownTable.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/utils.ts
- src/stories/containers/Finances/useFinances.tsx
- src/stories/containers/Finances/utils/types.ts
- src/stories/containers/Finances/utils/utils.ts
Connect the header of the table for different filters
> Connect the header of the table with the API

- src/core/utils/dictionary.js
- src/stories/containers/EndgameBudgetContainerSecondLevel/EndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerSecondLevel/useEndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerThirdLevel/EndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/EndgameBudgetContainerThirdLevel/useEndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/TitleFilterComponent.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/useMakerDAOExpenseMetrics.tsx
Add the Expenses metrics chart in all the levels
> [EML-1] Add  Expense Metrics Chart in all the levels

- src/stories/containers/EndgameBudgetContainerSecondLevel/EndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerSecondLevel/useEndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerThirdLevel/useEndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/Finances/FinancesContainer.stories.tsx
- src/stories/containers/Finances/components/FinacesTable/CellTable.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/utils.ts
- src/stories/containers/Finances/useFinances.tsx
https://trello.com/b/iebIfrww/ses-dashboard
Fix issues in the table
> [No-ticket]  Fix-Feat/breakdown table improv

- src/stories/containers/Finances/components/FinacesTable/FinancesTable.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
- src/stories/containers/Finances/utils/mockData.ts
- src/stories/containers/Finances/utils/types.ts
- src/stories/containers/Finances/utils/utils.ts
No ticket
Refactor the table TS type
> refactor: change table column field name

- src/stories/containers/Finances/utils/utils.ts
> Fix others row when there is exact 16 rows

- src/stories/components/IconTitle/IconTitle.tsx
- src/stories/containers/Finances/components/CardCoreUnitThirdLevelBudget/CardCoreUnitThirdLevelBudget.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
Solving issues on finances page and their level
> [SES-330] Fix issues on finances page

- src/stories/containers/EndgameBudgetContainerSecondLevel/EndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerSecondLevel/useEndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerThirdLevel/EndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/EndgameBudgetContainerThirdLevel/useEndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/CardChartOverview.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
- src/stories/containers/Finances/useFinances.tsx
Fix issues in the finances page
> Improve the dougnat chart

- src/stories/containers/EndgameBudgetContainerSecondLevel/useEndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChart/BreakdownChart.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/MakerDAOChartMetrics/MakerDAOChartMetrics.tsx
- src/stories/containers/Finances/utils/chartTooltip.ts
Added a tooltip to the expenses metric line chart when the user hovers the values
> [EML-1] Add expenses metric line chart tooltip

- .vscode/settings.json
- src/core/utils/dictionary.js
- src/stories/containers/EndgamePhaseOneProgress/EndgamePhaseOneProgressContainer.tsx
- src/stories/containers/EndgamePhaseOneProgress/components/MilestoneCard/MilestoneCard.stories.tsx
- src/stories/containers/EndgamePhaseOneProgress/components/MilestoneCard/MilestoneCard.tsx
Updated the breadcrumb and the title of the milestone cards
> [RMV-1] Roadmap mobile title card

- src/stories/containers/EndgameBudgetContainerThirdLevel/EndgameBudgetContainerThirdLevel.tsx
>  Slider for the Third level Budgets

- src/stories/containers/Finances/FinancesContainer.stories.tsx
No ticket
Temporarily disable the new finances page story until we can fix it
> Disable finances stories

- src/stories/containers/Finances/components/FinacesTable/CellTable.tsx
Fix the align in the table body
> Add same style in cell body

- src/stories/containers/Finances/components/FinacesTable/FinancesTable.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderSemiAnnual/CellSemiAnnual.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderSemiAnnual/HeaderSemiAnnual.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
Fix issues found in budget + navigations
> Fix container swiper don't grow

- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/CardLegend.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/CardChartOverview.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/utils.ts
Fix issues in the budget finances page
> [BSN-330] Remove percent and rounded the number in third level

- src/stories/containers/EndgameBudgetContainerThirdLevel/EndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/useBreakdownChart.ts
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/CardLegend.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/utils.ts
> [BSN-330] Add more length for the code

- src/stories/containers/Finances/components/FinacesTable/FinancesTable.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
> [BSN-330] Fix issues when the table don't have sub-Budgets

- src/stories/containers/FinancesOverview/FinancesOverviewContainer.tsx
- src/stories/containers/FinancesOverview/components/CostBreakdownTable/CostBreakdownTable.stories.tsx
- src/stories/containers/FinancesOverview/useFinancesOverview.ts
Fix the total expenses number as it does not coincide with the total number of the breakdown table
> [QC] Fix total expenses number

- src/stories/containers/FinancesOverview/FinancesOverviewContainer.tsx
Remove the decimal places form the total expenses
> Fix total expenses decimals

- src/core/utils/typesHelpers.ts
- src/stories/components/svg/CircleLegendChart.tsx
- src/stories/components/svg/DAIIcon.tsx
- src/stories/containers/EndgameBudgetContainerSecondLevel/EndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerSecondLevel/useEndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerThirdLevel/EndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/EndgameBudgetContainerThirdLevel/useEndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/LegendItemChart/LegendItemChart.tsx
- src/stories/containers/Finances/components/LineYearBorderBottomChart/LineYearBorderBottomChart.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DaiToolTipIcon.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/CardChartOverview.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterFallChartSection/ReservesWaterFallChartSection.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterFallChartSection/useReservesWaterFallChart.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterFallChartSection/utils.ts
- src/stories/containers/Finances/components/WaterFallChart/WaterFallChart.tsx
- src/stories/containers/Finances/useFinances.tsx
- src/stories/containers/Finances/utils/types.ts
- src/stories/containers/Finances/utils/utils.ts
Add waterfall to the finances page
> Add waterFall chart

- src/stories/containers/Finances/components/CardNavigationFinance/CardNavigationFinance.stories.tsx
- src/stories/containers/Finances/components/CardNavigationFinance/CardNavigationFinance.tsx
- src/stories/containers/Finances/components/ReadMore.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterFallChartSection/useReservesWaterFallChart.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterFallChartSection/utils.ts
> [No-Ticket] Fix broken page and explore button

- src/stories/containers/EndgameBudgetContainerSecondLevel/useEndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerThirdLevel/useEndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/Finances/components/LegendItemChart/LegendItemChart.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterFallChartSection/useReservesWaterFallChart.tsx
- src/stories/containers/Finances/components/TitleToolTipArrowLink/TitleToolTipArrowLink.tsx
- src/stories/containers/Finances/useFinances.tsx
> Add the dark mode

- src/stories/containers/Finances/components/LineYearBorderBottomChart/LineYearBorderBottomChart.tsx
- src/stories/containers/Finances/components/ReadMore.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterFallChartSection/ReservesWaterFallChartSection.stories.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterFallChartSection/ReservesWaterFallChartSection.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterFallChartSection/useReservesWaterFallChart.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterFallChartSection/utils.ts
- src/stories/containers/Finances/components/WaterFallChart/WaterFallChart.tsx
Add responsive for the waterfall chart
> Add stories for the chart

- src/stories/containers/EndgameBudgetContainerSecondLevel/useEndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerThirdLevel/useEndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/Finances/api/queries.ts
- src/stories/containers/Finances/components/SectionPages/DelegateExpenseTrendFinances/useDelegateExpenseTrendFinances.tsx
- src/stories/containers/Finances/useFinances.tsx
Apply sorting and filtering to the expense report items
> [MER-1] Integrate EMR filters with the API

- src/stories/containers/Finances/components/CardNavigationFinance/CardNavigationFinance.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/utils.ts
- src/stories/containers/Finances/utils/chartTooltip.ts
> Center the text in the cards

- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/CardLegend.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
- src/stories/containers/Finances/useFinances.tsx
> Fix the number slider per view

- src/stories/containers/Finances/components/BreakdownChartSection/useBreakdownChart.ts
- src/stories/containers/Finances/components/SectionPages/ReservesWaterFallChartSection/useReservesWaterFallChart.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterFallChartSection/utils.ts
- src/stories/containers/Finances/components/WaterFallChart/WaterFallChart.tsx
- src/stories/containers/Finances/utils/chartTooltip.ts
Fix issues relate with the RC-1 :Reserves Chart
-[X]  Each bar should show the values and should be connected by lines.  Please, add the lines to connect the bars and make it possible to see the values on the first and last bars.
> Add the line to join the waterfall

- src/stories/containers/ActorProjects/components/ProjectLink/ProjectLink.tsx
Fix deliverable's project link
> [RMV-1] Deliverables project link

- src/stories/containers/Finances/utils/utils.ts
> [BSN-1] Breakdown table header with net protocol

- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/CardNavigationFinance/CardNavigationFinance.stories.tsx
- src/stories/containers/Finances/components/CardNavigationFinance/CardNavigationFinance.tsx
- src/stories/containers/Finances/components/SectionPages/CardsNavigation/CardsNavigation.stories.tsx
- src/stories/containers/Finances/components/SectionPages/CardsNavigation/CardsNavigation.tsx
- src/stories/containers/Finances/useFinances.tsx
- src/stories/containers/Finances/utils/types.ts
- src/stories/containers/Finances/utils/utils.ts
Fix the level in the navigation in the cards
> Add limit in the navigations

- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderMonthly/HeaderMonthly.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderQuarterly/HeaderQuarterly.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderSemiAnnual/HeaderSemiAnnual.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/BreakdownTable.tsx
> Fix the table show the correct name

- src/stories/containers/Finances/components/HeaderTable/HeaderAnnually/HeaderAnnually.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderMonthly/HeaderMonthly.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderQuarterly/HeaderQuarterly.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderSemiAnnual/HeaderSemiAnnual.tsx
- src/stories/containers/Finances/components/HeaderTable/utils.ts
- src/stories/containers/Finances/components/WaterFallChart/WaterFallChart.tsx
> Add correct order for the filters

- src/stories/containers/Finances/components/WaterFallChart/WaterFallChart.tsx
> Fix line colors in the waterfall chart

- src/core/utils/const.ts
- src/stories/containers/Finances/components/ReservesWaterFallFilters/ReservesWaterFallFilters.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterFallChartSection/utils.ts
- src/stories/containers/Finances/components/WaterFallChart/WaterFallChart.tsx
> Fix long number and cero values

- src/stories/containers/Finances/components/LineYearBorderBottomChart/LineYearBorderBottomChart.tsx
- src/stories/containers/Finances/components/WaterFallChart/WaterFallChart.tsx
> [NO-ticket]Fix chart is cut in the top

- src/stories/containers/Finances/components/SectionPages/ReservesWaterFallChartSection/ReservesWaterFallChartSection.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterFallChartSection/useReservesWaterFallChart.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterFallChartSection/utils.ts
- src/stories/containers/Finances/components/WaterFallChart/WaterFallChart.tsx
- src/stories/containers/Finances/utils/types.ts
https://trello.com/c/3nvO11Pb/329-fte-1-fte-chart
Fix lines appear at the bottom
axis displays the red line and the +0 values in green color.
> [RC-1] Remove the line at the bottom

- src/stories/containers/Finances/components/SectionPages/ReservesWaterFallChartSection/ReservesWaterFallChartSection.tsx
- src/stories/containers/Finances/components/WaterFallChart/WaterFallSkeleton.tsx
Add the loading for the waterfall chart
> Add correct loading for waterfall

- pages/finances/[[...path]].tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
- src/stories/containers/Finances/useFinances.tsx
Remove unnecessary query as it can be reused be data fetched in the server
> [BSN-1] Remove unnecessary query

- src/stories/containers/Finances/components/WaterFallChart/WaterFallChart.tsx
This fix the problem about the lines wrong painting in the bars
> [RC-1] Fix the problem relate wit the lines in waterfall chart

- src/stories/containers/Finances/components/HeaderTable/HeaderAnnually/CellAnnually.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderAnnually/HeaderAnnually.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderSemiAnnual/HeaderSemiAnnual.tsx
Fix issues in the table in annually and semi-annually
> Fix the problem  in the table

- src/stories/components/ResponsiveButtonClearFilter/ResponsiveButtonClearFilter.tsx
- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/BreakdownTableFinances/BreakdownTableFinances.tsx
- src/stories/containers/Finances/components/FiltersTable/FilterTable.tsx
- src/stories/containers/Finances/components/ReservesWaterFallFilters/ReservesWaterFallFilters.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/BreakdownTable.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
- src/stories/containers/Finances/components/SectionPages/ExpenseReports/ExpenseReportsFilters.tsx
- src/stories/containers/Finances/components/SectionPages/ExpenseReports/useExpenseReports.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterFallChartSection/ReservesWaterFallChartSection.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterFallChartSection/useReservesWaterFallChart.tsx
No ticket
Add the component for the reset filter
> [No-ticket] Add reset filter button for mobile as component

- src/stories/containers/Finances/components/SectionPages/ReservesWaterFallChartSection/utils.ts
Improve the linea that connect the bars
> Improve the line tie the bar

- src/stories/containers/Finances/components/FinacesTable/FinancesTable.tsx
- src/stories/containers/Finances/utils/types.ts
no ticket
remove unused property on finances table types
> chore: remove other property form table type

- src/stories/containers/Finances/utils/utils.ts
> Remove the small letter for start and finish in RC

- src/stories/containers/Finances/components/BreakdownTableFinances/BreakdownTableFinances.tsx
> Fix the title in mobile

- src/stories/containers/Finances/components/SectionPages/ReservesWaterFallChartSection/utils.ts
Fix the array to start to construct the formula
> Use the rest onChain and Protocol as array for the waterfall

- src/stories/components/IconTitle/IconTitle.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
The doughnut chart was having a strange behavior when the windows were resized
> [BSN-1] Fix doughnut chart flickering

- src/stories/containers/Finances/components/HeaderTable/HeaderMonthly/CellMonthly.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderMonthly/HeaderMonthly.tsx
Fix the aligned in 1920 dimensions
> Fix the header aliged

- .vscode/settings.json
- next-env.d.ts
- src/core/utils/dictionary.js
- src/stories/components/SingleItemSelect/SingleItemSelect.tsx
- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChartFilter/BreakdownChartFilter.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChartSection.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/useBreakdownChart.ts
- src/stories/containers/Finances/components/BreakdownChartSection/utils.ts
- src/stories/containers/Finances/components/DelegateExpenseTrend/DelegateExpenseTrendItem.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/CardChartOverview.stories.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/CardChartOverview.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/utils.ts
- src/stories/containers/Finances/components/SectionPages/ExpenseReports/ExpenseReportsFilters.tsx
- src/stories/containers/Finances/components/SectionPages/ExpenseReports/useExpenseReports.tsx
- src/stories/containers/Finances/utils/types.ts
- src/stories/containers/Finances/utils/utils.ts
- tsconfig.json
Update the types to make the code more robust
> [BSN-1] Improve types on Finances page

- src/core/utils/humanization.ts
- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/utils.ts
Fix small number in the axis X
> [RC-1] Add suffix for negatives values and fix start point

- src/stories/containers/Finances/useFinances.tsx
The "Load more" button on the navigation cards on mobile wasn;t showing up due a wrong caching of the level status of cards number
> [BSN-1] Fix "load more" button on mobile

- src/stories/containers/Finances/api/queries.ts
- src/stories/containers/RecognizedDelegates/api/RecognizedDelegatesAPI.ts
The analytic query changed its structure
> [QC] Fix analytics breaking change

- src/stories/containers/Finances/components/SectionPages/BreakdownTable/BreakdownTable.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/BreakdownTableSkeleton/BreakdownTableBodySkeleton/BreakdownTableBodySkeleton.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/BreakdownTableSkeleton/BreakdownTableBodySkeleton/HeaderRowSkeleton.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/BreakdownTableSkeleton/BreakdownTableBodySkeleton/RowSkeleton.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/BreakdownTableSkeleton/BreakdownTableSkeleton.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/BreakdownTableSkeleton/HeaderBreakdownTableSkeleton.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/BreakdownTableSkeleton/HeaderTitleSkeleton.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/BreakdownTableSkeleton/ItemHeaderSkeleton.tsx
Add loading state of the table for small resolution
> [BSN-1] Add loading state for the table version mobile

- src/stories/containers/ActorProjects/components/ViewAllButton/ViewAllButton.tsx
- src/stories/containers/RoadmapMilestones/RoadmapMilestonesContainer.tsx
> [RMV-1] Fix RMV issues

- .github/workflows/chromatic.yaml
- src/stories/components/CustomBarChart/CustomBarChart.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Cards/ExpensesComparisonRowCard/ExpensesComparisonRowCard.tsx
- src/stories/containers/TransparencyReport/components/TransparencyForecast/useTransparencyForecast.tsx
> [QC] Fix QC issues

- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
When the finances page viewport is resized the we were adding the metrics, period and hash to the url
> [BSN-1] Fix mobile resize changes url

- src/stories/containers/Finances/components/LineYearBorderBottomChart/LineYearBorderBottomChart.tsx
- src/stories/containers/Finances/components/ReservesWaterfallFilters/ReservesWaterfallFilters.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/ReservesWaterfallChartSection.stories.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/ReservesWaterfallChartSection.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/utils.ts
- src/stories/containers/Finances/components/WaterfallChart/WaterfallChart.tsx
Fix the align in the waterfall chart and fix stories
> [RC-1] Fix/water fall align filter icons

- pages/endgame/index.tsx
- src/stories/containers/Endgame/Endgame.stories.tsx
- src/stories/containers/Endgame/EndgameContainer.tsx
- src/stories/containers/Endgame/components/BudgetDoughnutChart/BudgetDoughnutChart.tsx
- src/stories/containers/Endgame/components/BudgetStructureSection/BudgetStructureSection.tsx
- src/stories/containers/Endgame/components/TotalBudgetContent/TotalBudgetContent.tsx
- src/stories/containers/Endgame/useEndgameContainer.ts
- src/stories/containers/Finances/api/queries.ts
https://trello.com/c/ERuAdkUG/292-met-13-detailed-insight-into-endgame-budget-structure
Integrate the Budget structure with the API
> [MET-1] Integrate budget structure with api

- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/utils.ts
Not-ticket
Fix the waterfall data, check the index in the array before to access
> [No-ticket] Check that index exist before sum

- src/core/models/interfaces/analytic.ts
- src/stories/containers/Finances/api/queries.ts
- src/stories/containers/Finances/components/SectionPages/ExpenseReports/ExpenseReports.tsx
- src/stories/containers/Finances/utils/mockData.ts
- src/stories/containers/Finances/utils/types.ts
- src/stories/containers/Finances/utils/utils.ts
Fix analytics in the table, its got tow years
> [SB-1]Fix/issues table got two analitycs

- pages/endgame/index.tsx
- src/stories/containers/Endgame/Endgame.stories.tsx
- src/stories/containers/Endgame/EndgameContainer.tsx
- src/stories/containers/Endgame/components/BudgetDoughnutChart/BudgetDoughnutChart.tsx
- src/stories/containers/Endgame/components/BudgetStructureSection/BudgetStructureSection.tsx
- src/stories/containers/Endgame/components/BudgetTransitionChart/BudgetTransitionChart.tsx
- src/stories/containers/Endgame/components/BudgetTransitionStatusSection/BudgetTransitionStatusSection.stories.tsx
- src/stories/containers/Endgame/components/BudgetTransitionStatusSection/BudgetTransitionStatusSection.tsx
- src/stories/containers/Endgame/components/TransitionDataPicker/TransitionDataPicker.tsx
- src/stories/containers/Endgame/types.ts
- src/stories/containers/Endgame/useEndgameContainer.ts
https://trello.com/c/K6BCBa9u/293-met-14-visualization-of-budget-transition-status
Integrate the Transition Status section of the endgame page with the API
> [MET-1] Integrate transition status with API

- src/stories/containers/Finances/utils/utils.ts
Fix the values in the last level of budgets.
Right now the last level of the budgets don't show correct values, because there aren't any subbudget but its have values that need to be show
> fix:Fix the last level card overview don't show values

- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
Fix the values in the header  for the last level
Right now the  in the last level the table don't show correct values because don't have any subBudget
> [BS-1] Fix table don't show values in the last level in the header

- src/stories/containers/Endgame/components/BudgetTransitionChart/BudgetTransitionChart.tsx
- src/stories/containers/Endgame/components/TransitionDataPicker/TransitionDataPicker.tsx
- src/stories/containers/Endgame/types.ts
Changed the actuals by payment on chain metric
> [QA] Change actuals metric in endgame page

- src/stories/containers/Endgame/components/BudgetStructureSection/BudgetStructureSection.tsx
Update budget structure subtitle in the endgame page
> [QA] Update update structure subtitle

- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/useReservesWaterfallChart.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/utils.ts
Fix the filter in the waterfall chart has the  wrong number to start The values to start the chart its only correct when all the budgets are select, The filter don't recalculate
> [SB-1] Fix the filter waterfall chart

- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/CardLegend.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/ItemLegendDoughnut.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
Fix the number items that should show to get better approach of the space.
At the moment the items display but some cases don't got the correct space
- [X The pie chart legend should be displayed properly covering the space. **Current Output:** The elements are displayed in a block of three not covering the space.**Visual Proof:
> fix:Fix the way items in the  legend of the doughnut chart are display

- src/core/enums/zIndexEnum.ts
Fix zindex in the tooltips
Remove the big zIndex in the tooltip
> Fix the zIndex

- .github/workflows/staging-deploy.yaml
Run the staging deploy every day automatically at midnight
> [QC] Run staging deploy everyday at midnight

- src/stories/containers/Endgame/EndgameContainer.tsx
- src/stories/containers/Endgame/components/KeyChangesBudgetTransitionStatusSection/KeyChangesBudgetTransitionStatusSection.tsx
- src/stories/containers/Endgame/components/KeyChangesSections/KeyChangesSections.tsx
- src/stories/containers/Endgame/components/NavigationTabs/NavigationTabs.tsx
Moved a paragraph to the end of the page
> [QA] Move key changes line to the bottom

- src/stories/components/CustomMultiSelect/CustomMultiSelect.tsx
- src/stories/components/CustomSortSelect/CustomSortSelect.tsx
- src/stories/components/ResetButton/ResetButton.tsx
- src/stories/components/SearchInput/SearchInput.tsx
- src/stories/components/SingleItemSelect/SingleItemSelect.tsx
- src/stories/containers/ActorProjects/components/ProjectFilters/ProjectFilters.tsx
- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/BreadcrumbWithYear/BreadcrumbWithYear.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChartFilter/BreakdownChartFilter.tsx
- src/stories/containers/Finances/components/FiltersTable/FilterTable.tsx
- src/stories/containers/Finances/components/ReservesWaterfallFilters/ReservesWaterfallFilters.tsx
- src/stories/containers/Finances/components/SectionPages/BreadcrumbYearNavigation.tsx
- src/stories/containers/Finances/components/SectionPages/ExpenseReports/ExpenseReportsFilters.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/TitleFilterComponent.tsx
> [QA] Reduce paddings and sizes

- src/stories/containers/Finances/components/CardNavigationFinance/CardNavigationFinance.tsx
Move the code below the title if the code is lower case, has dashes and it is not uppercase, or if it is in camelCase format
> [QA] Move code below title

- src/stories/components/Breadcrumbs/Breadcrumbs.tsx
- src/stories/components/Breadcrumbs/CustomBreadcrumbs/CustomBreadcrumbs.tsx
- src/stories/components/CoreUnitSummary/CoreUnitSummary.tsx
https://trello.com/c/nGHZjl06/347-apply-changes-to-breadcrumb-and-dropdown-components
Reduced size of the
> Reduce breadcrumb size

- src/stories/components/IconTitle/IconTitle.tsx
- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/useFinances.tsx
Add a title description and reduce title font size
> [QA] Add title description

- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/utils.ts
> [BSN-1] Fix when there its not analytics but there are budgets

- src/stories/containers/ActorsAbout/components/ActorSummary/ActorTitleAbout.tsx
- src/stories/containers/ActorsAbout/components/ActorSummary/ActorTitleWithDescription.stories.tsx
https://trello.com/c/3EWKzArO/343-user-story-eat-21-ecosystem-actors-short-code
Add the code in the ecosystem actor page
> [EAT-21] Add code actor about page

- src/stories/components/Header/Header.tsx
- src/stories/components/Header/menuItems.ts
- src/stories/components/TopBarSelect/TopBarSelect.tsx
The main page( Landing page) should not have “Finances” highlighted.
> [QA-338] Remove highlighted finances when you are in the root

- src/stories/containers/Finances/components/BreakdownChartSection/utils.ts
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
- src/stories/containers/Finances/utils/utils.ts
Add missing values to prevent incorrect values
> [BSN] Fix missed budget on analytics

- src/stories/containers/Finances/components/ReservesWaterfallFilters/ReservesWaterfallFilters.tsx
https://trello.com/c/GsCTRmy1/352-change-requests-sprint-review-v1
Add the brackets to categories filters in waterfall
> [QA-352] Add parentis to categories filters

- src/stories/containers/Actors/ActorsContainer.tsx
- src/stories/containers/Actors/components/ActorHeader/ActorsHeaderTable.tsx
- src/stories/containers/Actors/components/ActorItem/ActorItem.stories.tsx
- src/stories/containers/Actors/components/ActorItem/ActorItem.tsx
- src/stories/containers/Actors/components/ActorItem/GroupedScopes.tsx
- src/stories/containers/Actors/components/ActorLastModified/ActorLastModified.tsx
- src/stories/containers/Actors/components/ActorTable/ActorTable.tsx
- src/stories/containers/Actors/useActors.ts
https://trello.com/c/3EWKzArO/343-user-story-eat-21-ecosystem-actors-short-code
Add the responsive for the actors list
> [ETA-21] Add responsive for the table actor page

- src/stories/containers/ActorsAbout/components/ActorSummary/ActorTitleAbout.tsx
- src/stories/containers/ActorsAbout/components/ActorSummary/ActorTitleWithDescription.stories.tsx
https://trello.com/c/TJJadCh4/345-user-story-eat-22-ecosystem-actors-status-indication
This add status indicator in the ecosystem actor
> [EAT-22] Feature/add ecosystem actors status indication about page

- src/stories/containers/Actors/components/ActorItem/ActorItem.tsx
https://trello.com/c/3EWKzArO/343-user-story-eat-21-ecosystem-actors-short-code
Fix the align in the code and name ecosystem actor
> [ETA-21] Fix the lineHeight code

- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/InformationBudgetCapOverView/InformationBudgetCapOverView.tsx
- src/stories/containers/Finances/components/OverviewCardMobile/OverviewCardMobile.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/CardChartOverview.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
Change actuals metric by net expenses on chain
> Change actuals by net expenses on chain

- src/stories/containers/ActorsAbout/components/ActorSummary/ActorTitleAbout.tsx
- src/stories/containers/RecognizedDelegates/RecognizedDelegates.stories.tsx
Fix the stories in delegate page
> [SR-362-]Fix stories in delegate and add minWith for the ecosystem actor

- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
Fix metric flickering when the amount of metric to be shown is bigger than the previous amount of metric selected previously with the previous period
> Fix metrics flickering on period change on breakdown table

- src/stories/containers/Actors/components/ActorItem/ActorItem.tsx
- src/stories/containers/ActorsAbout/components/ActorSummary/ActorTitleAbout.tsx
https://trello.com/c/TJJadCh4/345-user-story-eat-22-ecosystem-actors-status-indication
Change the status
> [EAT-22] Add default status for accepted

- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
Add missing values to the table when there are path in the analytics that doesn't match with any budget
> Add missing path data to breakdown table

- src/core/utils/colors.ts
- src/stories/containers/Actors/ActorsContainer.tsx
- src/stories/containers/Actors/components/ActorFilters/ActorFilters.tsx
- src/stories/containers/Actors/components/ActorFilters/utils.ts
- src/stories/containers/Actors/components/ScopeChip/ScopeChip.tsx
- src/stories/containers/Actors/useActors.ts
- src/stories/containers/Actors/utils/utils.ts
https://trello.com/c/VfuGwh20/370-user-story-eat-23-ecosystem-actors-scope-filter
Add new filter in ecosystem actor
> [ETA-23] Add the scope filter to ecosystem actors

- src/stories/containers/Actors/components/ActorFilters/ActorFilters.tsx
https://trello.com/c/VfuGwh20/370-user-story-eat-23-ecosystem-actors-scope-filter
Should implement the responsive view.
> [ETA-23] Fix the size of the popover

- src/stories/containers/Finances/FinancesContainer.tsx
Change first level description
> [QA] Change first level description

- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/utils.ts
This remove the row when the values are cero
> [QA-376] Add condition when values are cero don't show values

- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/ReservesWaterfallFilters/ReservesWaterfallFilters.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/ReservesWaterfallChartSection.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/useReservesWaterfallChart.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/utils.ts
The finish value and the start value of the next year didn't match in the reserves chart. Now it is fixed
> [QA] Reserves finish and start match

- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/useMakerDAOExpenseMetrics.tsx
The data for actuals, net on chain, and net outflow is not represented for future dates in the current year when monthly or quarterly granularities are selected
> [QA] Show data from past dates only in the expenses metrics chart for certain metrics

- src/stories/components/SingleItemSelect/SingleItemSelect.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/CumulativeFilter/CumulativeFilter.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/CumulativeFilter/CumulativeSelectItem.tsx
https://trello.com/c/tnG3VXBf/373-user-story-eml-21-cumulative-metric-check-for-expense-line-chart
> [EML] Cumulative filter dark mode

- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/CumulativeFilter/CumulativeSelectItem.tsx
> [QA] Fix change absolute icon

- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/CardNavigationMobile/CardNavigationMobile.tsx
- src/stories/containers/Finances/components/SectionPages/CardsNavigation/CardsNavigation.tsx
- src/stories/containers/Finances/useFinances.tsx
- src/stories/containers/FinancesOverview/components/HorizontalBudgetBar/HorizontalBudgetBar.tsx
> [QA] Fix mobile card progress bar

- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChartSection.tsx
- src/stories/containers/Finances/components/BreakdownTableFinances/BreakdownTableFinances.tsx
- src/stories/containers/Finances/components/ReservesWaterfallFilters/ReservesWaterfallFilters.tsx
- src/stories/containers/Finances/components/SectionPages/ExpenseReports/ExpenseReports.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/CumulativeFilter/CumulativeSelectItem.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/TitleFilterComponent.tsx
> [QA] Change tooltip copies

- src/stories/containers/Endgame/components/LatestUpdatesSection/LatestUpdatesSection.tsx
https://trello.com/c/ikyCL3Ex/393-user-story-met-15-endgame-latest-updates
Remove an "important" link
> hotfix: remove link

- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
https://trello.com/c/hjoZ54Mk/404-apply-changes-to-the-uncategorized-row-in-the-breakdown-table
Make the uncategorized budgets a suitable with multiple items if there are more than 1 uncategorized budget
> [QA] Fix uncategorized table with sub items

- src/core/utils/sort.ts
- src/stories/containers/Endgame/components/BudgetDoughnutChart/BudgetDoughnutChart.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/CardLegend.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
https://trello.com/c/o63AJUnq/410-sort-budgets-by-size-in-finances-and-endgame-views
Order the legend in the pie chart for the heights values
Sort budgets by size in Finances and Endgame views
> [QA-410] Order the legend by value in the pie chart in Finances Page

- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/utils.ts
https://trello.com/c/8LDv5Kvw/411-missing-data-in-the-reserves-chart
Missing data in the Reserves Chart
> [QA-411] Fix the return condition when total have some value

- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
No ticket
Fix the problem  in the uncategorized in the legacy
> [No- ticket] Add check when there its no rows[0]

- src/components/Card/Card.tsx
- src/components/index.ts
- src/stories/containers/Endgame/components/LatestUpdatesSection/LatestUpdatesSection.tsx
- src/stories/containers/Endgame/components/LatestUpdatesSection/PhaseCard.tsx
- src/stories/containers/Endgame/components/SectionHeader/SectionHeader.tsx
- src/views/Endgame/EndameView.tsx
- styles/theme/shadows.ts
- styles/theme/themes.ts
- tsconfig.json
https://trello.com/c/QXFAyAbF/425-apply-reskin-design-to-the-first-section-met
Created a generic card component, added shadows to the theme and more.
> [MET] Latest update reskin

- src/stories/containers/Endgame/Endgame.stories.tsx
- src/stories/containers/Endgame/components/EndgameIntroductionBanner/EndgameIntroductionBanner.tsx
https://trello.com/c/04eKxJok/426-apply-reskin-design-to-the-key-changes-section-met
> [Reskin-426] Correct the error and add the new section to storybook

- src/stories/containers/Endgame/components/KeyChangeSection/KeyChangeSection.tsx
- src/stories/containers/Endgame/components/KeyChangesSections/KeyChangesSections.tsx
- src/stories/containers/Endgame/components/TransitionHeader/TransitionHeader.tsx
https://trello.com/c/04eKxJok/426-apply-reskin-design-to-the-key-changes-section-met
Apply reskin styles to part of the key changes accordions section
> [MET] Key changes accordion reskin

- src/core/utils/typesHelpers.ts
- src/stories/containers/Endgame/components/KeyChangeCard/KeyChangeCard.tsx
- src/stories/containers/Endgame/components/KeyChangeSection/KeyChangeSection.tsx
- src/stories/containers/Endgame/components/KeyChangesSections/KeyChangesSections.tsx
- src/stories/containers/Endgame/components/KeyChangesSections/Sections/GovernanceSection.stories.tsx
- src/stories/containers/Endgame/components/KeyChangesSections/Sections/OperationsSection.stories.tsx
- src/stories/containers/Endgame/components/KeyChangesSections/Sections/TokenUpgradesSection.stories.tsx
https://trello.com/c/04eKxJok/426-apply-reskin-design-to-the-key-changes-section-met
Update the key changes remaining section with the new reskin styles
> [MET] Key changes reskin

- src/components/ExternalLinkButton/ExternalLinkButton.stories.tsx
- src/components/ExternalLinkButton/ExternalLinkButton.tsx
> [Reskin:432] Add the hover in the external link button

- src/components/InternalLinkButton/InternalLinkButton.stories.tsx
- src/components/InternalLinkButton/InternalLinkButton.tsx
- src/stories/containers/Endgame/components/EndgameIntroductionBanner/EndgameIntroductionBanner.tsx
> [Reskin-432] Fix the color in the key sections

- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
https://trello.com/c/wisPOY1d/442-missing-values-in-the-breakdown-table
> [QA] Fix missing values in the breakdown table

- src/components/SESTooltip/TooltipModalVariant.tsx
- src/stories/components/SESTooltipLegacy/ModalBottomSheetLegacy.tsx
- src/stories/components/SESTooltipLegacy/SESTooltipLegacy.tsx
- src/stories/components/SESTooltipLegacy/TooltipModalVariantLegacy.tsx
- src/views/Endgame/components/BudgetTransitionChart/BudgetTransitionChart.tsx
- src/views/Endgame/components/BudgetTransitionStatusSection/BudgetTransitionStatusSection.tsx
> [Reskin-432] Add style for mobile view in tooltip add deprecate for legacy component

- src/views/Endgame/components/LatestUpdatesSection/LatestUpdatesSection.tsx
https://trello.com/c/QXFAyAbF/425-apply-reskin-design-to-the-first-section-met
Add an important link to all the phases of the latest updates in the endgame page
> [MET] Add more important links

- src/views/Endgame/components/BudgetTransitionChart/BudgetTransitionChart.tsx
- src/views/Endgame/components/BudgetTransitionStatusSection/BudgetTransitionStatusSection.stories.tsx
> Fix the stories and fix format in mobile

- src/components/StatusChip/StatusChip.stories.tsx
- src/components/StatusChip/StatusChip.tsx
- src/components/StatusChip/useCustomColors.tsx
- src/core/businessLogic/__tests__/coreUnits.tests.ts
- src/core/businessLogic/builders/cuAbout/cuMIPBuilder.ts
- src/core/businessLogic/builders/cuMIPBuilder.ts
- src/core/businessLogic/builders/mip40Builder.ts
- src/core/businessLogic/coreUnitAbout.ts
- src/core/businessLogic/coreUnits.ts
- src/core/models/dto/coreUnitDTO.ts
- src/core/models/interfaces/cuMip.ts
- src/core/models/interfaces/types.ts
- src/core/utils/storybook/mocks/coreUnitsMocks.ts
- src/stories/components/CuTableColumnSummary/CuTableColumnSummary.tsx
- src/stories/components/RelateMips/RelateMips.tsx
- src/stories/components/StatusChipLegacy/StatusChipLegacy.stories.tsx
- src/stories/components/StatusChipLegacy/StatusChipLegacy.tsx
- src/stories/components/TitleNavigationCuAbout/TitleNavigationCuAbout.stories.tsx
- src/stories/containers/ActorsAbout/components/ActorSummary/ActorTitleAbout.tsx
- src/stories/containers/CUAbout/useCuAbout.ts
- src/stories/containers/CUTable/cuTableFilters.tsx
- src/stories/containers/CUTable/useCoreUnitsTable.ts
- src/views/Actors/components/ActorItem/ActorItem.tsx
> [Reskin-441] Add new style for the rows and fix the test

- src/views/Endgame/components/EndgameIntroductionBanner/EndgameIntroductionBanner.stories.tsx
- src/views/Endgame/components/EndgameIntroductionBanner/EndgameIntroductionBanner.tsx
This fix the style of the link text in the endgame page
> [No-ticket] Fix the style in the keys change sections

- src/views/Actors/components/ActorLastModified/ActorLastModified.tsx
> [Reskin] Add new style for last modified

- src/components/ButtonLink/ButtonLinkOptions.stories.tsx
- src/components/ButtonLink/ButtonLinkOptions.tsx
- src/components/icons/LinkSvg.tsx
- src/views/Actors/components/ActorItem/ActorItem.tsx
> [Reskin-441] Add link button for actor-item

- src/views/Actors/ActorsContainer.stories.tsx
Move the actor page to the fusion folder
> [Reskin-441] Move the actor page to fusion

- src/views/Endgame/components/BudgetStructureSection/BudgetStructureSectionSkeleton.tsx
https://trello.com/c/ySUDvo2c/431-apply-reskin-design-to-the-endgame-budget-structure-section-met
> [Reskin-431] Fix the comments in the loading state

- src/components/CustomSelect/CustomSelect.tsx
https://trello.com/c/UGndl7pm/446-create-a-reusable-year-component-for-the-endgame-view
> fix: solved the CustomSelect component selection status

- src/components/ButtonLink/ButtonLinkOptions.tsx
- src/components/InternalLinkButton/InternalLinkButton.tsx
- src/components/RoleChip/RoleChip.tsx
- src/components/ScopeChip/ScopeChip.tsx
- src/components/StatusChip/StatusChip.tsx
- src/views/Actors/ActorsContainer.stories.tsx
- src/views/Actors/components/ActorItem/ActorItem.stories.tsx
- src/views/Actors/components/ActorItem/ActorItem.tsx
- src/views/Actors/components/ActorLastModified/ActorLastModified.tsx
- src/views/Actors/components/LinkList/ItemLinkList.tsx
- src/views/Actors/components/LinkList/LinkList.tsx
- src/views/Actors/components/LinkList/useLinks.tsx
- src/views/Actors/components/PopoverListLinks/PopoverListLinks.tsx
- src/views/Actors/useActors.ts
> [Reskin-441] Add icons for navigations and show list of links in actor item

- src/core/utils/dictionary.js
- src/views/Endgame/components/BudgetDoughnutChart/BudgetDoughnutChart.tsx
https://trello.com/c/ySUDvo2c/431-apply-reskin-design-to-the-endgame-budget-structure-section-met
> [Reskin-432] Add the hover and delete the tooltip

- src/components/StatusChip/StatusChip.tsx
- src/views/Actors/components/ActorItem/ActorItem.stories.tsx
- src/views/Actors/components/ActorItem/ActorItem.tsx
- src/views/Actors/components/LinkList/ItemLinkList.tsx
> Add responsive in small resolutions

- src/stories/containers/CUTable/useCoreUnitsTable.ts
https://trello.com/c/BPXYIA1X/452-update-query-cu-ea-teams
> [Update-452] Add correct order in the cu

- src/views/Actors/useActors.ts
https://trello.com/c/BPXYIA1X/452-update-query-cu-ea-teams
> [Update-452] Remove the comments

- src/core/utils/string.ts
- src/stories/containers/ActorsAbout/ActorAboutContainer.tsx
- src/stories/containers/ActorsAbout/utils.ts
https://trello.com/c/8xXvI1fA/454-ea-about-finances-button-links-to-the-wrong-level
> [EA-454] Avoid break the ui when there is not budgetPath

- src/components/CustomSelect/CustomSelect.tsx
- src/components/CustomSelect/useCustomSelect.ts
- src/components/FiltersBundle/FilterDesktop.tsx
- src/components/FiltersBundle/FiltersBundle.stories.tsx
- src/components/FiltersBundle/FiltersBundle.tsx
- src/components/FiltersBundle/defaults/SelectAsList.tsx
- src/components/FiltersBundle/types.ts
- src/components/FiltersBundle/useFiltersBundle.ts
> [Reskin-450] update the filter component

- src/components/Footer/Footer.stories.tsx
- src/components/Footer/Footer.tsx
- src/components/Footer/FooterContact.tsx
- src/components/Footer/data.ts
https://trello.com/c/WXdC6g15/453-update-the-storybook-structure
> [Reskin-453] Should integrate the Footer with the Figma image.

- src/components/FiltersBundle/FilterDesktop.tsx
- src/components/FiltersBundle/FilterMobile.tsx
- src/components/FiltersBundle/FilterTablet.tsx
- src/components/FiltersBundle/FiltersBundle.stories.tsx
- src/components/FiltersBundle/FiltersBundle.tsx
- src/components/FiltersBundle/FiltersList.tsx
- src/components/FiltersBundle/types.ts
> [Fix-450] implement the funtionality for the filters

- src/components/FiltersBundle/FilterDesktop.tsx
- src/components/FiltersBundle/FilterMobile.tsx
- src/components/FiltersBundle/FilterTablet.tsx
- src/components/FiltersBundle/FiltersBundle.stories.tsx
- src/components/FiltersBundle/types.ts
- src/components/FiltersBundle/useFiltersBundle.ts
- src/components/Search/Search.tsx
- src/system/Colors.stories.mdx
- src/system/Iconography.stories.mdx
- src/system/icons.tsx
- src/views/Actors/ActorsContainer.stories.tsx
- src/views/Actors/ActorsContainer.tsx
- src/views/Actors/components/ActorHeader/ActorsHeaderTable.tsx
- src/views/Actors/components/ActorItem/ActorItem.tsx
- src/views/Actors/components/ActorTable/ActorTable.tsx
- src/views/Actors/components/LinkList/ItemLinkList.tsx
- src/views/Actors/useActors.tsx
- src/views/Actors/utils/utils.ts
https://trello.com/c/WXdC6g15/453-update-the-storybook-structure
> [Update-453] Add match page actors with figma

- src/components/Footer/Footer.tsx
- src/components/Footer/data.ts
- src/stories/components/Container/PageContainer.tsx
- src/system/Colors.stories.mdx
- src/system/Iconography.stories.mdx
https://trello.com/c/gES3hIR8/468-implement-footer-change-in-large-resolutions
> [Change-468] Fix the icons story and add links to cookies policy

- .dockerignore
- .env.example
- .vscode/settings.json
- Dockerfile
- README.md
- docker-compose.yml
- next.config.js
- package.json
- yarn.lock
https://trello.com/c/sHrn0TEo/469-dockerising-the-fusion-deployment
Created dockerfile and docker-compose file to dockerise the app
> [Reskin-469] Dockerize app

- src/core/utils/tests.ts
- src/stories/components/CoreUnitCard/CoreUnitCard.tsx
- src/views/CoreUnits/CuRenderLinks/CuRenderLinks.tsx
- src/views/CoreUnits/CuTableColumnSummary/CuTableColumnSummary.tsx
- src/views/CoreUnits/CuTableColumnTeamMember/CuTableColumnTeamMember.tsx
- src/views/CoreUnits/CuTableRenders.tsx
- src/views/CoreUnits/CustomTable/CustomTable.stories.tsx
- src/views/CoreUnits/CustomTable/ItemCoreUnit/ItemCoreUnit.stories.tsx
- src/views/CoreUnits/CustomTable/ItemCoreUnit/ItemCoreUnit.tsx
- src/views/CoreUnits/CustomTable/list-core-unit/list-core-unit.stories.tsx
- src/views/CoreUnits/useCoreUnitsTableView.tsx
> [Reskin-440] Add responsive for all resolutions

- src/components/StatusChip/StatusChip.tsx
- src/stories/components/CustomBarChart/CustomBarChart.tsx
- src/views/CoreUnits/CuTableColumnExpenditures/CuTableColumnExpenditures.tsx
- src/views/CoreUnits/CuTableColumnSummary/CuTableColumnSummary.tsx
- src/views/CoreUnits/CuTableColumnTeamMember/CuTableColumnTeamMember.tsx
- src/views/CoreUnits/CustomTable/ItemCoreUnit/ItemCoreUnit.stories.tsx
- src/views/CoreUnits/FilterItems/CustomStatusItemFilter.tsx
- src/views/CoreUnits/components/ToolTips/ActualsTooltip.tsx
- src/views/CoreUnits/components/ToolTips/ToolTips.tsx
- src/views/CoreUnits/useCoreUnitsTableView.tsx
> [WIP-440] Add tooltip for summary and fts

- src/components/Breadcrumb/Breadcrumb.stories.tsx
- src/components/Breadcrumb/Breadcrumb.tsx
- src/components/Breadcrumb/DotsSegment.tsx
https://trello.com/c/YiRim70Y/448-create-a-reusable-breadcrumb-for-cu-ea
Complete the stories for the breadcrumb
> [Reskin-448] Complete breadcrumb stories

- src/views/CUAbout/CuAboutView.stories.tsx
- src/views/CUAbout/CuAboutView.tsx
- src/views/CUAbout/NavigationCard/CardExpenses.tsx
- src/views/CUAbout/NavigationCard/CardSomethingWrong.tsx
- src/views/EAAbout/EAAboutView.tsx
> [Reskin 447 ]Apply reskin design to the cu ea about Something wrong card

- pages/teams/index.tsx
- src/core/models/interfaces/types.ts
- src/core/utils/dictionary.js
- src/views/Teams/Teams.stories.tsx
- src/views/Teams/TeamsView.tsx
- src/views/Teams/api/queries.ts
- src/views/Teams/components/TeamTypeCard/TeamTypeCard.stories.tsx
- src/views/Teams/components/TeamTypeCard/TeamTypeCard.tsx
- src/views/Teams/components/TeamsSections/TeamsSections.tsx
- src/views/Teams/useTeamView.ts
https://trello.com/c/ABVTtGBd/482-tgp-11-teams-categories-section
Implemented the Teams page
> [TGP-1] Created teams page with all its components

- src/views/Teams/TeamsView.tsx
https://trello.com/c/ABVTtGBd/482-tgp-11-teams-categories-section
> [TGP-1] Add teams SEO

- src/components/ButtonLink/SocialMediaLinksButton.tsx
- src/components/RoleChip/RoleChip.tsx
- src/components/StatusChip/StatusChip.tsx
- src/components/TeamHeader/TeamHeader.tsx
- src/views/RoadmapMilestones/components/Breadcrumb/Breadcrumb.tsx
https://trello.com/c/kBkJAOVP/495-chips-from-ecosystem-actors-are-displayed-with-the-wrong-sizes
Fix some edge cases styles in the team header component
> [Reskin-495] Items styles (edge cases)

- pages/budget-statements/[ownerType].tsx
- src/components/TeamHeader/TeamHeader.tsx
- src/views/BudgetStatement/types.ts
- src/views/BudgetStatement/useBudgetStatementView.ts
- src/views/BudgetStatement/utils/index.ts
https://trello.com/c/kBkJAOVP/495-chips-from-ecosystem-actors-are-displayed-with-the-wrong-sizes
Fix chip height in the Team Header
> [Reskin-495] Fix chip height in the CU and EA about pages

- src/views/CUAbout/NavigationCard/CardSomethingWrong.stories.tsx
- src/views/CUAbout/NavigationCard/CardSomethingWrong.tsx
- src/views/EAAbout/components/InlineUser/InlineUser.stories.tsx
> [Reskin-447] Add Something wrong card

- src/views/CUAbout/RelateMips/RelateMips.stories.tsx
- src/views/CUAbout/RelateMips/RelateMips.tsx
- src/views/EAAbout/components/CardProjects/CardProjects.stories.tsx
> [Reskin-447] Add StoryBook for mips and project cards

- src/views/CUAbout/RelateMips/RelateMips.stories.tsx
- src/views/CUAbout/RelateMips/RelateMips.tsx
- src/views/EAAbout/components/ActorMdViewer/ActorMdViewPage.tsx
- src/views/EAAbout/components/Auditors/Auditors.stories.tsx
- src/views/EAAbout/components/CardProjects/CardProjects.stories.tsx
- src/views/EAAbout/components/CardProjects/CustomSheetProjects.stories.tsx
- src/views/EAAbout/components/CardProjects/CustomSheetProjects.tsx
- src/views/EAAbout/components/CardProjects/ItemCustomProject.tsx
> [Reskin-447] Stories all cards project mobile

- src/views/CUAbout/Markdown/MdViewerPage.tsx
> [Reskin-447] Fix the space in Markdown

- src/stories/containers/ActorProjects/components/DeliverableCard/DeliverableCard.tsx
- src/stories/containers/ActorProjects/components/ProjectLink/ProjectLink.tsx
Hide the arrow in the project link if there's no link available
> [PH24-1] Remove arrow link

- src/components/ButtonLink/SocialMediaLinksButton.tsx
- src/views/CUAbout/CustomSheetFinances/ItemFinancesSheet.tsx
> [Fix-447] Fix the links component and aling text in finances sheet

- src/views/Actors/components/ActorCustomItem/CustomItemRole.tsx
- src/views/CoreUnits/FilterItems/CustomStatusItemFilter.tsx
> Fix the fontsize

- src/views/BudgetStatement/BudgetStatementView.tsx
- src/views/BudgetStatement/components/BudgetStatementSummary/BudgetStatementSummary.tsx
- src/views/BudgetStatement/useBudgetStatementView.ts
https://trello.com/c/KoM0xita/406-bss-11-budget-statement-pages-for-keepers-legacy-design
Add SEO metadata to the budget statements page. Also added social links
> [BSS-1] Budget statement page SEO

- src/views/Actors/ActorsView.tsx
- src/views/CoreUnits/CoreUnitsView.tsx
https://trello.com/c/16pG9Esv/497-change-background-color-to-the-pages
Fix the CU/EA index background page after the reskin
> [Reskin-497] Fix CU page background

- pages/roadmaps/[slug]/index.tsx
- src/core/models/interfaces/generics.ts
- src/core/models/interfaces/roadmaps.ts
- src/stories/containers/ActorProjects/components/KeyResults/KeyResults.tsx
- src/views/RoadmapMilestones/RoadmapMilestonesView.tsx
- src/views/RoadmapMilestones/api/queries.ts
- src/views/RoadmapMilestones/components/MilestoneCard/MilestoneCard.stories.tsx
- src/views/RoadmapMilestones/components/MilestoneCard/MilestoneCard.tsx
- src/views/RoadmapMilestones/components/MilestoneDetailsCard/Coordinators.tsx
- src/views/RoadmapMilestones/components/MilestoneDetailsCard/DeliverablesSection.tsx
- src/views/RoadmapMilestones/components/MilestoneDetailsCard/MilestoneDetailsCard.stories.tsx
- src/views/RoadmapMilestones/components/MilestoneDetailsCard/MilestoneDetailsCard.tsx
- src/views/RoadmapMilestones/components/MilestoneDetailsCard/MilestoneProgress.tsx
- src/views/RoadmapMilestones/components/MilestoneDetailsCard/StatsData.tsx
- src/views/RoadmapMilestones/staticData.ts
- src/views/RoadmapMilestones/useRoadmapMilestonesView.ts
- src/views/RoadmapMilestones/utils.ts
Integrate the Powerhouse roadmap with the API
> [PH24-1] Integrate roadmaps and milestones page with the API

- src/core/models/interfaces/deliverables.ts
- src/stories/containers/ActorProjects/components/DeliverableCard/DeliverableCard.tsx
- src/stories/containers/ActorProjects/components/ProjectOwnerChip/ProjectOwnerChip.tsx
- src/views/RoadmapMilestones/components/MilestoneDetailsCard/Contributors.tsx
- src/views/RoadmapMilestones/components/MilestoneDetailsCard/Coordinators.tsx
- src/views/RoadmapMilestones/components/MilestoneDetailsCard/DeliverablesSection.tsx
- src/views/RoadmapMilestones/components/MilestoneDetailsCard/MilestoneDetailsCard.tsx
- src/views/RoadmapMilestones/components/MilestoneDetailsCard/StatsData.tsx
- src/views/RoadmapMilestones/components/OwnerAvatarGroup/OwnerAvatarGroup.tsx
- src/views/RoadmapMilestones/components/OwnerAvatarGroup/OwnerTooltipContent.tsx
- src/views/RoadmapMilestones/staticData.ts
Adjust coordinators and contributors in mobile resolutions. Also modified how the title is displayed, and a few more improvements
> [PH24-1] Adjust elements in milestones card in mobile

- src/stories/containers/FinancesOverview/components/EndgameIntroductionBannerLegacy/EndgameIntroductionBannerLegacy.tsx
- src/views/Endgame/components/EndgameIntroductionBanner/EndgameIntroductionBanner.tsx
https://trello.com/c/pXIhu5GF/514-change-the-date-on-the-homepage-and-endgame-views
changed the date in the home page and endgame description
> [Demo-514] Change banner date

- src/stories/containers/ActorProjects/components/KeyResults/KeyResults.tsx
- src/stories/containers/FinancesOverview/components/EndgameIntroductionBannerLegacy/EndgameIntroductionBannerLegacy.tsx
- src/views/Endgame/components/EndgameIntroductionBanner/EndgameIntroductionBanner.tsx
https://trello.com/c/9tsYeo8x/517-add-future-key-results-section-in-the-roadmaps-view
Difference between linkable and no linkable key results
> [Demo-517] No linkable key results

- src/stories/containers/ActorProjects/components/DeliverableCard/DeliverableCard.tsx
- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/BudgetMetricsModal/BudgetMetricsModal.tsx
- src/views/Contributors/ContributorsView.tsx
- src/views/Contributors/staticData.ts
- src/views/RoadmapMilestones/staticData.ts
https://trello.com/c/OBI8WjzU/515-change-finaces-copy
https://trello.com/c/a71S1hUO/516-update-the-descriptions-in-the-contributors-categories-section
Apply some general improvements for next demo
> [Demo] Improvements for next Demo

- src/components/AdvancedInnerTable/AdvancedInnerTable.tsx
- src/components/BudgetStatement/BudgetStatementForecast/BarWithDottedLine.tsx
- src/components/BudgetStatement/BudgetStatementForecast/BarWithDottedLineMobile.tsx
- src/components/BudgetStatement/BudgetStatementForecast/BudgetStatementForecast.tsx
- src/components/BudgetStatement/BudgetStatementForecast/useBudgetStatementForecast.tsx
- src/components/BudgetStatement/BudgetStatementTransferRequest/useBudgetStatementTransferRequest.tsx
- src/components/BudgetStatement/ExpenseReport/useExpenseReport.tsx
- src/views/CoreUnitBudgetStatement/CoreUnitBudgetStatementView.tsx
- src/views/CoreUnitBudgetStatement/components/PopverForecastDescription/PopoverForecastDescription.tsx
- src/views/EcosystemActorBudgetStatement/EcosystemActorBudgetStatementView.tsx
> [Reskin-470]Fix the letter space and change styled in the forecast

- src/components/BudgetStatement/BudgetStatementActuals/TotalWalletSection/TotalWalletSections.stories.tsx
- src/core/businessLogic/tableBuilderColumns.ts
- src/core/businessLogic/tableBuilderRow.ts
> [Reskin-470] Add builder for the table total

- src/components/AdvancedInnerTable/TextCell/TextCell.tsx
- src/components/BudgetStatement/BudgetStatementForecast/BarWithDottedLine.tsx
- src/components/BudgetStatement/BudgetStatementForecast/ForecastBreakdownSection/ForecastBreakdownSection.stories.tsx
- src/components/BudgetStatement/BudgetStatementForecast/HeaderWithIcon/TooltipHeader.tsx
- src/components/BudgetStatement/BudgetStatementForecast/ProgresiveIndicator.tsx
- src/components/BudgetStatement/BudgetStatementForecast/TotalForecastSection/TotalForecastSection.stories.tsx
- src/components/BudgetStatement/BudgetStatementForecast/useBudgetStatementForecast.tsx
- src/views/CoreUnitBudgetStatement/utils/forecastTableHelpers.tsx
https://trello.com/c/JUvtoViK/476-reskin-budget-statements-cu-ea-forecast-tab
> [Reskin-476] Improve the BarComponent and add total section

- pages/home/index.tsx
- pages/index.tsx
- pages/legacy-home/index.tsx
- src/views/Home/components/HeaderCard/HeaderCard.stories.tsx
- src/views/Home/components/HeaderCard/HeaderCard.tsx
- src/views/Home/components/HeaderCard/useHeaderCard.tsx
https://trello.com/c/kLmYeHAD/536-hom-11-header-image-section
HOM-1.1 Header Image Section
> feat: HOM-1.1 Header Image Section

- src/components/BudgetStatement/BudgetStatementAuditorComments/AuditorCommentCard.tsx
- src/components/BudgetStatement/BudgetStatementAuditorComments/ParticipantRoles.tsx
- src/views/EcosystemActorAbout/components/InlineUser/InlineUser.tsx
https://trello.com/c/jFyvnNDO/500-reskin-budget-statements-cu-ea-comments-tab
Applied reskin Participant Roles component
> [Reskin-500] Reskin participant roles

- src/components/AccountsSnapshot/AccountsSnapshotTabContainer.tsx
https://trello.com/c/1A1BltB6/478-reskin-budget-statements-cu-ea-mkr-vesting-tab
> [Reskin-478] Fix the color and add empty state

- src/components/BudgetStatement/BudgetStatementMkrVesting/useBudgetStatementMkrVesting.tsx
- src/components/BudgetStatement/BudgetStatementTransferRequest/BudgetStatementTransferRequest.tsx
- src/components/BudgetStatement/BudgetStatementTransferRequest/components/TargetValueThreeMonths/TargetValueThreeMonths.tsx
- src/components/BudgetStatement/BudgetStatementTransferRequest/components/TransferRequestSection/TransferRequestSection.stories.tsx
- src/components/BudgetStatement/BudgetStatementTransferRequest/components/TransferRequestSection/TransferRequestSection.tsx
- src/components/BudgetStatement/BudgetStatementTransferRequest/useBudgetStatementTransferRequest.tsx
https://trello.com/c/R6wqimqX/477-reskin-budget-statements-cu-ea-transfer-requests-tab
> [Reskin-477] Add transfer component

- src/components/InternalLinkButton/InternalLinkButton.tsx
- src/views/Contributors/components/TeamTypeCard/TeamTypeCard.tsx
https://trello.com/c/NIAUk1RD/545-apply-interaction-to-the-contributors-page
> [Reskin-545] Add link to the cards contributors

- src/components/AdvancedInnerTable/TransparencyCard/TransparencyCard.tsx
- src/components/BudgetStatement/BudgetStatementTransferRequest/components/TargetValueThreeMonths/TargetValueThreeMonths.tsx
- src/components/BudgetStatement/BudgetStatementTransferRequest/components/TransferRequestSection/TransferRequestSection.stories.tsx
- src/components/BudgetStatement/BudgetStatementTransferRequest/useBudgetStatementTransferRequest.tsx
https://trello.com/c/R6wqimqX/477-reskin-budget-statements-cu-ea-transfer-requests-tab
> [Reskin-447] Fix space icon text

- src/components/BudgetStatement/BudgetStatementTransferRequest/components/TargetValueThreeMonths/TargetValueThreeMonths.tsx
- src/views/CoreUnitsIndex/components/CuTableColumnExpenditures/CuTableColumnExpenditures.tsx
https://trello.com/c/ukLWiU1h/546-make-each-contributors-row-clickable
> Fix the links and add correct space for custom component

- src/stories/components/CoreUnitCard/CoreUnitCard.tsx
- src/views/CoreUnitsIndex/components/CuRenderLinks/CuRenderLinks.tsx
- src/views/CoreUnitsIndex/components/CuTableColumnSummary/CuTableColumnSummary.tsx
- src/views/CoreUnitsIndex/components/CuTableColumnTeamMember/CuTableColumnTeamMember.tsx
- src/views/CoreUnitsIndex/components/CustomTable/CustomTable2.tsx
- src/views/CoreUnitsIndex/components/CustomTable/ItemCoreUnit/ItemCoreUnit.tsx
- src/views/CoreUnitsIndex/components/CustomTable/list-core-unit/list-core-unit.tsx
https://trello.com/c/ukLWiU1h/546-make-each-contributors-row-clickable
> [Reskin-546] Make each contributors row clickable

- .env.example
- .github/workflows/dev-deploy.yaml
- .github/workflows/production-deploy.yaml
- .github/workflows/staging-deploy.yaml
- README.md
- src/core/utils/const.ts
- src/stories/containers/CookiesPolicy/CookiesPolicyContainer.tsx
https://trello.com/c/c2Ma3wNH/550-apply-changes-requested-by-the-techops-team
Fix the env on the actions to include the new variable
> Actions connect variable

- src/components/AdvancedInnerTable/AdvancedInnerTable.tsx
- src/components/AdvancedInnerTable/TransparencyCard/TransparencyCard.tsx
- src/components/AdvancedInnerTable/types.ts
- src/components/BudgetStatement/ExpenseReport/ExpenseReport.tsx
- src/components/BudgetStatement/ExpenseReport/components/ExpenseSection/ExpenseSection.tsx
- src/components/BudgetStatement/ExpenseReport/components/SectionTitle/SectionTitle.tsx
- src/components/Tabs/TabPopover.tsx
> [Reskin-501] Update links core unit index

- src/views/Home/HomeView.tsx
- src/views/Home/components/FinancesBarChart/FinancesBarChart.tsx
- src/views/Home/components/FinancesBarChart/useFinancesBarChart.tsx
- src/views/Home/components/FinancesBarChartCard/FinancesBarChartCard.tsx
HOM-1.2 Finances Homepage Section
> feat: HOM-1.2 Finances Homepage Section

- src/components/Search/Search.tsx
- src/views/Contributors/components/TeamTypeCard/TeamTypeCard.tsx
- src/views/CoreUnitAbout/hooks.ts
- src/views/CoreUnitsIndex/components/CuTableColumnSummary/CuTableColumnSummary.tsx
- src/views/CoreUnitsIndex/components/CustomTable/ItemCoreUnit/ItemCoreUnit.tsx
- src/views/EcosystemActorAbout/hooks.ts
- src/views/EcosystemActorsIndex/components/ActorItem/ActorItem.tsx
- src/views/EcosystemActorsIndex/components/EcosystemActorDescription/EcosystemActorDescription.tsx
- src/views/EcosystemActorsIndex/components/RoleItem/RoleItem.tsx
- src/views/EcosystemActorsIndex/components/ScopeItem/ScopeItem.tsx
- src/views/Endgame/components/SectionHeader/SectionHeader.tsx
https://trello.com/c/7g6oATpI/554-fix-general-issues-in-cu-ea-contributors-endgame-views
> [Fix-554] General issues in CU-EA-Contributors-Endgame views

- src/views/CoreUnitsIndex/components/CustomTable/ItemCoreUnit/ItemCoreUnit.tsx
- src/views/CoreUnitsIndex/useCoreUnitsTableView.tsx
- src/views/EcosystemActorsIndex/useEcosystemActorsIndexView.tsx
https://trello.com/c/7g6oATpI/554-fix-general-issues-in-cu-ea-contributors-endgame-views
> [Reskin] Fix the slow typing in Ecosystem Actor and Core Unit

- src/components/ScopeChip/ScopeChip.stories.tsx
- src/components/ScopeChip/ScopeChip.tsx
- src/components/ScopeChip/useScopeColors.tsx
- src/components/TeamHeader/TeamHeader.tsx
- src/views/EcosystemActorsIndex/components/ActorItem/GroupedScopes.tsx
- src/views/EcosystemActorsIndex/components/ScopeItem/ScopeItem.tsx
- src/views/EcosystemActorsIndex/useEcosystemActorsIndexView.tsx
- styles/theme/colorPalette.ts
> [HOM-14] Contributors homepage update the scope Chip

- src/components/FancyTabs/BulletIcon.tsx
- src/components/FancyTabs/FancyTabs.tsx
- src/views/Home/HomeView.tsx
- src/views/Home/components/Contributors/ContributorsDescription.tsx
- src/views/Home/components/Contributors/ContributorsSection.tsx
- src/views/Home/components/Contributors/TabDescriptions.tsx
- src/views/Home/components/Contributors/useContributorsSection.tsx
> [HOM-539] Add styles tab categories teams and tab description teams

- src/components/FancyTabs/FancyTabs.tsx
- src/components/RoleChip/RoleChip.tsx
- src/components/ScopeChip/ScopeChip.tsx
- src/core/models/interfaces/activity.ts
- src/views/Home/HomeView.tsx
- src/views/Home/components/Contributors/ContributorsDescription.tsx
- src/views/Home/components/Contributors/ContributorsItem.tsx
- src/views/Home/components/Contributors/ContributorsSection.tsx
- src/views/Home/components/Contributors/Profile.tsx
- src/views/Home/components/Contributors/ProfileUpdated.tsx
- src/views/Home/components/Contributors/TabDescriptions.tsx
- src/views/Home/components/Contributors/useContributorsSection.tsx
- src/views/Home/staticData.ts
- src/views/Home/utils/types.ts
- src/views/Home/utils/utils.tsx
> [Home-539]Add styles the details contributors sections

- pages/index.tsx
- src/components/InternalLinkButton/InternalLinkButton.tsx
- src/components/RoleChip/RoleChip.tsx
- src/core/utils/string.ts
- src/views/EcosystemActorsIndex/api/queries.ts
- src/views/Home/Home.stories.tsx
- src/views/Home/HomeView.tsx
- src/views/Home/components/Contributors/ContributorsItem.tsx
- src/views/Home/components/Contributors/ContributorsSection.tsx
- src/views/Home/components/Contributors/GroupScopesContributors.tsx
- src/views/Home/components/Contributors/Profile.tsx
- src/views/Home/components/Contributors/useContributorsSection.tsx
- src/views/Home/staticData.ts
- src/views/Home/utils/utils.tsx
> Add styles for the Details Sections in contributors

- src/components/FancyTabs/ShadowWrapper.tsx
- src/views/Home/components/Contributors/ContributorsSection.tsx
- src/views/Home/components/Contributors/TabDescriptions.tsx
- src/views/Home/components/Contributors/useContributorsSection.tsx
> [Home-539] Fix styles in tab descriptions  in contributors sections

- src/views/Home/api/queries.ts
- src/views/Home/components/FinancesLineChart/FinancesLineChart.tsx
- src/views/Home/components/FinancesLineChartCard/FinancesLineChartCard.stories.tsx
- src/views/Home/components/FinancesLineChartCard/FinancesLineChartCard.tsx
- src/views/Home/components/FinancesLineChartCard/useFinancesLineChartCard.tsx
- src/views/Home/staticData.ts
Improve the mkr vesting data integration and the right side chart
> [HOM-1.2] Improve finances charts in homepage

- src/views/Endgame/components/LatestUpdatesSection/LatestUpdatesSection.tsx
https://trello.com/c/agfvDVR5/557-fix-grammatical-errors-on-the-endgame-page
> [FIX-557] fix-grammatical-errors

- src/views/CoreUnitAbout/components/CustomSheetFinances/ItemFinancesSheet.tsx
https://trello.com/c/gpE4auII/559-fix-redirect-issue-in-core-units-activity-feed-view
> [Fix-559] Add correct router for mobile

- src/views/Home/HomeView.tsx
> Change homepage title

- src/views/Home/components/FinancesBarChart/FinancesBarChart.tsx
- src/views/Home/components/FinancesBarChartCard/FinancesBarChartCard.tsx
- src/views/Home/components/FinancesSection/FinancesSection.tsx
- src/views/Home/utils/utils.tsx
> [ Home-537] Add the tooltip for Bar Chart

- src/views/Home/components/GovernanceSection/ForumOverview/ForumOverview.tsx
- src/views/Home/components/GovernanceSection/ForumPost/ForumPost.tsx
- src/views/Home/components/GovernanceSection/GovernanceSection.tsx
https://trello.com/c/fKv0jCGG/538-hom-13-governance-homepage-section
Implemented the forum section (50%)
> [HOM-1.3] Forum UI implementation (50%)
