makerdao-ses/ecosystem-dashboard

- src/stories/components/markdown/markdown.stories.tsx
- src/stories/components/markdown/md-view-container.tsx
- src/stories/components/markdown/md-view.tsx
- src/stories/components/sidebar/sidebar.tsx
[Trello-20-layout-cu-about](https://trello.com/c/JqoadMnP/20-layout-cu-about)
The "CU About" view will be presented once the user clicks on the "Core Unit -> About" option in 
Change the md-view components to work with text instead of url
> change-md-component-use-text-insted-url

- src/stories/components/core-unit-summary/core-unit-summary.mvvm.ts
- src/stories/components/core-unit-summary/core-unit-summary.tsx
- src/stories/components/cu-table-column-team-member/cu-table-column-team-member.stories.tsx
- src/stories/components/custom-table/custom-table.tsx
- src/stories/containers/cu-table/cu-table.slice.ts
- src/stories/containers/cu-table/cu-table.stories.tsx
- src/stories/containers/cu-table/cu-table.tsx
https://trello.com/c/QJFWbzL0/110-general-issues-detected-in-the-uat-coreunitaboutpage-r
When a user filters on the core unit index table and then clicks into the specific core unit. The filter is not reflected when a user toggles back to the previous, or ahead to the next core unit, so this behavior was changed to reflect the filters
- The ordering logic was moved to redux
- The sorting CU function was moved out of the CU table so it can be reused
- The pagination now works by applying the filters and orderings in the CU table
> [SES-110] Reflect the filter and sorting in the inside pagination of cu about

- pages/core-unit/[code]/finances/reports/index.tsx
- pages/core-unit/[code]/index.tsx
- src/stories/components/core-unit-summary/core-unit-summary.mvvm.ts
- src/stories/components/core-unit-summary/core-unit-summary.tsx
- src/stories/components/markdown/renderUtils.tsx
- src/stories/components/title-navigation-cu-about/title-navigation-cu-about.stories.tsx
- src/stories/components/title-navigation-cu-about/title-navigation-cu-about.tsx
- src/stories/containers/cu-about/cu-about-container.tsx
- src/stories/containers/cu-about/cu-about.stories.tsx
- src/stories/containers/transparency-report/transparency-report.tsx
- src/stories/containers/transparency-report/transpareny-report.stories.tsx
- src/stories/pages/page/cu-about/cu-about.tsx
NO TICKET
Moved all queries previously done on the client side to the Server Side
- Moved queries from core-unit-summary to SSR in CU about page
- Moved queries from core-unit-summary to SSR on CU transparency report page
- Removed `budgetStatements` from the `core-unit-summary` query to reduce the weight of the data fetched
- Apply SSR to the markdown elements in the CU about page
> [SES] Make CU about pages fully SSR

- pages/_app.tsx
- pages/auth/change-password/index.tsx
- pages/auth/create-account/index.tsx
- pages/auth/delete-account/index.tsx
- pages/auth/manage/accounts.tsx
- pages/auth/manage/change-my-password.tsx
- pages/auth/manage/delete-my-account.tsx
- pages/auth/manage/my-profile.tsx
- pages/auth/manage/user/[username]/change-password.tsx
- pages/auth/manage/user/[username]/delete-account.tsx
- pages/auth/manage/user/[username]/index.tsx
- pages/auth/user-profile/index.tsx
- src/core/utils/common-get-ssr-props.ts
- src/stories/containers/users/users-manager/user-manager-layout.tsx
- add concept of `protected` routes to the project
- Redirect to login when the users try to enter to a protected route and they're no authenticated
- Show a forbidden message when the user are authenticated but they're not admins
> [FIX-189] Fix 404 message flicker on auth related routes on refresh

- feature-flags/feature-flags.interface.ts
- src/stories/containers/transparency-report/transparency-report.tsx
- The “Source” link per Expense Report on a monthly basis was removed.
> Removed source link

- src/core/business-logic/builders/budget-statement.builder.ts
- src/core/business-logic/core-units.ts
- src/core/enums/budget-status.enum.ts
- src/core/models/dto/core-unit.dto.ts
- src/stories/containers/cu-about/cu-about-slice.ts
- src/stories/containers/cu-table/cu-table.api.ts
- src/stories/containers/transparency-report/transparency-comments/comment-item.tsx
- src/stories/containers/transparency-report/transparency-report.api.ts
- src/stories/containers/transparency-report/transparency-report.tsx
- Replacing month-specific Source links with a single legacy reporting link
- Update the introduction paragraph
- Fixed breaking changes in the API
> [SES-203] Improve expense report header

- src/core/utils/string.utils.ts
- src/stories/components/cu-activity-table/cu-activity-item.tsx
When some event in the activity feed related to the comments is clicked, the link should go to the relevant CU/BudgetStatement and the comments tab should be active
> [SES-203] New Expense Report Change Tracking Events

- src/stories/containers/transparency-report/transparency-report.mvvm.ts
[No ticket]
Fixed issue in the CU report tabs when changing tabs, the CU was moving to the previous CU
> Fix: CU moving back when changing the budget month

- src/stories/components/cu-activity-table/cu-activity-item.tsx
In the Activity Feed, only the commenting and auditing-related activities should link to the commenting tab.
Technical names:
- CU_BUDGET_STATEMENT_CREATED and CU_BUDGET_STATEMENT_UPDATED
- should navigate to the Actuals tab of the correct month's expense report
- CU_BUDGET_STATEMENT_COMMENT
- should navigate to the Comments tab of the correct month's expense report
> [SES-225] Activity feed linking

- src/stories/containers/cu-activity/cu-activity.tsx
- src/stories/containers/global-activity/global-activity.tsx
- src/stories/containers/transparency-report/transparency-report.tsx
Move the header text to the bottom of the activity feed pages and restore the old text of the transparency report page.
> [SES-225] Feature/improve text header

- src/stories/containers/transparency-report/transparency-auditor-comments/comment-container/auditor-comments-container.tsx
Disable the option to comment when there are no budget statement available to prevent errors
> [SES-QA-231] Disable comments form when there is not budget statement

- src/stories/containers/recognized-delegates/delegates-actuals/useDelegatesActuals.mvvm.ts
- src/stories/containers/recognized-delegates/delegates-forecast/delegates-forecast.tsx
- src/stories/containers/recognized-delegates/delegates-forecast/useDelegatesForeCast.mvvm.ts
- src/stories/containers/transparency-report/transparency-forecast/transparency-forecast-2.mvvm.ts
https://trello.com/c/HoJdcpkZ/242-qa-bug-findings-v-70
- **CoreUnitTransparencyReporting:** Under the expense reports forecast tab- Switch “Monthly Budget” column with “3 Month Forecast”, for all tables. [image.png](https://trello.com/1/cards/63dbc9348e3ca5e5e66b17e5/attachments/63f7322718cb30895efe3745/download/image.png) 
Switched the columns in the transparency report and the delegates page. Updated some column names on the delegates page
> [SES-QA-242] Feature/switch forecast tabs

- src/stories/components/breadcrumbs/breadcrumbs.tsx
- **NC** **Environment:** DEV. **Browser:** All. **Resolution:** All. **Steps to Reproduce:** CUAbout and Expense Reports views. **Expected Output:** The breadcrumb and the elements (number of the core units and navigation icons) displayed on the left side should be aligned. **Current Output:** The breadcrumb and the elements on the left side are misaligned. **Visual Proof:**  [image.png](https://trello.com/1/cards/63dbc95c19102cb39f3e5692/attachments/63fdfd432e13542cb7763962/download/image.png)
> [SES-QC-243] Fix breadcrumbs alignment

- src/stories/components/custom-bar-chart/custom-bar-chart.tsx
- CoreUnitOverview Table The month leters below the budget graph appear in black, and in white when in dark mode. Making it hard to see. **Solution: Make sure the budget graph month letters are legible in dark mode. ** [image.png](https://trello.com/1/cards/63dbc9348e3ca5e5e66b17e5/attachments/63e3628ad6c649e06c8bedf1/download/image.png)
> [SES-256] Fix Bar Chart when there is one value only

- src/stories/containers/transparency-report/transparency-actuals/transparency-actuals-2.tsx
- src/stories/containers/transparency-report/transparency-forecast/transparency-forecast-2.tsx
- src/stories/containers/transparency-report/transparency-mkr-vesting/transparency-mkr-vesting-2.tsx
- src/stories/containers/transparency-report/transparency-report.tsx
- src/stories/containers/transparency-report/transparency-transfer-request/transparency-transfer-request-2.tsx
#What solved
The months area is too closer to the header bottom 
A big space is displayed between the makerburn link and the section below.
The space between the footer and the section above should be the same defined in the design. 
A big space is displayed between the tab and the data below. 
Fix-space-additional-notes
> [SES-254] Fix space transparency report and delegate

- styles/globals.scss
- When pulling the page down on mobile in dark mode, a white area appears. [image.png](https://trello.com/1/cards/63c573b095f58802270f7e2b/attachments/63da3cfa7029e31482f41b1c/download/image.png)
> Prevent scroll bouncing on apple devices

- src/stories/containers/FinancesOverview/components/YearPicker/YearPicker.tsx
- src/stories/containers/FinancesOverview/useFinancesOverview.ts
https://trello.com/c/tqmW07KT/246-feature-delegatestransparencyreporting-v2
- Should add hover styles on the `YearPicker`
- Should ensure that the default year for the Yearly Budget Graph, is the current year
> [SES-246] Improve Finance's YearPicker

- src/core/utils/typesHelpers.ts
- src/stories/components/AdvancedInnerTable/AdvancedInnerTable.tsx
- src/stories/components/NumberCell/NumberCell.tsx
- src/stories/components/TextCell/TextCell.tsx
- src/stories/components/svg/information.tsx
- src/stories/containers/TransparencyReport/components/TransparencyTransferRequest/TransparencyTransferRequest.tsx
- src/stories/containers/TransparencyReport/components/TransparencyTransferRequest/useTransparencyTransferRequest.tsx
- src/stories/containers/TransparencyReport/transparencyReportUtils.tsx
#What solved
Under the existing Transfer Requests Tab, change the column text: "Current Balance” → “31-JAN Balance". This is specific to the expense report, and is derived from the specific data that the report was published. 
Add headers to table
Add new style for data in the column
> Ses 245 feature coreunittransparencyreporting v6 add fiels table

- src/core/utils/typesHelpers.ts
- src/stories/components/CustomPopover/CustomPopover.tsx
- src/stories/containers/TransparencyReport/components/ArrowPopoverTargetValue/ArrowPopoverTargetValueComponent.stories.tsx
- src/stories/containers/TransparencyReport/components/ArrowPopoverTargetValue/ArrowPopoverTargetValueComponent.tsx
- src/stories/containers/TransparencyReport/components/ArrowPopoverTargetValue/ArrowPopoverTargetValueContent.tsx
- src/stories/containers/TransparencyReport/components/TransparencyTransferRequest/useTransparencyTransferRequest.tsx
- src/stories/containers/TransparencyReport/transparencyReportUtils.tsx
#What solved
Should switch the styles of the icon/tooltip to dark on dark mode  Desk
Should add an information tooltip on the "Target balance" column
Add dark mode and other parameter necessary
> [SES-245] : Add dark mode and other parameter necessary

- src/stories/containers/TransparencyReport/components/TransparencyTransferRequest/useTransparencyTransferRequest.tsx
- src/stories/containers/TransparencyReport/transparencyReportUtils.tsx
#What solved
Should align the target balance value to the left In the Transfer Requests tab
Should display in a line the months (Month + Month Budget Cap) in the target balance (834 resolution). 
Add new layout in column target balance
> Add new layout in column target balance

- src/stories/containers/FinancesOverview/FinancesOverviewContainer.stories.tsx
- src/stories/containers/FinancesOverview/components/QuarterCard/QuarterCard.stories.tsx
- src/stories/containers/FinancesOverview/components/QuarterCard/QuarterCard.tsx
- src/stories/containers/FinancesOverview/components/QuarterCarousel/QuarterCarousel.stories.tsx
- src/stories/containers/FinancesOverview/components/QuarterCarousel/QuarterCarousel.tsx
#What solved
The spacing of quarterly expenses card sub-data (eg. ‘actuals’ and ‘cap’) is off.
Add more padding in bigger resolution
> Add more padding in bigger resolution

- pages/index.tsx
- src/core/businessLogic/builders/totalExpenseReportsBuilder.ts
- src/core/models/dto/expensesDTO.ts
- src/core/utils/dictionary.js
- src/core/utils/math.ts
- src/stories/containers/FinancesOverview/FinancesOverviewContainer.stories.tsx
- src/stories/containers/FinancesOverview/FinancesOverviewContainer.tsx
- src/stories/containers/FinancesOverview/api/queries.ts
- src/stories/containers/FinancesOverview/components/CostBreakdownTable/ByBudgetTableRow.tsx
- src/stories/containers/FinancesOverview/components/CostBreakdownTable/ByExpenseCategoryTableRow.tsx
- src/stories/containers/FinancesOverview/components/CostBreakdownTable/CostBreakdownTable.tsx
- src/stories/containers/FinancesOverview/components/CostBreakdownTable/TableFooter.tsx
- src/stories/containers/FinancesOverview/components/NavigationButtons/NavigationButtons.tsx
- src/stories/containers/FinancesOverview/components/RelativeBudgetBar/RelativeBudgetBar.tsx
- src/stories/containers/FinancesOverview/financesOverviewTypes.ts
- src/stories/containers/FinancesOverview/useFinancesOverview.ts
- src/stories/containers/FinancesOverview/utils/costBreakdown.ts
https://trello.com/c/tqmW07KT/246-feature-aggregatedviewlevels-v1
Connect the UI of the Cost Breakdown table on the Finance's page with the API
- Should get the required data from the API on Server Side
- Should have the Budget column: The core unit column will list core units and recognized delegates by name.
- Should add column “% of Total”
- Should be displayed 12 row, when the “By Budget” category is select
- Should order the entries of the table by absolute amount regardless of their source
- Should on the "By budget" the top 10 expenses be by absolute amount regardless of their source, either by individual core units, Individual recognized delegates , “remaining core units” and  “remaining recognized delegates”
- The "View" CTA should go to the right place
- Should have "Total …
> [SES-246] Connect cost breakdown with API

- pages/activity-feed/index.tsx
- pages/core-unit/[code]/activity-feed.tsx
- src/stories/containers/CUActivity/CUActivityFeedContainer.stories.tsx
- src/stories/containers/CUActivity/CUActivityFeedContainer.tsx
- src/stories/containers/CUActivity/cuActivityAPI.ts
- src/stories/containers/GlobalActivity/GlobalActivityAPI.ts
- src/stories/containers/GlobalActivity/GlobalActivityFeedContainer.stories.tsx
- src/stories/containers/GlobalActivity/GlobalActivityFeedContainer.tsx
- src/stories/containers/GlobalActivity/useGlobalActivity.ts
Due to the global activity feed not being paginated, the result is too heavy so this page is outperforming. Now the page is going to show the last 500 activities only
- Limit the activity feed item numbers to 500 on the Global and the Core Units Activity Feeds
> Limit global activity feed to 500 items

- src/core/businessLogic/builders/budgetStatementBuilder.ts
- src/core/businessLogic/builders/budgetStatementMKRVestBuilder .ts
- src/core/businessLogic/builders/budgetStatementWalletBuilder.ts
- src/core/businessLogic/builders/budgetStatementWalletTransferRequestBuilder.ts
- src/core/utils/storybook/mocks/coreUnitsMocks.ts
- src/stories/containers/TransparencyReport/TransparencyReport.stories.tsx
Add pending stories variants of the transparency reports page.
Added:
- mkr vesting variant
- transfer request variant
- Add pending variants on the transparency page story
> [SES-QC-254] Add pending variants on the transparency page story

- src/stories/containers/TransparencyReport/components/TransparencyForecast/useTransparencyForecast.ts
- Prevented not including breakdown items of the wallets lines budget statement on the breakdown section of the forecast tab on the transparency reports page
-There are duplicated breakdown items in the forecast tab on the transparency report page
> [SES-QC-254] Prevent not including items into grouped due empty/null values

- src/stories/containers/FinancesOverview/FinancesOverviewContainer.stories.tsx
- src/stories/containers/FinancesOverview/components/CostBreakdownTable/CostBreakdownTable.tsx
Remove recognized delegates from the bottom remaining core units row when the Delegate is in the top 10
- The core units breakdown list for 2021, duplicates Recognized Delegates. Impacting the integrity of displayed data
> [SES-QA-256] Remove duplicate DEL on Cost Breakdown table

- src/stories/components/TransparencyCard/TransparencyCard.tsx
#What solved
Should show the correct color in the line for separation in the forecast tab for mobile view
Add border-top line instead border
> [SES-254] Correct color in the line forecast card

- src/stories/components/CoreUnitCard/CoreUnitCard.tsx
- src/stories/containers/TransparencyReport/components/TransparencyAuditorComments/AuditorCommentsContainer/AuditorCommentsContainer.tsx
- src/stories/containers/TransparencyReport/components/TransparencyAuditorComments/GenericCommentCard.tsx
https://trello.com/c/Z1EJXde6/265-qc-round-v-90
#What solved
Should display the #405361 color in the Expenditure (headers) in the core units list (375).
1-Add correct color in dark mode card Core Unit Table
2-Should display the line with the correct color in dark mode. (375 resolution, RWF Core unit, Expense Reports view, Comments tab).
3-Should display a space = 40 px between the Participant Role and Additional Notes section.(375 resolution, Expense Reports view, Comments tab)
> [SES-265] Add correct color in dark mode card cu-table

- src/stories/components/Tabs/Tabs.tsx
- src/stories/containers/TransparencyReport/components/TransparencyActuals/TransparencyActuals.tsx
- src/stories/containers/TransparencyReport/components/TransparencyActuals/useTransparencyActuals.ts
- src/stories/containers/TransparencyReport/components/TransparencyForecast/TransparencyForecast.tsx
- src/stories/containers/TransparencyReport/components/TransparencyForecast/useTransparencyForecast.ts
Upgrade the breakdown tabs in the actuals and forecast main tabs to allow opening the tabs in new tabs
- Should allow opening in a new browser tab when the user right click on the tabs on the actuals breakdown and the forecast breakdown
> [SES-257] Allow to open breakdown tabs in a new tab

- src/stories/containers/TransparencyReport/TransparencyReport.stories.tsx
- src/stories/containers/TransparencyReport/useTransparencyReport.tsx
Added a variant for the Transparency report page with the Budget report (Auditori view) tab activated
- Should add the "Budget Report" story variant to the `TransparecyReport` Story
> [SES-257] Add Budget Report story variant

- src/stories/components/AdvancedInnerTable/AdvancedInnerTable.tsx
- src/stories/components/NumberCell/NumberCell.tsx
- src/stories/containers/RecognizedDelegatesReports/DelegatesActuals/useDelegatesActuals.ts
- src/stories/containers/TransparencyReport/components/TransparencyActuals/useTransparencyActuals.ts
- src/stories/containers/TransparencyReport/components/TransparencyForecast/TransparencyForecast.tsx
- src/stories/containers/TransparencyReport/utils/actualsTableHelpers.ts
The numbers in the tables of the actuals and forecast columns of the actuals tab were changed to green when they were negative. The change was made on the CU and delegates report pages. 
- Should show the negative number in the actuals and forecast tabs of the actuals total table in green
- Should show the negative number in the actuals and forecast tabs of the actuals breakdown table in green
> [SES-257] Change actuals and forecast negative numbers to green

- src/core/utils/urls.ts
- src/stories/components/Tabs/Tabs.tsx
- src/stories/containers/TransparencyReport/components/BudgetReport/BudgetReport.tsx
- src/stories/containers/TransparencyReport/components/BudgetReport/useBudgetReport.ts
- src/stories/containers/TransparencyReport/components/TransparencyActuals/useTransparencyActuals.ts
- src/stories/containers/TransparencyReport/components/TransparencyForecast/useTransparencyForecast.ts
- src/stories/containers/TransparencyReport/useTransparencyReport.tsx
Allow to compress/expand the breakdown tabs in the actuals and forecast sections simultaneously. The state of the tabs is shareable through the URL and the state should be kept after the page refresh or the URL opened on any other device.
- Should compress the actuals and forecasts breakdown at the same time
- Should compress all the breakdown tabs by default when the auditor view is opened
- Should allow to share the state of the breakdown tabs (compressed/expanded) through the URL utilizing the `breakdownView` query string
> [SES-257] Improve Breakdown tabs behavior on Budget Report section

- src/core/hooks/useHashFragment.tsx
- src/core/utils/string.ts
- src/stories/components/svg/ArrowLink.tsx
- src/stories/containers/TransparencyReport/components/BudgetReport/BudgetReport.tsx
- src/stories/containers/TransparencyReport/components/BudgetReport/components/BudgetSection/BudgetSection.tsx
- src/stories/containers/TransparencyReport/components/BudgetReport/components/SectionTitle/SectionTitle.stories.tsx
- src/stories/containers/TransparencyReport/components/BudgetReport/components/SectionTitle/SectionTitle.tsx
- src/stories/containers/TransparencyReport/components/BudgetReport/useBudgetReport.ts
Allow opening the Budget sections in a new tab and move the scroll to the section
- Should allow to update the active section through the hash and move the scroll to that section with the link is shared, the page is refreshed or opened in a new tab
-  Should allow opening in a new tab the "Actuals - Totals" when the page is in Auditor View
- Should allow opening in a new tab the "Actuals - Breakdown" when the page is in Auditor View
- Should allow opening in a new tab the "Forecasts - Totals" when the page is in Auditor View
- Should allow opening in a new tab the "Forecasts - Breakdown" when the page is in Auditor View 
- Should allow opening in a new tab the "MKR Vesting Overview" when the page is in Auditor View
- Should …
> [SES-257] Open Budget Sections in a new tab

- src/core/models/dto/userActivityDto.ts
- src/core/utils/userActivity.ts
- src/stories/components/Tabs/Tabs.tsx
- src/stories/containers/TransparencyReport/TransparencyReport.tsx
- src/stories/containers/TransparencyReport/useTransparencyReport.tsx
- src/stories/containers/TransparencyReport/utils/constants.ts
The status of the auditor's view is now saved to local storage if the user is not logged in or in the server if the user is logged in and it is restored when the transparency page is opened
- Should utilize browser cookies (or equivalent user preference storage) to store the auditor view preference, allowing the application to remember the user's selected view and maintain it across sessions, thus offering a personalized and consistent user experience.
> [SES-257] Save the auditor view status

- src/stories/containers/TransparencyReport/components/TransparencyActuals/useTransparencyActuals.ts
- src/stories/containers/TransparencyReport/utils/budgetStatementsUtils.ts
Added the real values to the Mthly Budget column
- Should add a new column titled "MTHLY BUDGET" immediately to the right of the "wallet" column, which will display the budget cap for each entry.
> [SES-257] Added the values to the Mthly Budget column

- src/core/businessLogic/reconizedDelegate.ts
- src/stories/components/CustomBarChart/CustomBarChart.tsx
✅Should The bars should display gray color when there is no value in the month
Add the color gray and give height when the value is cero
> Add color gray and give hight when the value is cero

- pages/recognized-delegates/finances/reports/index.tsx
- src/core/auth/delegatesExtension.ts
- src/stories/containers/RecognizedDelegatesReports/DelegatesActuals/DelegatesActuals.tsx
- src/stories/containers/RecognizedDelegatesReports/DelegatesForecast/DelegatesForecast.tsx
- src/stories/containers/RecognizedDelegatesReports/RecognizedDelegatesReportAPI.ts
- src/stories/containers/RecognizedDelegatesReports/useRecognizedDelegatesReport.tsx
- src/stories/containers/TransparencyReport/components/ExpenseReport/components/ExpenseSection/ExpenseSection.tsx
- src/stories/containers/TransparencyReport/components/TransparencyAuditorComments/AuditorCommentsContainer/useCommentsContainer.ts
The delegates transparency page got broken after the Delegates was removed from the CU endpoint as it is not a CU, the page was fixed using the new way: fetching directly the budget statements owned by the delegates
-  Should fix the Recognize delegates report page after the API breaking change.
- Should update the spacing of the section: Actuals and Forecast of the Delegates repots reports page
> [SES-265] Fix the delegates transparency reports page

- src/stories/containers/TransparencyReport/components/ExpenseReport/ExpenseReport.tsx
When the user navigates between the core units with the Auditor view activated and then refresh the page it breaks
- When accessing the SH, COM, GROW, KING core units, an error is displayed (the access can be through the url or core unit navigators).
> [SES-265] Fix Auditor view breaks on refresh

- src/stories/containers/TransparencyReport/components/ExpenseReport/ExpenseReport.tsx
Fix spacing in the top of the breakdowns sections in auditor view
-  Should display a space between the tab and the Headcount Expenses area.
> [SES-] Fix mobile spacing

- src/stories/components/CustomMultiSelect/CustomMultiSelect.tsx
- src/stories/containers/RecognizedDelegates/components/FilterDelegate/FilterDelegate.tsx
✅The filter should allow the selection of all core units. Global Activity
Fix-issues-filter-delegate
> Fix-issues-filter-delegate

- src/stories/components/CoreUnitSummary/CoreUnitSummary.tsx
- src/stories/components/Tabs/Tabs.tsx
- src/stories/containers/TransparencyReport/TransparencyReport.tsx
- src/stories/containers/TransparencyReport/components/ExpenseReport/ExpenseReport.tsx
- src/stories/containers/TransparencyReport/components/ExpenseReport/useExpenseReport.tsx
- src/stories/containers/TransparencyReport/useTransparencyReport.tsx
https://trello.com/c/kUYUN01m/266-qc-round-v-100-r
Fixed issues on Auditor View related to the tabs
- When accessing the SH, COM, GROW, KING core units, an error is displayed (the access can be through the url or core unit navigators). 
- Expense Reports view is displayed but with the Auditor view tabs. **Visual Proof:** [video](https://trello.com/1/cards/641b2be81cff6a200ce72382/attachments/644bac600e853a55f67f15ef/download/screencast-expenses-dev.makerdao.network-2023.04.28-14_21_08.webm)
- Clicking on the collapse/expand icons, a jump is displayed. **Visual Proof:** [wrong behavior.webm](https://trello.com/1/cards/641b2be81cff6a200ce72382/attachments/6453a880da92ae3149f4ecc1/download/cinnamon-2023-05-04T144311%2B0200.webm)
- Should hide the red dot icon to the right of the comment tab …
> [SES-QC-266] Fix Auditor view pending issues

- feature-flags/feature-flags.development.ts
- feature-flags/feature-flags.interface.ts
- feature-flags/feature-flags.production.ts
- feature-flags/feature-flags.staging.ts
- src/stories/containers/TransparencyReport/TransparencyReport.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/AccountsSnapshot.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/CUReserves/CUReserves.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/ExpensesComparison/ExpensesComparison.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/FundingOverview/FundingOverview.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/SectionHeader/SectionHeader.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/useAccountsSnapshot.ts
- src/stories/containers/TransparencyReport/useTransparencyReport.tsx
Added the Accounts Snapshot tab and the headers of each section
- Should enable/disable the "Accounts Snapshot" section through feature flags
- Should create a new tab called "Accounts Snapshot"
- Should add the MakerDAO Funding Overview section within the "Accounts Snapshot" tab (header) 
- Should add the Total Core Unit Reserves section within the "Accounts Snapshot" tab (header)
- Should add the Reported Expenses Comparison section within the "Accounts Snapshot" tab (header)
> [SES-268] Add Accounts Snapshot tab

- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/CUReserves/CUReserves.stories.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/CUReserves/CUReserves.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Cards/FundChangeCard.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Cards/OutlinedCard.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Cards/SimpleStatCard.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/FundingOverview/FundingOverview.stories.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/FundingOverview/FundingOverview.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/NumberWithSignCard/NumberWithSignCard.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/SVG/Equals.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/SectionHeader/SectionHeader.tsx
Added the cards in the Funding Overview section and in the Total Core Unit Reserves section
- Should add the "Initial Lifetime Balance" card in the MakerDAO Funding Overview section
- Should add a card with the info of the " Extra Funds Made Available", the "Funds Returned via DSSBLow" and the "Net change"
- Should add the "Inflow Core Unit Amount" card in the Total Core Unit Reserves section
- Should add the inflow/outflow card in the Total Core Unit Reserves section
- Should add the "New Core Unit Reserves" card in the Total Core Unit Reserves
> [SES-268] Add cards in the Accounts Snapshot tab sections

- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/AccordionArrow/AccordionArrow.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/FundingOverview/FundingOverview.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/TransactionHistory/TransactionHistory.tsx
Add the "View transaction history" section. This section is implemented without the "expanded" content
- Should add the transaction history section (collapsed)
> [SES-268] Add transaction history

- src/stories/components/AdvancedInnerTable/AdvancedInnerTable.tsx
- src/stories/components/TransparencyCard/TransparencyCard.tsx
- src/stories/containers/TransparencyReport/components/HeaderWithIcon/HeaderWithIcon.tsx
✅Should hidden tooltip in the card that are not totals
✅ Should the tooltip show Month: Indicate the specific month for which the forecast and budget cap data is being presented.
✅Should the tooltip show Severity distinction: Include a high/medium/low distinction that matches the color of the bar (red, yellow, or green) to represent the severity of the forecast relative to the budget cap.
✅Should the tooltip show Percent of budget cap: Show the percentage of the budget cap forecasted to be spent for that specific month and year.
✅Should the tooltip show Absolute numbers: Display the absolute values for the forecast and budget cap, allowing users to easily compare the numbers.
Hidden icon cards when is mobile
> Hidden icon cards when is mobile

- src/stories/components/CustomPopover/CustomPopover.tsx
- src/stories/containers/TransparencyReport/components/HeaderWithIcon/HeaderWithIcon.tsx
- src/stories/containers/TransparencyReport/components/TransparencyForecast/useTransparencyForecast.tsx
- src/stories/containers/TransparencyReport/utils/forecastHelper.ts
✅Should the tooltip contain a link to the relevant MIP (Maker Improvement Proposal)
✅Should all other forecast numbers within the forecast breakdown (non-totals), we will also include The budget cap for the specific month.
✅Should all other forecast numbers within the forecast breakdown (non-totals), we will also include: A dotted line that expresses 100% of the budget cap reached.**PR**https://github.com/makerdao-ses/ecosystem-dashboard/pull/778
Add the correct way to get info tooltip
Add hard code for the size tooltip
Add size as props
> Add correct way get info popover

- src/stories/containers/TransparencyReport/components/HeaderWithIcon/HeaderWithIcon.tsx
- src/stories/containers/TransparencyReport/components/TransparencyForecast/useTransparencyForecast.tsx
- src/stories/containers/TransparencyReport/utils/forecastHelper.ts
✅Should show a tooltip for the budget caps beside {Month} header column, when the user hovers over the icon
✅Should the month columns should display the next 3 months after the month that you are in
✅ Should move the dotted line to the left of the horizontal bar graph to make it clear that the forecast is more than 100% of the budget cap.
✅Should show the correct values forecast and budget cap, for the new component
Add dark mode and fix the header
Add delay for close popover
> Add dark mode and fix header

- src/stories/components/AdvanceTable/AdvanceTable.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/ExpensesComparison/ExpensesComparison.stories.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/ExpensesComparisonRowCard/ExpensesComparisonRowCard.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/useAccountsSnapshot.tsx
Add the capability to transform the table into cards in the "Reported Expenses Comparison" section
- Should show the exhibit five rows as cards instead of a table in mobile (Reported Expenses Comparison) 
- Should replace the table in the "Reported Expenses Comparison" section by expandable cards
> [SES-268] Replace the table by expandable cards

- src/stories/components/CustomPopover/CustomPopover.tsx
- src/stories/components/TransparencyCard/TransparencyCard.tsx
- src/stories/containers/TransparencyReport/components/HeaderWithIcon/HeaderWithIcon.tsx
✅The change was made but in dark mode, the text (Totals) is barely visible. Check the font color in dark mode.
✅ Resolution: 1194, the tooltip is cut off on the right side
✅ The tooltip should be displayed. It is a little bit difficult to see the modal. 
Add the correct color dark mode and fix the arrow position
> Add correct color dark mode and fix arrow position

- src/stories/containers/TransparencyReport/components/TransparencyForecast/BarWithDottedLine.stories.tsx
- src/stories/containers/TransparencyReport/components/TransparencyForecast/BarWithDottedLineMobile.tsx
- src/stories/containers/TransparencyReport/components/TransparencyForecast/ProgresiveIndicator.tsx
- src/stories/containers/TransparencyReport/components/TransparencyForecast/ProgresiveIndicatorMobile.tsx
✅Hovering/clicking on the bars, the tooltip should be displayed. The touch area should be the actual number,  budget number, and bars. **Current Output:** The tooltip still missing.dashboard/pull/785 
Add hover in all parts mobile component
> Add hover in all part mobile component

- .vscode/settings.json
- package.json
- src/core/utils/dictionary.js
- src/core/utils/string.ts
- src/stories/components/CopyIcon/CopyIcon.tsx
- src/stories/components/svg/ClipBoard.tsx
- src/stories/components/svg/information.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/CUReserves/CUReserves.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Cards/ReserveCard/ReserveCard.stories.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Cards/ReserveCard/ReserveCard.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/WalletInfo/WalletInfo.stories.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/WalletInfo/WalletInfo.tsx
- yarn.lock
Added on chain and off reserves subsections
- Should add the "On-Chain Reserves" sub section in the Total Core Unit Reserves section and display title, subtitle, and three expandable rows (DSS Vest, Auditor, Operational) with four columns (Initial Balance, Inflow, Outflow, New Balance) 
- Should make the "On-Chain Reserves" cards responsive
- Should add the "Off-Chain Reserves" sub section in the Total Core Unit Reserves section and Show one row (Payment Processor) with four columns (Initial Balance, Inflow, Outflow, New Balance)
> [SES-268] On and Off Chain reserves cards

- src/stories/containers/TransparencyReport/components/HeaderWithIcon/HeaderWithIcon.tsx
- src/stories/containers/TransparencyReport/components/TransparencyForecast/BarWithDottedLine.tsx
- src/stories/containers/TransparencyReport/components/TransparencyForecast/BarWithDottedLineMobile.tsx
- src/stories/containers/TransparencyReport/transparencyReportUtils.tsx
✅It is hard to touch the tooltip area
✅Hovering/clicking on the bars, the tooltip should be displayed. The touch area should be the actual number,  budget number, and bars. **Current Output:** The tooltip still missing. 
✅ Hovering over the 2 last values from the Totals column. **Expected Output:** The tooltip should be visible. **Current Output:** When the values are closer to the bottom, the tooltip is not displayed
Fix popover don't show
> Fix popover don't show

- src/stories/containers/TransparencyReport/components/TransparencyForecast/BarWithDottedLine.tsx
- src/stories/containers/TransparencyReport/components/TransparencyForecast/BarWithDottedLineMobile.tsx
- src/stories/containers/TransparencyReport/components/TransparencyForecast/useTransparencyForecast.tsx
- src/stories/containers/TransparencyReport/utils/forecastHelper.ts
✅ **Expected Output:** The rigth and left paddings should be = 24px. **Current Output:** The right paddings on both tables displays 24px plus other space. 
✅ SAS core unit. Breakdown. **Expected Output:** If the percent is equal to 100, the dots should be displayed at the end. **Current Output:** The percent is equal to 100 but the dots are displayed at the begging of the bar.
Delete unnecessary space in mobile
Fix case 100% bars
> Delete unnecessary space in mobile

- src/stories/containers/TransparencyReport/components/HeaderWithIcon/HeaderWithIcon.tsx
- src/stories/containers/TransparencyReport/components/PopverForecastDescription/PopoverForecastDescription.tsx
✅Should show the same information when there is no forecast
Fix popover as core unit chart
> Fix popover as core unit chart

- src/stories/components/AdvancedInnerTable/AdvancedInnerTable.tsx
https://trello.com/c/kUYUN01m/266-qc-round-v-100-r
When navigating between the core units under specific circumstances the page crash
-  Auditor view, SES core unit: http://46.101.104.232:82/core-unit/SES/finances/reports?section=expense-report&view=auditor&forecast-account=incubation-program&breakdownView=default&actual-account=permanent-team. **Expected Output:** - **Current Output:** Changing the core unit, an error is displayed (the view crash). **Visual Proof:** [crash.webm](https://trello.com/1/cards/643fb08255b18a0d27d36be9/attachments/647743c81ae0d4e0b873d1a6/download/cinnamon-2023-05-31T122225%2B0200.webm).
> [SES-QC-266] Fix Auditor View on navigation issue

- src/stories/containers/TransparencyReport/components/PopverForecastDescription/PopoverForecastDescription.tsx
✅SAS core unit. Breakdown. **Expected Output:** In case of negative numbers, let’s just hide the % row. **Current Output:** The forecast and the percent are displayed with a negative value.  **Visual Proof:** 
Add condition hidden % values negative
> Add condition hidden % values negative

- src/stories/containers/TransparencyReport/components/PopverForecastDescription/PopoverForecastDescription.tsx
✅ **Expected Output:** Let’s just hide the % row and the 0 on the top right. **Current Output:** It's displayed a "-" in the percent and a 0 on the top right. 
Delete the cero and percent when forecast and not budget cap
> Delete the cero and percent when forecast and not budgets

- src/stories/containers/FinancesOverview/components/QuarterCarousel/QuarterCarousel.tsx
https://trello.com/c/kUYUN01m/266-qc-round-v-100-r
Decrease the navigation arrows of the Quarter Carouser in the Finances page to prevent the arrow from going over the navbar
- **Steps to Reproduce:** Scroll down till the navigation arrows of the Quarterly Carouser are in the same position of the navbar **Expected Output:** The arrows should be under the navbar **Current Output:** It's displayed over the navbar.
> [SES-QC-266] Fix Quarter Carousel Navigation zIndex

- src/stories/components/CopyIcon/CopyIcon.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/SVG/GreenArrowDown.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/SVG/RedArrowUp.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Transaction/MobileTransaction.stories.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Transaction/MobileTransaction.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Transaction/Transaction.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Transaction/TransactionWalletInfo.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/TransactionHistory/TransactionHistory.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/TxHash/TxHash.tsx
Created expandable transactions component for transactions on Mobile using Blockies for sender/receivers components
- Should allow to collapse/expand the "View transaction history" subsection in the MakerDAO Funding Overview section (taking in count the responsiveness)
- Should create an expandable transaction info component for the Transaction History section on mobile 
- Should create a "blockie" avatars component for the wallets Blockie
> [SES-268] Created Mobile transaction component

- src/core/models/dto/snapshotAccountDTO.ts
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/AccountsSnapshot.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/CUReserves/CUReserves.stories.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/CUReserves/CUReserves.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Cards/SimpleStatCard.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/FundingOverview/FundingOverview.stories.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/FundingOverview/FundingOverview.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/useAccountsSnapshot.tsx
Integrate the cards in the "Total Core Unit Reserves" section with the API. Cards:
- Initial Core Unit Reserves
- Inflow
- Outflow
- New Core Unit Reserves
- Should show the actual values coming from the API in the cards of the  "Total Core Unit Reserves" section (cards)
> [SES-268] Integrate Total Core Unit Reserves section with the API

- src/core/models/dto/expenseCategoriesDTO.ts
- src/stories/components/BasicModal/CategoryItem/ArrowAccordionCategory.tsx
- src/stories/components/BasicModal/CategoryItem/CategoryItem.tsx
- src/stories/components/BasicModal/ContainerModal.tsx
- src/stories/containers/FinancesOverview/FinancesOverviewContainer.tsx
- src/stories/containers/FinancesOverview/useFinancesOverview.ts
✅Should the modal have the "expand all categories" functionality to expand/collapse the categories
This adds to the behavior of expanded all when the checkbox is select
> Add expanded all behaviors

- src/stories/containers/FinancesOverview/FinancesOverviewContainer.tsx
✅ The modal is displayed T the end of the page.
✅  All text is displayed with lower letters. 
Add only marginTop when is mobile
> Add position in mobile

- src/stories/containers/CUAbout/CuAboutContainer.tsx
https://trello.com/c/FEo923dc/277-qa-bug-finding-r
The Makerburn link on the CU about was fixed
- The link View on-chain transfers to PE Core Unit on makerburn.com within the “Expenses” Box directs to an outdated link.
> [SES-QA-277] Fix: makerburn link

- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Cards/FundChangeCard.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Cards/ReserveCard.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/GroupItem/GroupItem.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Transaction/segments/TransactionAmount.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/TransactionHistory/TransactionHistory.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/TransactionList/TransactionList.tsx
Created a transaction list with group support for the on/off chain reserves cards and reused in the transaction history
- Should support multiple groups and corresponding wallets (e.g., "Stream 14" and its corresponding wallet) and transactions when the cards in the "On/Off Chain reserves" are expanded
> [SES-268] Implement group transaction list

- src/core/businessLogic/builders/accountSnapshot/accountSnapshotBuilder.ts
- src/core/businessLogic/builders/accountSnapshot/snapshotAccountBalanceBuilder.ts
- src/core/businessLogic/builders/accountSnapshot/snapshotAccountTransactionBuilder.ts
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/AccountsSnapshot.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/CUReserves/CUReserves.stories.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/CUReserves/CUReserves.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Cards/FundChangeCard.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Cards/SimpleStatCard.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/FundingOverview/FundingOverview.stories.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/FundingOverview/FundingOverview.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/NumberWithSignCard/NumberWithSignCard.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/WalletInfo/WalletInfo.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/useAccountsSnapshot.tsx
Render the On Chain reserves cards according to the data coming from the API
- Should render the "On chain reserves" cards based on the data coming from the API (each card with the correct data)
> [SES-268] Integrate on chain reserve cards with the API

- src/stories/containers/TransparencyReport/components/AccountsSnapshot/AccountsSnapshot.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/api/queries.ts
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/FundingOverview/FundingOverview.stories.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/FundingOverview/FundingOverview.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Transaction/Transaction.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/TransactionHistory/TransactionHistory.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/TransactionList/TransactionList.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/useAccountsSnapshot.tsx
Render the transactions of the root account coming from the API in the transaction history 
- Should show the correct transactions coming from the API in the "View transaction history" subsection of the "MakerDAO Funding Overview" section
> [SES-268] Integrated the transaction history with the API

- src/stories/containers/TransparencyReport/TransparencyReport.tsx
- src/stories/containers/TransparencyReport/components/ExpenseReport/ExpenseReport.tsx
- src/stories/containers/TransparencyReport/components/ExpenseReport/useExpenseReport.tsx
✅Should the link open the modal with the correct data 
This pr is for the show the modal in the auditor view
> Modal don't show auditor view

- src/stories/components/CustomTooltip/CustomTooltip.stories.tsx
Describing usecases for viewport overflow and hiden delay
> [SES-268] Custom tooltip overflow

- src/stories/containers/TransparencyReport/components/ExpenseReport/ExpenseReport.tsx
- src/stories/containers/TransparencyReport/components/TransparencyForecast/useTransparencyForecast.tsx
✅Should remove the icon displayed in the Forecast tab, next to the Budget Category
This is to remove the icon for the forecast view
> [SES-no-ticket-278]Fix/delete icon budget cap

- src/core/models/dto/snapshotAccountDTO.ts
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Cards/ReserveCard.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Transaction/MobileTransaction.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Transaction/Transaction.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Transaction/segments/TransactionAmount.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/TransactionHistory/TransactionHistory.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/TransactionList/TransactionList.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/useAccountsSnapshot.tsx
Make the positive numbers in the "View Transaction History" section green
> [SES-268] Make the positive numbers green in the transaction history section

- src/stories/containers/TransparencyReport/components/AccountsSnapshot/AccountsSnapshot.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/CUReserves/CUReserves.stories.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/CUReserves/CUReserves.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/useAccountsSnapshot.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/utils/reserveUtils.ts
Integrate off-chain section with the API
> [SES-208] Integrate the off-chain section with the API

- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/CUReserves/CUReserves.stories.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Cards/ReserveCard.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/GroupItem/GroupItem.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Transaction/Transaction.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Transaction/segments/TransactionHeader.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/WalletInfo/WalletInfo.tsx
Redistributing the space on Reserve Card so it supports longer account names
> [SES-208] Feature/add space to reserve cards

- src/stories/components/CUActivityTable/ActivityTable.tsx
- src/stories/containers/Actors/ActorsContainer.stories.tsx
- src/stories/containers/Actors/ActorsContainer.tsx
- src/stories/containers/Actors/components/ActorHeader/ActorsHeaderTable.tsx
- src/stories/containers/Actors/components/ActorItem/ActorItem.tsx
- src/stories/containers/Actors/components/ActorTable/ActorTable.tsx
- src/stories/containers/Actors/useActors.ts
This adds a header for the table, add dark mode, and different sizes for the cards
> Add header for table and dark mode

- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/CUReserves/CUReserves.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Cards/ReserveCard.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/TransactionList/TransactionList.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/useAccountsSnapshot.tsx
Hide the arrow of the CU reserve cards when they have no transactions, also was made it unclickable the cards when there are no transactions. The Off-Chain section and all its data are now hidden when there is no Off-chain data
> [SES-268] Improve the UI when there is no data for the off-chain section

- src/stories/components/CustomPopover/CustomPopover.tsx
Fix the tooltip should close when opening a new tab
> Fix error popover remainder open

- src/stories/components/CustomTableHeader/CustomTableHeader.tsx
- src/stories/containers/Actors/ActorsContainer.tsx
- src/stories/containers/Actors/components/ActorHeader/ActorsHeaderTable.tsx
This add hover to read more, and also fix color in the arrow
> Add hover and fix color arrow in header table for dark mode

- src/stories/containers/TransparencyReport/components/AccountsSnapshot/AccountsSnapshot.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/CUReserves/CUReserves.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Cards/ExpensesComparisonRowCard/ExpensesComparisonRowCard.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Cards/ReserveCard.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/ExpensesComparison/ExpensesComparison.stories.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/ExpensesComparison/ExpensesComparison.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/ExpensesComparison/headers.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Transaction/Transaction.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Transaction/segments/TransactionHeader.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/TransactionHistory/TransactionHistory.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/TxHash/TxHash.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/useAccountsSnapshot.tsx
A new version of the table is sown in the Expense comparison section when there are no off-chain data, this change includes the mobile version of the table in cards too. The performance of the Snapshot account page was improved by memorizing the high CPU-demanding operations.
> [SES-268] Add On chain only version to the expense comparison table

- .vscode/settings.json
- src/core/models/dto/snapshotAccountDTO.ts
- src/stories/components/SESTooltip/SESTooltip.stories.tsx
- src/stories/components/SESTooltip/SESTooltip.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/AccountsSnapshot.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/AccountsSnapshotTabContainer.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/api/queries.ts
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/ExpensesComparison/ExpensesComparison.stories.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/useAccountsSnapshotTab.ts
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/useAccountsSnapshot.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/utils/expenseComparisonUtils.tsx
Integrate the Expense comparison section with the API
Renamed the new Tooltip component
> [SES-268] Integrate the expense comparison section with the API

- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Cards/ExpensesComparisonRowCard/ExpensesComparisonRowCardSkeleton.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/ExpensesComparison/ComparisonTableSkeleton.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/ExpensesComparison/ExpensesComparisonSkeleton.stories.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/ExpensesComparison/ExpensesComparisonSkeleton.tsx
Added the Reported expenses comparison skeleton to the general Account Snapshot skeleton
> [SES-268] Created Expenses Comparison Skeleton

- src/stories/containers/TransparencyReport/TransparencyReport.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/AccountsSnapshotTabContainer.tsx
- src/stories/containers/TransparencyReport/components/Placeholders/TransparencyEmptyTable.tsx
Add an empty state in the Account Snapshots tab of the Core Unit reporting page when there is no data for the Account snapshots
> [SES-268] Add account snapshot empty state

- pages/ecosystem-actors/[code]/finances/reports/index.tsx
- src/core/businessLogic/coreUnits.ts
- src/core/hooks/useBudgetStatementPager.ts
- src/core/hooks/useTransparencyReporting.ts
- src/core/models/interfaces/generics.ts
- src/stories/containers/ActorsAbout/ActorSummary/ActorTitleAbout.tsx
- src/stories/containers/ActorsTransparencyReport/ActorsTransparencyReportContainer.tsx
- src/stories/containers/ActorsTransparencyReport/api/queries.ts
- src/stories/containers/ActorsTransparencyReport/components/TeamHeadlineText/TeamHeadlineText.tsx
- src/stories/containers/RecognizedDelegatesReports/DelegatesActuals/DelegatesActuals.tsx
- src/stories/containers/RecognizedDelegatesReports/DelegatesForecast/DelegatesForecast.tsx
- src/stories/containers/TransparencyReport/TransparencyReport.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/AccountsSnapshotTabContainer.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/useAccountsSnapshotTab.ts
- src/stories/containers/TransparencyReport/components/CuHeadlineText/CuHeadlineText.tsx
- src/stories/containers/TransparencyReport/components/Placeholders/TransparencyEmptyTable.tsx
- src/stories/containers/TransparencyReport/components/TransparencyActuals/TransparencyActuals.tsx
- src/stories/containers/TransparencyReport/components/TransparencyForecast/TransparencyForecast.tsx
- src/stories/containers/TransparencyReport/components/TransparencyMkrVesting/TransparencyMkrVesting.tsx
- src/stories/containers/TransparencyReport/components/TransparencyTransferRequest/TransparencyTransferRequest.tsx
https://trello.com/c/KT93qSRs/288-user-story-ability-to-view-ecosystem-actor-expense-reports
Stabilize the first 4 tabs
> [SES-288] Stabilize primary tabs

- src/stories/containers/ActorsAbout/ActorSummary/ActorSummary.tsx
- src/stories/containers/ActorsTransparencyReport/ActorsTransparencyReportContainer.tsx
Fix the highlight of text in the mobile
> Check BreadCrumb in mobile

- src/stories/components/AdvancedInnerTable/AdvancedInnerTable.tsx
- src/stories/containers/ActorsTransparencyReport/ActorsTransparencyReportContainer.tsx
- src/stories/containers/ActorsTransparencyReport/components/TeamHeadlineText/TeamHeadlineText.tsx
- src/stories/containers/RecognizedDelegatesReports/DelegatesActuals/DelegatesActuals.tsx
- src/stories/containers/RecognizedDelegatesReports/DelegatesForecast/DelegatesForecast.tsx
- src/stories/containers/TransparencyReport/TransparencyReport.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/AccountsSnapshotTabContainer.tsx
- src/stories/containers/TransparencyReport/components/ExpenseReport/ExpenseReport.tsx
- src/stories/containers/TransparencyReport/components/Placeholders/TransparencyEmptyTable.tsx
- src/stories/containers/TransparencyReport/components/TransparencyActuals/TransparencyActuals.tsx
- src/stories/containers/TransparencyReport/components/TransparencyForecast/TransparencyForecast.tsx
- src/stories/containers/TransparencyReport/components/TransparencyMkrVesting/TransparencyMkrVesting.tsx
- src/stories/containers/TransparencyReport/components/TransparencyTransferRequest/TransparencyTransferRequest.tsx
https://trello.com/c/KT93qSRs/288-user-story-ability-to-view-ecosystem-actor-expense-reports
Fix the issues
> [SES-288] Fix shortcode issues

- src/core/hooks/useMobileDetector.ts
- src/stories/components/CustomPopover/CustomPopover.tsx
- src/stories/components/SESTooltip/ModalBottomSheet.tsx
- src/stories/components/SESTooltip/SESTooltip.stories.tsx
- src/stories/components/SESTooltip/SESTooltip.tsx
Allow showing the tooltips as a modal bottom sheet in real mobile devices
The `CustomPopover` component was marked as deprecated in favor of `SESTooltip`
> [SES-268] Show modal sheet on real mobile devices

- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/CUReserves/CUReserves.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/ExpensesComparison/ExpensesComparison.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/ExpensesComparison/headers.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/FundingOverview/FundingOverview.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/SectionHeader/SectionHeader.tsx
Added tooltips content to the Account Snapshot sections
> [SES-268] Add tooltips in the Account Snapshot tab

- src/core/hooks/useTransparencyReportingTabs.tsx
- src/stories/containers/ActorsTransparencyReport/useActorsTransparencyReport.tsx
- src/stories/containers/TransparencyReport/TransparencyReport.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/FundingOverview/FundingOverview.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/SectionHeader/SectionHeader.tsx
- src/stories/containers/TransparencyReport/useTransparencyReport.tsx
A few improvements in the Account snapshot tab were made. The whole logic of the expense reporting pages is now fully reutilizable through hooks
> [SES-268] Expense reporting logic improvements

- src/stories/containers/TransparencyReport/utils/budgetStatementsUtils.ts
The issue was when the headcountExpense is undefined instead of a boolean, now it is handles as false in those cases
> [SES-QC-278] Actuals breakdown for non headcount expenses without value

- src/core/businessLogic/builders/accountSnapshot/snapshotAccountTransactionBuilder.ts
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Cards/ReserveCard.stories.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Cards/ReserveCard.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/GroupItem/GroupItem.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Transaction/InitialBalanceRow.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Transaction/Transaction.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Transaction/segments/TransactionHeader.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/TransactionList/TransactionList.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/utils/expenseComparisonUtils.tsx
Fixed some issues in the CU reserves section
> [SES-268] Fix issues on Account snapshot 

- src/stories/containers/TransparencyReport/components/AccountsSnapshot/AccountsSnapshot.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/AccountsSnapshotTabContainer.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/api/queries.ts
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/FundingOverview/FundingOverview.stories.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/FundingOverview/FundingOverview.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/SectionHeader/SectionHeader.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/useAccountsSnapshotTab.ts
Added the `since date` to the account snapshots tab as the start date of the first snapshot
> [SES-268] Add correct since month

- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/ExpensesComparison/headers.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/SectionHeader/SectionHeader.tsx
Fixed the tooltips of the account snapshot section on mobile devices
> [SES-268] Fix account snapshots tooltips on mobile

- src/stories/containers/FinancesOverview/components/EndgameIntroductionSection/EndgameIntroductionSection.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Cards/FundChangeCardSkeleton.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Cards/ReserveCardMobileSkeleton.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Cards/ReserveCardSkeleton.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/NumberWithSignCard/NumberWithSignCardSkeleton.tsx
Fixed issued on account snapshot skeletons UI
> [SES-QC-278] Fix account snapshot skeleton hightlighted squares

- src/stories/components/SESTooltip/SESTooltip.tsx
Prevent the tooltip to be too close to the edge of the window
> [SES-278] Fix tooltip too close to the viewport

- src/stories/containers/FinancesOverview/FinancesOverviewContainer.tsx
- src/stories/containers/FinancesOverview/components/EndgameIntroductionBanner/EndgameIntroductionBanner.tsx
- src/stories/containers/FinancesOverview/components/EndgameIntroductionBanner/EndgameIntroductionEndgameIntroductionBanner.stories.tsx
https://trello.com/c/FWSdBoo4/290-user-story-expense-dashboard-transition-to-endgame-v1
Added the Endgame proposal link to the endgame introduction banner
> [SES-290] Add external link to the endgame proposal

- src/stories/containers/Endgame/components/BudgetStructureSection/BudgetStructureSection.stories.tsx
- src/stories/containers/Endgame/components/BudgetStructureSection/BudgetStructureSection.tsx
- src/stories/containers/Endgame/components/TotalBudgetContent/TotalBudgetContent.tsx
Added the Total Budget UI to the Endgame Budget Structure section
> [SES-292] Add total budget UI

- src/stories/containers/Endgame/components/EndgameIntroductionBanner/EndgameIntroductionBanner.tsx
- src/stories/containers/Endgame/components/KeyChangesSections/KeyChangesSections.tsx
Now all the key section can be expanded at the same time, except in mobile that only one can be expanded at the same time
> [SES-292] Updated the behavior of the expandable sections on Key Changes

- src/stories/containers/Endgame/components/BudgetTransitionStatusSection/BudgetTransitionStatusSection.stories.tsx
- src/stories/containers/Endgame/components/BudgetTransitionStatusSection/BudgetTransitionStatusSection.tsx
- src/stories/containers/Endgame/components/TransitionDataPicker/TransitionDataPicker.tsx
https://trello.com/c/K6BCBa9u/293-user-story-visualization-of-budget-transition-status
Added the card for the Transition status section of the endgame page + the button group (without behavior)
> [SES-293] add card & toggle button group

- src/core/hooks/useTransparencyReportingTabs.tsx
By default restoring the expense report content was showing the "Expense report" content in auditor view instead of "Account Snapshots"
> [SES-QC] Fix restoring expense report content

- src/core/businessLogic/coreUnits.ts
Add correct link in the absolute CU also
> [No-ticket-278]Add correct link

- src/core/businessLogic/coreUnits.ts
- src/stories/components/TitleNavigationCuAbout/TitleNavigationCuAbout.tsx
Fix function to get correct link
> [No-ticket] Fix links for absolutes

- package.json
- src/stories/containers/Endgame/EndgameContainer.tsx
- src/stories/containers/Endgame/components/NavigationTabs/NavigationTabs.tsx
- src/stories/containers/Endgame/useEndgameContainer.ts
- yarn.lock
Solved issue on iphone devices in the endgame navigation component
> fix: apple devies endgame scroll

- pages/snapshots/[...data].tsx
- src/core/models/interfaces/types.ts
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/api/queries.ts
https://trello.com/c/OTAKvqeH/308-user-story-delegates-and-keepers-snapshot-reports
Add support for recognized delegates and keepers in the temporary snapshot page
> feat: add support to keepers & delegates

- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/Cards/ReserveCard.tsx
https://trello.com/c/OTAKvqeH/308-user-story-delegates-and-keepers-snapshot-reports
Fixed focus color
> [SES-308] Account Snapshots Reserve card focus

- src/stories/containers/FinancesOverview/FinancesOverviewContainer.stories.tsx
- src/stories/containers/FinancesOverview/FinancesOverviewContainer.tsx
- src/stories/containers/FinancesOverview/api/queries.ts
- src/stories/containers/FinancesOverview/components/CostBreakdownTable/ByBudgetTableRow.tsx
- src/stories/containers/FinancesOverview/components/CostBreakdownTable/CostBreakdownTable.tsx
- src/stories/containers/FinancesOverview/components/CostBreakdownTable/TableFooter.tsx
- src/stories/containers/FinancesOverview/components/NavigationButtons/NavigationButtons.tsx
- src/stories/containers/FinancesOverview/useFinancesOverview.ts
- src/stories/containers/FinancesOverview/utils/costBreakdown.ts
Add ecosystem actors to query in finances
> Add actors Breakdown

- src/stories/components/CoreUnitSummary/CoreUnitSummary.tsx
- src/stories/containers/CUAbout/CuAboutContainer.tsx
- src/stories/containers/CUAbout/useCuAbout.ts
- src/stories/containers/CUActivity/CUActivityFeedContainer.tsx
- src/stories/containers/CUActivity/useCuActivity.ts
- src/stories/containers/TransparencyReport/TransparencyReport.tsx
https://trello.com/c/udGDe7fW/278-qc-round-1-r
Add fix in the header summary for the page of about page of core unit and transparency report for core unit
> Add fix header in CoreUnitSummary

- src/stories/containers/Endgame/components/TransitionHeader/TransitionHeader.tsx
Fix the alignment in the 768 breakpoint in the governance section of the endgame page
> [SES-292] Governance section alignment in 768

- src/stories/containers/Finances/components/DelegateExpenseTrend/DelegateExpenseTrendItem.tsx
- src/stories/containers/Finances/components/SeccionPages/DelegateExpenseTrendFinances/DelegateExpenseTrendFinances.tsx
- src/stories/containers/Finances/useFinances.tsx
- src/stories/containers/Finances/utils/utils.ts
Add some issues in last expense report
> [Not-ticket-294] Fix colors and add correct links

- src/core/hooks/useHeaderSummary.ts
When the delegates finance page is reloaded the space between the summary and the comment wasn't the correct
> [SES-310] Delegates summary header

- src/stories/containers/Finances/components/BreadcrumbWithYear/BreadcrumbWithYear.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
- src/stories/containers/Finances/components/SeccionPages/BreadcrumbYearNavigation.tsx
- src/stories/containers/Finances/components/SeccionPages/CardChartOverview/CardChartOverview.tsx
All the card clickable and fix some breakpoint
> Add easy transition and fix breadCrumnb

- src/stories/containers/Endgame/components/EndgameIntroductionBanner/EndgameIntroductionBanner.tsx
Fix the image that wasn't being displayed between 1194 and 1280px
> [SES-310] Fix introduction banner image between 1194-1280

- src/stories/containers/Finances/components/HeaderTable/FinancesTable.tsx
Add new option filter and show correct text when semiannual is select
> Add new option filter

- src/stories/components/BasicModal/CategoryItem/ArrowAccordionCategory.tsx
- src/stories/components/BasicModal/CategoryModalComponent.tsx
- src/stories/components/BasicModal/ChekBoxDescription/ChekBoxDescription.tsx
- src/stories/components/BasicModal/ContainerModal.stories.tsx
- src/stories/components/BasicModal/ContainerModal.tsx
- src/stories/containers/FinancesOverview/components/CostBreakdownTable/ByExpenseCategoryTableRow.tsx
https://trello.com/c/NU2xBFF9/313-finances-homepage-breakpoints-changes
Adapt the "By expense categories" table and the categories modal to the new breakpoints
> [SES-313] Adapt by categories table and the category modal to the new breakpoints

- src/stories/containers/TransparencyReport/components/TransparencyForecast/useTransparencyForecast.tsx
Fix N/A values in total in the forecast tab of the finances pages
> [SES-310] Fix total forecast with N/A values

- src/stories/components/CuTableColumnLinks/CuTableColumnLinks.tsx
- src/stories/components/SocialMediaComponent/SocialMediaComponent.tsx
Fixed the issue in the CU, EA and RD summary component
> fix: hover on mobile devices in the social icons

- src/stories/containers/Finances/components/FiltersTable/FilterTable.tsx
- src/stories/containers/Finances/components/SelectDropdown.tsx
Fix some issues related to the filter select components
> [SES-294] Fix finances filters dropdown

- src/core/hooks/useBudgetStatementComments.ts
Fix the comments items in the Ecosystem Actors finance's page
> [SES-310] Fix activity feed items on comments in ecosystem actors

- src/core/hooks/useTransparencyReportingTabs.tsx
- src/stories/containers/TransparencyReport/TransparencyReport.tsx
Fix the comment tab on the auditor view when the user navigates to the view and the auditor view is the preferred
> [SES-310] Fix enabling comment tab on auditor view on nav

- src/stories/containers/Finances/components/FinacesTable/CellTable.tsx
- src/stories/containers/Finances/components/FinacesTable/FinancesTable.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderAnnually/CellAnnually.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderAnnually/HeaderAnnually.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderMonthly/CellMonthly.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderMonthly/HeaderMonthly.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderQuarterly/CellQuarterly.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderQuarterly/HeaderQuarterly.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderSemiAnnual/HeaderSemiAnnual.tsx
- src/stories/containers/Finances/utils/mockData.ts
- src/stories/containers/Finances/utils/utils.ts
Adjust the row when there is more than one metric
Order the table in function number of category
> Adjust data when there is more one metric

- pages/core-unit/[code]/finances/reports/index.tsx
- pages/ecosystem-actors/[code]/finances/reports/index.tsx
- src/core/hooks/useBudgetStatementPager.ts
- src/core/hooks/useTransparencyReporting.ts
- src/stories/containers/ActorsTransparencyReport/ActorsTransparencyReportContainer.tsx
- src/stories/containers/ActorsTransparencyReport/useActorsTransparencyReport.tsx
- src/stories/containers/TransparencyReport/TransparencyReport.tsx
- src/stories/containers/TransparencyReport/transparencyReportAPI.ts
- src/stories/containers/TransparencyReport/useTransparencyReport.tsx
Allow to navigate the budget statements having in count if there is snapshot data or not
> fix: budget statement navigation

- src/core/auth/teamExtension.ts
- src/core/enums/roleEnum.ts
- src/core/models/dto/delegatesDTO.ts
- src/stories/containers/RecognizedDelegatesReports/RecognizedDelegatesReportAPI.ts
Enable the auditor flow in the delegates reports
> [SES-310] Add delegates auditor flow

- src/stories/containers/Finances/FinacesContainer.tsx
- src/stories/containers/Finances/components/FinacesTable/FinancesTable.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderAnnually/CellAnnually.tsx
- src/stories/containers/Finances/utils/mockData.ts
- src/stories/containers/Finances/utils/utils.ts
-  [X] **Still pending in breakpoints >=1439. The header values and the rest of the values in the column should be aligned. **Current Output:**  The values aren't aligned with the header values. 
Fix some issues in the feature
> Correct borders in the table and fix  the same title

- src/stories/containers/ActorProjects/components/ProjectOwnerChip/ProjectOwnerChip.tsx
- src/stories/containers/ActorProjects/components/SupportedTeamsAvatarGroup/SupportedTeamsAvatarGroup.tsx
https://trello.com/c/0oAK0jem/299-user-story-tpd-11-projects-overview-v1
Added a tooltip for the owner chip and the supporters
> [SES-299] Participants tooltips

- src/stories/components/svg/ArrowOutline.tsx
- src/stories/containers/Finances/components/CardCoreUnitThirdLevelBudget/CardCoreUnitThirdLevelBudget.stories.tsx
- src/stories/containers/Finances/components/CardCoreUnitThirdLevelBudget/CardCoreUnitThirdLevelBudget.tsx
This add the card for third level of the page
> [SES-294] Add card for core units third level

- src/core/models/dto/snapshotAccountDTO.ts
- src/stories/containers/ActorsTransparencyReport/ActorsTransparencyReportContainer.tsx
- src/stories/containers/ActorsTransparencyReport/useActorsTransparencyReport.tsx
- src/stories/containers/TransparencyReport/TransparencyReport.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/AccountsSnapshotTabContainer.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/api/queries.ts
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/useAccountsSnapshotTab.ts
- src/stories/containers/TransparencyReport/useTransparencyReport.tsx
https://trello.com/c/0oAK0jem/299-user-story-tpd-11-projects-overview-v1
Display the snapshot last update instead of budget statement last update when the account snapshot tab is active and keep the previous behavior when the other tabs are active
> [SES-299] Show snapshot last update on transparency reporting page

- pages/core-unit/[code]/finances/reports/index.tsx
- pages/ecosystem-actors/[code]/finances/reports/index.tsx
- src/core/hooks/useBudgetStatementPager.ts
- src/core/hooks/useTransparencyReporting.ts
- src/stories/containers/ActorsTransparencyReport/ActorsTransparencyReportContainer.tsx
- src/stories/containers/ActorsTransparencyReport/useActorsTransparencyReport.tsx
- src/stories/containers/TransparencyReport/TransparencyReport.tsx
- src/stories/containers/TransparencyReport/transparencyReportAPI.ts
- src/stories/containers/TransparencyReport/useTransparencyReport.tsx
The account snapshot data wasn't considered when navigating the finances page. Now it is fixed
> [SES-QC-310] Fix finances navigation

- src/stories/containers/Finances/FinacesContainer.tsx
This is for add SEO for the Finances Page
> [SES-294] Add SEO for the page

- src/stories/containers/ActorProjects/components/DeliverableViewModeToggle/DeliverableViewModeToggle.tsx
- src/stories/containers/ActorProjects/components/ProjectCard/ProjectCard.tsx
- src/stories/containers/ActorProjects/components/ViewAllButton/ViewAllButton.tsx
Allow to expand/collapse the deliverables, change between the deliverables view mode (compacted/detailed), and add a background when the deliverables are expanded.
> [SES-299] Expand/collapse deliverables

- src/stories/containers/Finances/FinacesContainer.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChartFilter/BreakdownChartFilter.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChartSection.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/useBreakdownChart.ts
- src/stories/containers/Finances/components/FiltersTable/FilterTable.tsx
- src/stories/containers/Finances/components/FinacesTable/FinancesTable.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderAnnually/CellAnnually.tsx
This remove the borders in the last row when the others rows (footer) appears
> Remove borders when others is present

- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/MakerDAOChartMetrics.stories.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/MakerDAOChartMetrics/MakerDAOChartMetrics.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/MakerDAOExpenseMetrics.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/TitleFilterComponent.tsx
https://trello.com/c/Dy3KazCU/305-eml-1-expense-metrics-line-chart
This add responsive for chart line
> Add responsive in chart line

- src/stories/containers/ActorProjects/ActorProjectsContainer.tsx
- src/stories/containers/ActorProjects/components/ProjectCard/ProjectCard.tsx
- src/stories/containers/ActorProjects/components/ProjectList/ProjectList.tsx
https://trello.com/c/wAk6GR11/302-tpd-14-non-project-owner-view
Add the supported projects section where all the project supported by the active ecosystem actor are listed
> [SES-302] Supported projects section

- next.config.js
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/MakerDAOChartMetrics/MakerDAOChartMetrics.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/useMakerDAOExpenseMetrics.tsx
- src/stories/containers/Finances/utils/types.ts
https://trello.com/c/Dy3KazCU/305-eml-1-expense-metrics-line-chart
Allow to toggle on/off the data throughout the legend
> [EML-1] feat: Should allow to toggle on/off the data throughout the legend on Expense Metrics Line Chart

- next.config.js
- src/stories/containers/EndgameBudgetContainerSecondLevel/EndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerSecondLevel/useEndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerThirdLevel/EndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/EndgameBudgetContainerThirdLevel/useEndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChart/BreakdownChart.tsx
Show the Breakdown Chart at levels 2 and 3
> fix: [BC-1.1] Prepare the Breakdown Chart for all levels

- src/stories/containers/Actors/useActors.ts
Sorting by scope on Ecosystem Actors broke the entire UI, now the issues have been fixed
> Fix Ecosystem Actors sorting by scope

- src/stories/containers/ActorProjects/components/DeliverableCard/DeliverableCard.tsx
- src/stories/containers/ActorProjects/components/KeyResults/KeyResults.tsx
- src/stories/containers/ActorProjects/components/KeyResults/MaybeScrollableList.tsx
- src/stories/containers/ActorProjects/components/ProjectCard/ProjectCard.stories.tsx
- src/stories/containers/ActorProjects/components/ProjectCard/ProjectCard.tsx
Sometimes the deliverable cards had different sizes due to how many key result items each one of them had, now all the key results lists on the same row have the same height no matter how many elements each one of them has.
> [SES-299] Fix key results component height

- src/stories/containers/ActorProjects/ActorProjectsContainer.tsx
- src/stories/containers/ActorProjects/components/ProjectCard/ProjectCard.tsx
- src/stories/containers/ActorProjects/components/ProjectList/ProjectList.tsx
- src/stories/containers/ActorProjects/useActorProjectsContainer.tsx
Apply filter to the supported projects and show "No result founds" if there are no results
> [SES-299] Apply filters to supported projects

- src/stories/containers/ActorProjects/ActorProjectsContainer.tsx
- src/stories/containers/ActorProjects/components/ProjectList/ProjectList.tsx
Fix filtering messaging on the supported projects section
> [SES-299] Supported projects filtering

- src/stories/containers/ActorProjects/components/KeyResults/KeyResults.tsx
- src/stories/containers/ActorProjects/components/ProjectFilters/ProjectFilters.tsx
- src/stories/containers/ActorProjects/components/ProjectStatusChip/ProjectStatusChip.tsx
On mobile when the deliverables has no key results it shows a message instead of not displaying anything at all.
> [SES-299] Show "no key result" msg on mobile & fix filter chips size

- pages/finances/index.tsx
- src/stories/containers/EndgameBudgetContainerSecondLevel/useEndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerThirdLevel/useEndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/Finances/FinacesContainer.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
- src/stories/containers/Finances/useFinances.tsx
- src/stories/containers/Finances/utils/utils.ts
> feat: BSN-1 Budget Summary + Navigation

- src/stories/containers/ActorProjects/components/DeliverableCard/DeliverableCard.tsx
- src/stories/containers/ActorProjects/components/KeyResults/KeyResults.tsx
- src/stories/containers/ActorProjects/components/MilestoneLink/MilestoneLink.tsx
- src/stories/containers/ActorProjects/components/ProjectCard/ProjectCard.tsx
Change the logic for the deliverables section on the different modes, added the milestones link and change the behavior of the deliverables title
> [TPD-1] Apply Project cards corrections

- src/stories/containers/RecognizedDelegates/useRecognizedDelegates.ts
Some numbers were NaN and the chart was not showing up, now the source of the issue is solved
-  Recognized Delegate's view. Key Stats section. **Expected Output:**  In the Percentage of Total DAO Expense card if there are no values or the values are zero, the values reflected should be 0 and the pie chart should have a placeholder when there are no values to show. **Current Output: ** NAN and NaN are displayed and the pie chart is not visible causing a big space.
> [QC-r2] Fix doughnut chart NaN numbers

- src/stories/components/SESTooltip/SESTooltip.tsx
- src/stories/containers/Actors/components/ActorItem/ActorItem.tsx
- src/stories/containers/Actors/components/ActorItem/GroupedScopes.tsx
- src/stories/containers/Actors/components/ScopeChip/ScopeChip.tsx
- src/stories/containers/EndgamePhaseOneProgress/components/RoadmapTimeline/RoadmapTimeline.tsx
Now when there are more than 2 scopes they're grouped to fit in the space they have
> [QC-r2] accomodate EA scopes

- src/stories/containers/ActorProjects/components/ProjectCard/ProjectCard.tsx
Fix the font size of the deliverables title on the mobile
> [TPD-1] Fix deliverables font size

- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChart/BreakdownChart.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChartSection.stories.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/utis.ts
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
- src/stories/containers/Finances/utils/types.ts
https://trello.com/c/GLeuvMJI/323-bc-13-breakdown-chart-ability-to-change-granularity
Fix issues in breakdown chart
> Fix the stories and add hover

- src/stories/containers/EndgameBudgetContainerSecondLevel/EndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerThirdLevel/EndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/DelegateExpenseTrend/DelegateExpenseTrendItem.stories.tsx
- src/stories/containers/Finances/components/DelegateExpenseTrend/DelegateExpenseTrendItem.tsx
- src/stories/containers/Finances/components/DelegateExpenseTrend/HeaderDelegateExpense.stories.tsx
- src/stories/containers/Finances/components/SectionPages/DelegateExpenseTrendFinances/DelegateExpenseTrendFinances.stories.tsx
- src/stories/containers/Finances/components/SectionPages/DelegateExpenseTrendFinances/DelegateExpenseTrendFinances.tsx
- src/stories/containers/Finances/components/SectionPages/DelegateExpenseTrendFinances/ExpenseReportsFilters.tsx
- src/stories/containers/Finances/components/SectionPages/DelegateExpenseTrendFinances/useDelegateExpenseTrendFinances.tsx
- src/stories/containers/Finances/utils/utils.ts
Fix issues in dark mode in the expense report/filter section
> [MER-1] Fix expense report filters

- src/stories/containers/Finances/components/DelegateExpenseTrend/DelegateExpenseTrendItem.tsx
- src/stories/containers/Finances/components/SectionPages/DelegateExpenseTrendFinances/DelegateExpenseTrendFinances.tsx
- src/stories/containers/Finances/components/SectionPages/DelegateExpenseTrendFinances/ExpenseReportsFilters.tsx
- src/stories/containers/Finances/utils/utils.ts
> [MER-1] Fix expense reports header

- src/stories/containers/TransparencyReport/components/AccountsSnapshot/useAccountsSnapshot.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/utils/expenseComparisonUtils.tsx
Fix the empty headers on the snapshot expenses comparison when there are not off-chain data
> [QC-r2] Fix snapshot expense comparison header

- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChart/BreakdownChart.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChartFilter/BreakdownChartFilter.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/useBreakdownChart.ts
Fix issues in the breakdown chart relate with the bar with and some colors
> [SES-304] Fix issues relate BreakDownChart

- .vscode/settings.json
- pages/delegates/index.tsx
- src/core/businessLogic/recognizedDelegate.ts
- src/core/models/dto/delegatesDTO.ts
- src/core/utils/dictionary.js
- src/core/utils/string.ts
- src/stories/containers/RecognizedDelegates/RecognizedDelegates.stories.tsx
- src/stories/containers/RecognizedDelegates/RecognizedDelegatesContainer.tsx
- src/stories/containers/RecognizedDelegates/api/RecognizedDelegatesAPI.ts
- src/stories/containers/RecognizedDelegates/useRecognizedDelegates.ts
Change the queries used to fetch the numbers of the delegates page for the analytics query
> fix: recognized delegate number source

- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChart/BreakdownChart.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/MakerDAOChartMetrics.stories.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/MakerDAOChartMetrics/MakerDAOChartMetrics.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/MakerDAOExpenseMetrics.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/useMakerDAOExpenseMetrics.tsx
- src/stories/containers/Finances/utils/mockData.ts
- src/stories/containers/Finances/utils/types.ts
- src/stories/containers/Finances/utils/utils.ts
Allow to enable/disable visually the series and fix the stacked mode in the chart
> [EML-1] Fix line chart axis status

- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChart/BreakdownChart.tsx
Fixed the bar shadow color on hover and the tooltip colors
> [BC-11] Fix breakdown chart shadow colors

- src/stories/containers/TransparencyReport/components/AccountsSnapshot/utils/expenseComparisonUtils.tsx
Some numbers in the expenses comparison of the snapshot section was showing undefined values
> [QC-r2] Fix snapshot expenses comparison numbers

- src/stories/containers/TransparencyReport/components/AccountsSnapshot/utils/expenseComparisonUtils.tsx
Fix undefined values on account snapshot
> [QC-r2] Fix snapshot expenses with no off chain data

- src/stories/containers/EndgameBudgetContainerSecondLevel/EndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerSecondLevel/useEndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerThirdLevel/EndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/EndgameBudgetContainerThirdLevel/useEndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChart/BreakdownChart.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChartSection.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/useBreakdownChart.ts
Persist the legend status when changing the year or theme mode
> [BC-1] Persist breakdown chart legend status

- src/stories/containers/EndgameBudgetContainerSecondLevel/EndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerSecondLevel/useEndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerThirdLevel/EndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/EndgameBudgetContainerThirdLevel/useEndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderMonthly/CellMonthly.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/CardLegend.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/utils.ts
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/CardChartOverview.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
Add Swiper in the navigation card, when there is a lot items
**RF59:** Should add the swiper for the third level in Doughnut Chart
> Add Swiper in the table size and when there is more than five items

- src/stories/containers/FinancesOverview/components/YearPicker/YearPicker.tsx
- src/stories/containers/FinancesOverview/useFinancesOverview.ts
Show the current year (2024) in the finances year range.
> [QC] Fix finances year range

- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/CardLegend.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
Solving issues in the summary plus navigations
> Show all the budget

- src/stories/containers/FinancesOverview/components/CostBreakdownTable/ByBudgetTableRow.tsx
- src/stories/containers/FinancesOverview/components/CostBreakdownTable/ByExpenseCategoryTableRow.tsx
- src/stories/containers/FinancesOverview/components/CostBreakdownTable/CostBreakdownTable.tsx
- src/stories/containers/FinancesOverview/useFinancesOverview.ts
replace the prediction by the actuals field in the breakdown table
> [QC] replace prediction by actuals

- src/stories/containers/RoadmapMilestones/components/RoadmapTimeline/RoadmapTimeline.tsx
Add a View All button at the end of the milestones on mobile to show all the milestones in the list (presentation only)
> [RMV-1] Add view all button

- src/stories/containers/FinancesOverview/components/CostBreakdownTable/ByBudgetTableHeader.tsx
- src/stories/containers/FinancesOverview/components/CostBreakdownTable/ByExpenseCategoryTableHeader.tsx
- src/stories/containers/FinancesOverview/components/ExpensesChart/ExpensesChart.tsx
- src/stories/containers/FinancesOverview/useFinancesOverview.ts
https://trello.com/c/Bg7xkiIf/335-qa-bug-finding-r
Add a tooltip to the finances chart, set 2023 as default year and changed the totals label by "Actuals"
> Hotfix: finances page chart tooltip and breakdown table labels

- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/MakerDAOChartMetrics/MakerDAOChartMetrics.tsx
- src/stories/containers/Finances/utils/utils.ts
Add correct format to the legend
> [POWER-305-eml] Add correct formatter for line chart quarterly

- src/core/utils/dictionary.js
- src/stories/containers/RoadmapMilestones/components/MilestoneDetailsCard/MilestoneDetailsCard.stories.tsx
- src/stories/containers/RoadmapMilestones/components/MilestoneDetailsCard/MilestoneDetailsCard.tsx
- src/stories/containers/RoadmapMilestones/components/MilestoneDetailsCard/MilestoneProgress.tsx
- src/stories/containers/RoadmapMilestones/components/MilestoneDetailsCard/PercentageProgressBar.tsx
- src/stories/containers/RoadmapMilestones/components/MilestoneDetailsCard/StatsData.tsx
Implement the Milestones details card
> [RMV-1] Implement the Milestones details card aside

- src/stories/containers/RoadmapMilestones/components/MilestoneDetailsCard/Coordinators.tsx
- src/stories/containers/RoadmapMilestones/components/MilestoneDetailsCard/EcosystemAcotrs.tsx
- src/stories/containers/RoadmapMilestones/components/MilestoneDetailsCard/MilestoneDetailsCard.tsx
Added a UI section for the coordinators and ecosystem actors for the milestones details card
> [RMV-1] Add coordinators and ecosystem actors data

- src/stories/containers/Finances/components/SectionPages/DelegateExpenseTrendFinances/ExpenseReportsFilters.tsx
Removed the option budget from the metric select in the Expense reports section
> [MER-1] Remove budget metric

- src/stories/containers/Finances/components/DelegateExpenseTrend/DelegateExpenseTrendItem.stories.tsx
- src/stories/containers/Finances/components/DelegateExpenseTrend/DelegateExpenseTrendItem.tsx
- src/stories/containers/Finances/components/SectionPages/DelegateExpenseTrendFinances/DelegateExpenseTrendFinances.tsx
Fix the links on the View button of the expense reports section
> [MER-1] Fix expense reports links

- src/stories/containers/EndgameBudgetContainerSecondLevel/EndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerThirdLevel/EndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/MakerDAOChartMetrics.stories.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/MakerDAOExpenseMetrics.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/TitleFilterComponent.tsx
Changed the title of the expense metrics to "<budget name> Expense Metrics"
> [EML-1] Add custom expense metrics titles

- src/stories/containers/EndgameBudgetContainerSecondLevel/useEndgameBudgetContainerSecondLevel.tsx
- src/stories/containers/EndgameBudgetContainerThirdLevel/useEndgameBudgetContainerThirdLevel.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChart/BreakdownChart.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderMonthly/CellMonthly.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterFallChartSection/useReservesWaterFallChart.tsx
- src/stories/containers/Finances/useFinances.tsx
- src/stories/containers/Finances/utils/utils.ts
> Fix/issues BS+N version 5

- src/stories/containers/Finances/api/queries.ts
- src/stories/containers/Finances/components/SectionPages/DelegateExpenseTrendFinances/useDelegateExpenseTrendFinances.tsx
> [MER-1] Expense reports query typo

- src/stories/components/SingleItemSelect/SingleItemSelect.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChartFilter/BreakdownChartFilter.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
- src/stories/containers/Finances/components/SectionPages/DelegateExpenseTrendFinances/ExpenseReportsFilters.tsx
- src/stories/containers/Finances/utils/types.ts
- src/stories/containers/Finances/utils/utils.ts
> [BSN-330] Add optional label in the mobile

- src/stories/containers/Finances/components/HeaderTable/HeaderAnnually/CellAnnually.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderMonthly/CellMonthly.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderQuarterly/CellQuarterly.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderSemiAnnual/CellSemiAnnual.tsx
- src/stories/containers/Finances/utils/utils.ts
Fix issues relate with the values in the header
> Fix the name in relation with the api

- src/stories/containers/RoadmapMilestones/components/MilestoneDetailsCard/DeliverablesSection.tsx
Add a button to expand/collapse the deliverables in the milestones details card
> [RMV-1] Allow to expand/collapse the deliverables

- src/stories/containers/RoadmapMilestones/components/MilestoneDetailsCard/DeliverablesSection.tsx
Update the deliverables title when they are expanded/collapsed
> [RMV-1] Update deliverables title on expand

- src/stories/containers/RoadmapMilestones/components/MilestoneDetailsCard/StatsData.tsx
Add tooltip to the target date
> [RMV-1] Added target date tooltip

- src/stories/containers/RoadmapMilestones/components/MilestoneCard/MilestoneCard.tsx
- src/stories/containers/RoadmapMilestones/components/MilestoneCard/MobileProgressBar.tsx
- src/stories/containers/RoadmapMilestones/components/MilestoneDetailsCard/Coordinators.tsx
- src/stories/containers/RoadmapMilestones/components/MilestoneDetailsCard/DeliverablesSection.tsx
- src/stories/containers/RoadmapMilestones/components/MilestoneDetailsCard/EcosystemActors.tsx
- src/stories/containers/RoadmapMilestones/components/MilestoneDetailsCard/MilestoneDetailsCard.tsx
- src/stories/containers/RoadmapMilestones/components/MilestoneDetailsCard/MilestoneProgress.tsx
- src/stories/containers/RoadmapMilestones/components/MilestoneDetailsCard/PercentageProgressBar.tsx
- src/stories/containers/RoadmapMilestones/components/MilestoneDetailsCard/StatsData.tsx
- styles/theme/dark.ts
Fixed the dark mode on the milestones cards
> [RMV-1] Milestones dark mode

- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChart/BreakdownChart.tsx
> Add min and max for the chart when there is not data

- src/core/utils/dictionary.js
- src/stories/containers/Finances/api/queries.ts
- src/stories/containers/Finances/components/SectionPages/DelegateExpenseTrendFinances/DelegateExpenseTrendFinances.tsx
- src/stories/containers/Finances/components/SectionPages/DelegateExpenseTrendFinances/ExpenseReportsFilters.tsx
- src/stories/containers/Finances/components/SectionPages/DelegateExpenseTrendFinances/useDelegateExpenseTrendFinances.tsx
- src/stories/containers/Finances/useFinances.tsx
- src/stories/containers/Finances/utils/utils.ts
> [MER-1] Fix expense reports alignment

- src/stories/containers/TransparencyReport/components/AccountsSnapshot/utils/expenseComparisonUtils.tsx
Show the percentage of the Expense comparison section of the account snapshots correctly when there are not offchain data
> [QC] Fix expense comparison percentage when there are not off chain data

- src/stories/containers/Finances/components/SectionPages/DelegateExpenseTrendFinances/useDelegateExpenseTrendFinances.tsx
Avoid query revalidation on the expense reports page as the data is immutable
> [MER-1] Avoid query revalidation

- src/stories/containers/Finances/components/SectionPages/CardChartOverview/CardChartOverview.tsx
Show the filters of the first section when there are many items
> [BSN-1] Show filters on the third level

- src/stories/containers/Finances/components/CardNavigationFinance/CardNavigationFinance.tsx
- src/stories/containers/Finances/components/SectionPages/CardsNavigation/CardsNavigation.tsx
Show 5 navigation cards on desktop and 3 in tablet, if there are more, then show a carrousel to avoid having multiple rows
> [BSN-1] Show only one row of navigation cards

- src/stories/containers/Finances/components/SectionPages/CardsNavigation/CardsNavigation.tsx
Now the pages of the carousel change by half page instead of cards 1 by 1
> [BSN-1] Split the carousel into pages

- src/stories/containers/Finances/components/HeaderTable/HeaderAnnually/HeaderAnnually.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderSemiAnnual/HeaderSemiAnnual.tsx
- src/stories/containers/Finances/useFinances.tsx
Change the No-Name text for the code Path text
> [BSN-1] Fix the No-name with the code path

- src/stories/containers/Finances/components/FinacesTable/FinancesTable.tsx
- src/stories/containers/Finances/components/LinkCellComponent/LinkCellComponent.tsx
When navigating through the table items keep the table filter status
> [BSN-1] Keep the table filter status when navigating to a deeper level

- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
When the windows are resized in the finances page it was redirecting to the finances root page when it should keep in the same page
> [BSN-1] Fix resize the windows was redirecting to finances

- src/stories/containers/Actors/components/ActorLastModified/ActorLastModified.tsx
- src/stories/containers/Finances/components/DelegateExpenseTrend/DelegateExpenseTrendItem.stories.tsx
- src/stories/containers/Finances/components/DelegateExpenseTrend/DelegateExpenseTrendItem.tsx
> Fix the arrow and icon in the expense report items

- src/stories/components/Pagination/BreadCrumbWithIcons.tsx
Close the modal when some item are selecting
> Add function to close the modal

- src/core/utils/const.ts
- src/stories/containers/Finances/utils/utils.ts
If a suitable in finances has sub budgets they should be shown as rows, but show up to 16 rows in total
> [BSN-1] Show rows and other if necessary in the subtables

- src/stories/containers/Finances/components/SectionPages/ReservesWaterFallChartSection/useReservesWaterFallChart.tsx
Show the correct filers in each level
> Fix the filters per level

- src/stories/containers/Finances/components/SectionPages/ReservesWaterFallChartSection/utils.ts
Fix the colors of the line in dark mode and when not change values put green color for the lines
> Fix the color line in dark mode

- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/MakerDAOExpenseMetrics.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/MakerDAOExpenseMetricsSkeleton.tsx
Add a loading skeleton on the expense metrics section
> [BSN-1] Expense metrics skeleton

- src/stories/containers/Finances/components/DelegateExpenseTrend/DelegateExpenseTrendItem.tsx
- src/stories/containers/Finances/components/SectionPages/ExpenseReports/ExpenseReportsFilters.tsx
Remove off chain metric and set the on chain metric in the expense reports filter
> [BSN-1] Fix on chain metric on the expense reports section

- src/stories/containers/Finances/components/FinacesTable/CellTable.tsx
- src/stories/containers/Finances/components/FinacesTable/FinancesTable.tsx
- src/stories/containers/Finances/components/LinkCellComponent/LinkCellComponent.tsx
- src/stories/containers/Finances/utils/types.ts
- src/stories/containers/Finances/utils/utils.ts
Remove the link of the "Others" row as it is a summary and not a budget
> [BSN-1] Remove "Others" link

- src/core/utils/dictionary.js
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChartFilter/BreakdownChartFilter.tsx
Shorten the Protocol Outflow label on mobile in the breakdown chart section
> [BSN-1] Protocol Outflow on mobile in the breakdown chart section

- src/stories/components/IconTitle/IconTitle.tsx
Fix icon width on mobile when the title is too long
> fix: finances icon title width

- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
If the period was Monthly or Quarterly and then change to Annually the selected metrics was just 1-3 but they had to be the max amount of allowed metrics for the annually period
> [BSN-1] Restore max amount of metric in annual when the granularity is changed to Annual

- src/stories/containers/Finances/utils/chartTooltip.ts
Fix tooltip when the names are too long
> [BSN-1] Fix breakdown chart tooltip

- src/stories/containers/Finances/components/HeaderTable/HeaderAnnually/HeaderAnnually.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderMonthly/HeaderMonthly.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderQuarterly/HeaderQuarterly.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderSemiAnnual/HeaderSemiAnnual.tsx
When the table header titles has a very long title it was out of its container
> [BSN-1] Fix table header long titles

- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
When the finances page load on mobile resolution the URL anchors of the breakdown table were adding to the URL
> [BSN-1] Update URL anchor on mobile load

- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/useReservesWaterfallChart.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/utils.ts
Fix the analytics for the waterfall
> [RC-1] Included all the analytics for the level budgets

- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/useReservesWaterfallChart.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/utils.ts
Fix the filter in waterfall chart
> [RC-1]Add all the budgets

- src/stories/components/SingleItemSelect/SingleItemSelect.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChartSection.tsx
- src/stories/containers/Finances/components/FinacesTable/FinancesTable.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
> [BSN-1] Fix finances issues

- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/InformationBudgetCapOverView/InformationBudgetCapOverView.tsx
- src/stories/containers/Finances/components/OverviewCardMobile/OverviewCardMobile.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/CardChartOverview.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
The card overview was showing the prediction/forecast
> [BSN-1] Remove prediction from overview card

- src/stories/containers/Finances/components/HeaderTable/HeaderQuarterly/HeaderQuarterly.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
Fix when the text its to long, then a scroll add in the title of the header in the table
> [BS-1] Add min height for the title

- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChart/BreakdownChart.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/MakerDAOChartMetrics/MakerDAOChartMetrics.tsx
- src/stories/containers/Finances/components/WaterfallChart/WaterfallChart.tsx
- src/stories/containers/Finances/utils/utils.ts
Made the legend of the chart for mobile and monthly homogeneous
> [BSN-1] Add the same behavior in mobile for monthly componente

- src/stories/containers/Finances/components/SectionPages/BreakdownTable/BreakdownTableSkeleton/BreakdownTableBodySkeleton/BreakdownTableBodySkeleton.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/BreakdownTableSkeleton/BreakdownTableBodySkeleton/HeaderRowSkeleton.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/BreakdownTableSkeleton/BreakdownTableBodySkeleton/HeaderRowSkeletonTitle.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/BreakdownTableSkeleton/BreakdownTableBodySkeleton/RowSkeleton.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/BreakdownTableSkeleton/HeaderBreakdownTableSkeleton.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/BreakdownTableSkeleton/HeaderTitleSkeleton.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/BreakdownTableSkeleton/ItemHeaderSkeleton.tsx
> [BS-1] Add CSS breakpoint to avoid render container before loading

- pages/core-unit/[code]/finances/reports/index.tsx
- src/stories/containers/TransparencyReport/transparencyReportAPI.ts
Fixed the navigation. The issue was related to differences between the timezones of the server and clients
> [QC] Fix CU reports month navigation

- src/stories/components/Pagination/BreadCrumbWithIcons.tsx
Fix long names with an ellipsis on mobile
> [BSN-1] Fix mobile breadcrumb long names

- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/SectionPages/ExpenseReports/ExpenseReports.tsx
Add component of not result when there its not result
> [BS-1] Add component for not result in expense report

- src/stories/containers/Finances/components/FinacesTable/FinancesTable.tsx
- src/stories/containers/Finances/components/HeaderTable/utils.ts
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/BreakdownTableSkeleton/BreakdownTableBodySkeleton/HeaderRowSkeletonTitle.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
Fix the order of of the metrics to match with the analiticys
> [BS-1] Fix/issues table number

- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
Add Swiper when there is to many items
> [SB-1] Fix/issues relate with doughnut chart

- src/stories/containers/Finances/components/FinacesTable/FinancesTable.tsx
Add correct color for annual metric in the table
> Add correct color for annual

- pages/endgame/index.tsx
- src/stories/containers/Endgame/components/BudgetTransitionChart/BudgetTransitionChart.tsx
- src/stories/containers/Finances/api/queries.ts
https://trello.com/c/K6BCBa9u/293-met-14-visualization-of-budget-transition-status
The years are not correctly aligned with the x-axis Q1 items
> fix: transition status chart yeras on mobile

- src/stories/containers/Finances/api/queries.ts
Fix the NAN value return by the endYear value in the finances page query 
Fix the way that end year is calculate to get a valid value for filter in the query
> fix: Fix the query analytics in the Finances

- src/stories/containers/Finances/components/CardNavigationMobile/CardNavigationMobile.tsx
Fix the  percent value in mobile that show incorrect percent for the same values.
The percent in mobile is different that the one that is show in  desktop even although, values to calculate it are the same
> fix:Fix the percent in mobile show diferent value

- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/CardLegend.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
Fix the correct items in each columns when there are to many items .
Some columns have more items that the other column, when should be the same  number
> fix: Fix the number of items show in the columns

- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/MakerDAOChartMetrics.stories.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/MakerDAOChartMetrics/MakerDAOChartMetrics.tsx
Fix spacing between Expense Metrics and Reserves sections
> [BSN-1] Fix expense metrics spacing

- src/core/utils/humanization.ts
Fix negative zeros on the breakdown table
> [BSN-1] Fix negative zero

- src/stories/components/SingleItemSelect/SingleItemSelect.tsx
Hide scroll bar in the year picker of the finances breadcrumb
> [BSN-1] Fix year select default scroll bar

- src/stories/containers/Finances/components/BreakdownChartSection/useBreakdownChart.ts
- src/stories/containers/Finances/components/BreakdownChartSection/utils.ts
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
- src/stories/containers/Finances/useFinances.tsx
…correct name
Fix the name in the last level for breakdown chart and drought chart Some of the  code path use to match came with some * in the code path so its not match
> [SB-1]  Fix the last level the doughnut and breakdown chart don't

- src/stories/containers/Finances/components/ReservesWaterfallFilters/ReservesWaterfallFilters.tsx
Change the label in the filter of waterfall chart
> [SB-1] Change the name of waterfall filters

- src/stories/containers/Endgame/components/BudgetTransitionChart/BudgetTransitionChart.tsx
Update Chart legend in the transition status section of the endgame page
> [QA] Update transition chart legend

- src/stories/containers/Endgame/components/BudgetTransitionStatusSection/BudgetTransitionStatusSection.tsx
Update the Budget transition status subtitle of the endgame page
> [QA] Update transition subtitle

- src/stories/containers/Endgame/components/BudgetStructureSection/BudgetStructureSection.tsx
- src/stories/containers/Endgame/components/TotalBudgetContent/TotalBudgetContent.tsx
Change "Budgets" by "Budget" everywhere (except titles/subtitles)
> [QA] Update budget text to make it singular everywhere

- pages/endgame/index.tsx
- src/core/utils/dictionary.js
- src/stories/components/SingleItemSelect/SingleItemSelect.tsx
- src/stories/containers/Endgame/EndgameContainer.tsx
- src/stories/containers/Endgame/components/BudgetStructureSection/BudgetStructureSection.tsx
- src/stories/containers/Endgame/components/BudgetStructureSection/BudgetStructureSectionSkeleton.tsx
- src/stories/containers/Endgame/components/SectionHeader/SectionHeader.tsx
- src/stories/containers/Endgame/useEndgameContainer.ts
Add a year picker to show the data of only one year in the budget structure section of the endgame transition page
> [QA] Budget structure year picker

- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/utils.ts
Fix duplicate items in the table that have the same code path At this point there some code-Path are the same the different */*, so it's have to be the same and delete the duplicate items.
> Fix duplicate budgets same code-Path(*/*) in the table

- src/stories/containers/Finances/components/CardNavigationMobile/CardNavigationMobile.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
- src/stories/containers/Finances/components/SectionPages/CardsNavigation/CardsNavigation.tsx
- src/stories/containers/Finances/useFinances.tsx
- src/stories/containers/Finances/utils/types.ts
Fix the sum of the all values in the pie chart and the mobile view should be 100%.
Right now because the round some times the sum of all items its less or more than 100%
> [SB-1]Fix sum values of the items in the  pie chart is not 100%

- src/core/enums/zIndexEnum.ts
Fix apache echart tooltip overlap to header end the navigation
> [SB-1] Give a big number to avoid big zIndex of tooltip Apache Echart

- src/stories/containers/Endgame/components/SectionHeader/SectionHeader.tsx
> [QA] Fix year picker styles

- src/stories/containers/Finances/components/SectionTitle/SectionTitle.tsx
Replace the external link icon with a copy icon
> [QA] Change link icon

- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
- src/stories/containers/Finances/components/SectionPages/CardsNavigation/CardsNavigation.stories.tsx
Fix the values in the table that are  no values
When there are  only one subBuget the same budget are add twice
> [SB-1] Fix  values from the table are missing

- src/stories/containers/Finances/components/SectionTitle/SectionTitle.tsx
> [QA] Update copy button text

- src/stories/containers/Finances/components/SectionPages/ExpenseReports/useExpenseReports.tsx
- src/stories/containers/Finances/components/SectionTitle/SectionTitle.tsx
Change the default order of the expense report table, now it is sorted by last activity
> [QA] Change expense report default sorting

- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/useReservesWaterfallChart.tsx
Avoid reset filter of budgets, when the granularity change
> [SB-1] Avoid reset budget filter in waterfall chart

- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/CardNavigationFinance/CardNavigationFinance.tsx
- src/stories/containers/Finances/components/CardNavigationMobile/CardNavigationMobile.tsx
- src/stories/containers/Finances/components/SectionPages/CardsNavigation/CardsNavigation.tsx
add the budget code on the navigation cards
> [QA] Add code in navigation card

- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/useReservesWaterfallChart.tsx
Add the default value for categories in the waterfall chart
> [SB-1] Reset category filter to initial state

- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChart/BreakdownChart.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/MakerDAOChartMetrics/MakerDAOChartMetrics.tsx
- src/stories/containers/Finances/utils/chartTooltip.ts
Fix the problem the tooltip cut  because isn't in the right position. 
At this moment in 768 and 1024 position the tooltip of breakdown chart cut in left side
> [SB] Fix the position of the tooltip for 768 and 1024 resolution

- src/stories/components/CustomMultiSelect/CustomMultiSelect.tsx
- src/stories/containers/Finances/components/FiltersTable/FilterTable.tsx
When one metric is select only show the same placeholder. When only one metric is select then should be show the  metric instead of placeholder with number of items
> [SB-1] Fix when only one metric is select show the name of the metric

- src/stories/components/CustomMultiSelect/CustomMultiSelect.tsx
- src/stories/containers/Finances/components/FiltersTable/FilterTable.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/utils.ts
Add the brackets for items count in the multiselect component Fix the gap in the filters to adjust the big metrics
> [QA-338] Fix the multi-selected to reflect items select in brackets

- src/stories/components/SingleItemSelect/SingleItemSelect.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChart/BreakdownChart.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChartFilter/BreakdownChartFilter.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChartSection.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/utils.ts
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/MakerDAOChartMetrics/MakerDAOChartMetrics.tsx
- src/stories/containers/Finances/utils/chartTooltip.ts
- src/stories/containers/Finances/utils/utils.ts
Add the metric select to tooltip and  remove budget word for the legend of breakdown chart The information show in the chart its relate with other metric too, son remove budget word help to let it clear
> fix:Add the metric select to tooltip in breakdown chart

- src/core/utils/const.ts
Fix the umbral, when its number less than q, should be despicable
> [BSN-1] Adjust the umbral to one

- src/stories/containers/Finances/utils/chartTooltip.ts
Adjust the umbral to one, for don't show the 0 values
> [SBN-1] Fix the tooltip when there are many items

- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/useReservesWaterfallChart.tsx
Set popover menu to max height of 8 items in the waterfall chart section
> [QA] Adjust multiselect to 8 items

- src/stories/containers/Finances/utils/chartTooltip.ts
Remove the items from the tooltip if the values are cero
[X] Breakdown chart popup when hovering on a specific granularity bar should not show metrics that are 0. Applicable to all levels.
> [QA-338] Filter element that have no cero values

- src/stories/components/SingleItemSelect/SingleItemSelect.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChartFilter/BreakdownChartFilter.tsx
- src/stories/containers/Finances/components/BreakdownTableFinances/BreakdownTableFinances.tsx
- src/stories/containers/Finances/components/FiltersTable/FilterTable.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/BreakdownTable.tsx
Add the fit-content for the height of the popover in the filters
> [QA-338] Fix scroll table bar chart add fit content

- src/stories/containers/Finances/FinancesContainer.tsx
Add the correct description for the main page and center de description with the title
> [QA-338]Add correct description for the main page and center description

- pages/finances/[[...path]].tsx
Changed finances default year to the current year if it is >=Q2 or the previous year if it is Q1
> [QA] Change finances default year

- src/stories/containers/Finances/FinancesContainer.tsx
Add a short tittle for the main page
> [QA-338] Add correct text for the main page

- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
[X] Delete the budget word from the pie chart
> Add funcion to delete budget word

- src/core/utils/string.ts
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/MakerDAOChartMetrics/MakerDAOChartMetrics.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/useMakerDAOExpenseMetrics.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/utils.ts
- src/stories/containers/Finances/utils/utils.ts
Allow the chart of line metric and the breakdown chart
> [QA-338] Allow show negative value breakdown chart and line chart

- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/utils.ts
Remove the space between sign and value in the waterfall
> [QA-338] Remove the space between the sign and value waterfall chart

- src/stories/containers/Finances/components/ReservesWaterfallFilters/ReservesWaterfallFilters.tsx
Allow to show the name of budget when only one its selected and only show number metrics when its mobile
> [QA-338] Allow show name of metric when only one its select waterfall

- src/stories/containers/Finances/components/ReservesWaterfallFilters/BudgetItem.tsx
Fix images in the filter of the waterfall section
> [BSN] Fix waterfall filter image

- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
From 2400px up we should 4 metrics and form 3000 on we show the 5 metrics by default
> [BSN] Change default amount of metrics on bigger desktops

- src/stories/containers/Finances/components/HeaderTable/HeaderAnnually/HeaderAnnually.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderMonthly/HeaderMonthly.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderQuarterly/HeaderQuarterly.tsx
- src/stories/containers/Finances/components/HeaderTable/HeaderSemiAnnual/HeaderSemiAnnual.tsx
Remove overflow in the table header of the breakdown table in finances
> [BSN] Fix firefox overflow on the table header

- src/stories/containers/Finances/components/BreakdownChartSection/utils.ts
https://trello.com/c/L3OMliKC/338-qa-issues-bug-findings-fusion-v1
Allow in the breakdown chart to have negative values and show the correct borders in each bar
> [QA-338] Allow border in the negative values

- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
- src/stories/containers/Finances/utils/utils.ts
using a name extracted by the path if there is not name or code
> [BSN] Remove no-code work and put the path fragment to fix it

- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinancesSkeleton.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/CardChartOverview.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
Add a skeleton to prevent component flickering when the page is being mounted
> [BSN] Add loading skeleton on doughnut

- src/stories/containers/Finances/components/BreakdownChartSection/utils.ts
- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/utils.ts
Avoid big negative number with decimal, replace with cero, for the start point of the waterfall
> [BSN-348] Add the umbral condition for start point

- src/stories/containers/Finances/components/BreakdownChartSection/useBreakdownChart.ts
- src/stories/containers/Finances/components/BreakdownChartSection/utils.ts
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
Fix the unnamed budgets on the first section and second sections, also fixed the colors for the breakdown chart when there are more analytics paths than budgets
> [BSN] Fix unnamed budgets

- src/stories/containers/Finances/components/BreakdownChartSection/useBreakdownChart.ts
- src/stories/containers/Finances/components/BreakdownChartSection/utils.ts
https://trello.com/c/L3OMliKC/338-qa-issues-bug-findings-fusion-v1
Remove the borders from the bottom of each bars, and add only to the top, its in negative or positive values
> Change the behavior of borders in the breakdown chart

- src/core/utils/colors.ts
- src/stories/containers/Finances/components/BreakdownChartSection/utils.ts
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
use the same way to assign colors on the legend of the doughnut chart and the breakdown chart
> fix: use the same colors for the same paths

- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/ItemLegendDoughnut.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
Allow to display "negative" values on the doughnut chart
> Negative values on doughnut chart

- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChartFilter/BreakdownChartFilter.tsx
Make the label of the metric selected on the breakdown chart shorter
> Fix Metric label on tablet

- src/stories/containers/Finances/components/DelegateExpenseTrend/DelegateExpenseTrendItem.tsx
Fixed the metric label on small resolutions
> Fix expense reports metric label

- src/stories/containers/Finances/components/ReservesWaterfallFilters/ReservesWaterfallFilters.tsx
Fix width of the categories field on the waterfall chart
> Fix categories field width on waterfall chart section

- src/stories/containers/Finances/useFinances.tsx
Hide the load more button on levels where there are not items as it was showing up
> Hide load more when there are no items

- src/core/hooks/useBudgetStatementPager.ts
https://trello.com/c/wxhA1BDB/366-bug-no-access-to-march-2024-in-the-ecosystem-actors-expense-reports
Change the dates to be UTC localized to avoid differences between server/client dates
> Improve budget pager dates

- src/stories/containers/ActorsAbout/components/ActorSummary/ActorTitleAbout.tsx
- src/stories/containers/ActorsAbout/components/ActorSummary/ActorTitleWithDescription.tsx
https://trello.com/c/3EWKzArO/343-user-story-eat-21-ecosystem-actors-short-code
Fix the aligned  the header with the body
> [ETA-21] Remove the 960 max-with in ecosystem actor profile

- src/stories/containers/Finances/components/BreakdownChartSection/utils.ts
- src/stories/containers/Finances/utils/chartTooltip.ts
Hide close to 0 values on the breakdown chart
> Hide zero value son the breakdown chart

- src/stories/containers/Finances/components/SectionPages/ExpenseReports/ExpenseReports.tsx
Change the name of the last session of the finances page to budget statement
> Change the text in the Finances page for the last session

- src/core/utils/filters.ts
- src/stories/containers/Finances/components/ReservesWaterfallFilters/ReservesWaterfallFilters.tsx
- src/stories/containers/RecognizedDelegates/components/FilterDelegate/FilterDelegate.tsx
https://trello.com/c/fpeJV0Lo/354-qa-issues-bug-findings-fusion-v2
Add the same behavior for filter in delegate page as multi select filter in the finances page
Recognized delegates filter: spell out the name of the RD if only one RD is selected.[image.png](https://trello.com/1/cards/65fd33949f2746e5c61b515c/attachments/660bad621c332f8bfd2f8fdb/previews/660bad621c332f8bfd2f9107/download/image.png)
> Add the same behavior when one element its select for the delegate

- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/utils.ts
https://trello.com/c/TJJadCh4/345-user-story-eat-22-ecosystem-actors-status-indication
Fix small values waterfall chart
> Fix negative values at the end and check dark mode status

- pages/ecosystem-actors/[code]/finances/reports/index.tsx
https://trello.com/c/wxhA1BDB/366-bug-no-access-to-march-2024-in-the-ecosystem-actors-expense-reports
Changed date to UTC
> Fix ecosystem actors budget pager

- src/stories/containers/Finances/components/SectionPages/ExpenseReports/ExpenseReports.tsx
Add the 's' to the title  in the Budget Statement section
> Correct the name in the last session finances page

- src/stories/containers/Finances/utils/chartTooltip.ts
Allow negative values in the tooltip
> [GI-364] Add absolute value to fix the negative values

- src/core/utils/humanization.ts
Avoid the scientific notation add by toPrecision method to add format for the waterfall chart
> [GI-364] Add function to verify scientific notation

- src/core/utils/const.ts
- src/stories/containers/Finances/components/FinacesTable/FinancesTable.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
- src/stories/containers/Finances/utils/utils.ts
Allow max 13 rows per sub table
> [QA] Limit breakdown table rows

- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
Add empty values on levels where there are not data in the doughnut chart
> [QA] Empty doughnut charts in the last levels

- src/stories/containers/TransparencyReport/components/AccountsSnapshot/utils/reserveUtils.ts
https://trello.com/c/s9JOxwZX/368-change-requests-sprint-review-v3
Hide the empty snapshot balance in the on/off chain reserves of the snapshot accounts
> Hide empty Snapshot Balance

- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
https://trello.com/c/s9JOxwZX/368-change-requests-sprint-review-v3
Make the last level with only one item and zero values gray
> Fix last level doughnut chart color

- src/stories/containers/Finances/components/ReservesWaterfallFilters/BudgetItem.tsx
- src/stories/containers/Finances/components/ReservesWaterfallFilters/ReservesWaterfallFilters.tsx
https://trello.com/c/ol1mo4dH/371-finances-view-general-issues-v3
Avoid that filter overlap with the check mark
> [GI-371] Remove unnecessary checking for the filter

- src/stories/containers/Finances/utils/utils.ts
The finish date should be next year instead the same year
> Fix waterfall chart finish date

- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChartFilter/BreakdownChartFilter.tsx
- src/stories/containers/Finances/components/BreakdownTableFinances/BreakdownTableFinances.tsx
- src/stories/containers/Finances/components/SectionPages/ExpenseReports/ExpenseReportsFilters.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/useReservesWaterfallChart.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/utils.ts
https://trello.com/c/ol1mo4dH/371-finances-view-general-issues-v3
When some metrics are selected on table the filter should float below the title to fit correctly
> Fix finances filter wrap

- src/stories/containers/Actors/components/ActorFilters/ActorFilters.tsx
Fix the issues relate with the ecosystem actors filters
> Add the code to code and fixscrollbar ecosystem actor filter

- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/InformationBudgetCapOverView/InformationBudgetCapOverView.tsx
This change the name in the card and change the margin left for label in the item component
> [QA-369] Change the name and add the same margin

- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChart/BreakdownChart.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/MakerDAOChartMetrics/MakerDAOChartMetrics.tsx
- src/stories/containers/Finances/utils/utils.ts
Fix the breakdown chart and metric chart for small dimensions
> [369-QA]Add properties for charts in 360 dimension's

- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/ItemLegendDoughnut.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
https://trello.com/c/ol1mo4dH/371-finances-view-general-issues-v3
If the values for some items are too small relative to the others, the percentage was close to 0 but it was showing 0%
> Fix doughnut percentages

- src/stories/containers/Finances/components/CardNavigationMobile/CardNavigationMobile.tsx
- src/stories/containers/Finances/useFinances.tsx
Change the percentage of the budget utilization in the cards on mobile and change the budget by net on chain value
> [QA] Fix mobile cards budget utilization

- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/InformationBudgetCapOverView/InformationBudgetCapOverView.tsx
https://trello.com/c/ol1mo4dH/371-finances-view-general-issues-v3
This add the conditional render to css, for better user experience
> [GI-371] Move the conditional to css for better user experience

- src/core/utils/dictionary.js
- src/stories/containers/Finances/components/FinacesTable/FinancesTable.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
Change the name for other budget
> Change the name for the other budget to uncategorized

- src/stories/containers/FinancesOverview/components/HorizontalBudgetBar/HorizontalBudgetBar.tsx
Add more width to bar indication for better user experience
> [QA-369] Add more with for the line

- src/stories/containers/TransparencyReport/components/AccountsSnapshot/AccountsSnapshot.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/CUReserves/CUReserves.tsx
- src/stories/containers/TransparencyReport/components/AccountsSnapshot/useAccountsSnapshot.tsx
This pr remove the Core Units word when ownerType its not a Core-Unit
> [QA-369] Remove the core unit word if not a core unit expense report

- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/useReservesWaterfallChart.tsx
- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/utils.ts
This pr fix the width of the reserve chart in mobile
> [QA369] Fix the width line chart for mobile resolutions

- src/core/utils/humanization.ts
- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/utils.ts
Change the number formating way in the waterfall chart
> [QA] Make numbers in waterfall bars 2 significant digits

- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/SectionPages/CardsNavigation/CardsNavigation.tsx
- src/stories/containers/Finances/useFinances.tsx
Allow to load less items on navigation cards on mobile after the load more button is clicked if there are more than 6 items
> [QA] Allow to load less items on navigation cards mobile

- src/stories/containers/Finances/useFinances.tsx
Sort the navigation cards on mobile by the percentage of budget utilization. Higher on top
> [QA] Sort navigation cards on mobile

- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/CardNavigationMobile/CardNavigationMobile.tsx
- src/stories/containers/Finances/components/SectionPages/CardsNavigation/CardsNavigation.tsx
- src/stories/containers/Finances/useFinances.tsx
Fix the percentage of the budget utilization and the way we display the net on-chain value
> [QA] Fix mobile navigation cards percentages

- src/stories/components/Breadcrumbs/Breadcrumbs.tsx
- src/stories/components/Pagination/BreadCrumbWithIcons.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
- src/stories/containers/Finances/useFinances.tsx
Fix the other in the page when you click in the row in the table
> [QA-376] Add Uncategorized in the page

- .vscode/settings.json
- src/core/utils/dictionary.js
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/MakerDAOChartMetrics.stories.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/useMakerDAOExpenseMetrics.tsx
- src/stories/containers/Finances/utils/types.ts
- src/stories/containers/Finances/utils/utils.ts
Add horizontal lines when annual granularity is selected in the expense metrics chart
> [QA] Add horizontal line when annual is selected

- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/utils.ts
Make bars in the start and final bars sharp on the zero level
> [QA] Make bars sharp on zero values

- src/core/context/BudgetMetricsModalContext.tsx
- src/stories/components/BasicModal/BasicModal.tsx
- src/stories/components/BasicModal/CategoryModalComponent.tsx
- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/BudgetMetricButtonModalTrigger/BudgetMetricButtonModalTrigger.tsx
- src/stories/containers/Finances/components/BudgetMetricsModal/BudgetMetricsModal.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/CardChartOverview.tsx
- src/stories/containers/Finances/useFinances.tsx
> [QA] Add budget metrics modal

- src/stories/containers/Finances/components/BudgetMetricsModal/BudgetMetricsModal.tsx
Remove unnecessary text that was added by accident into the budget metrics modal
> [QA] Remove unnecessary text

- src/stories/containers/Finances/components/BreakdownChartSection/useBreakdownChart.ts
The items with higher values show first now in the breakdown chart
> [QA] Sort by total values the breakdown chart

- src/stories/components/SESTooltip/SESTooltip.tsx
- src/stories/components/SESTooltip/TooltipModalVariant.tsx
On mobile now the tooltips are shown as modals instead as a popup
> [QA] Show tooltip as modals in mobile

- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/InformationBudgetCapOverView/InformationBudgetCapOverView.tsx
Show dashes percentage when the percentage is 0 due right value equal to 0
> [QA] Show dashes when the percentage is zero

- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
https://trello.com/c/YtFMkHoz/378-finances-view-general-issues-v4
The percentage in the tooltip was being displayed with several decimal places
> Fix doughnut chart percentage rounding

- src/stories/containers/TransparencyReport/components/AccountsSnapshot/components/CUReserves/CUReserves.tsx
https://trello.com/c/YtFMkHoz/378-finances-view-general-issues-v4
There was twowords together without spacing in the account snapshot component
> Fix snapshot reserves CU text spacing

- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
In the core units level the budget utilization was calculated using the actuals instead of the net on chains
> Fix budget utilization in the third level

- src/stories/components/Breadcrumbs/Breadcrumbs.tsx
- src/stories/components/Pagination/BreadCrumbWithIcons.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
- src/stories/containers/Finances/useFinances.tsx
Roll back the changes as this is going to be handled in the API side now
> [QA] fix: remove the uncategorized to handle it in the API side

- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
If all the values of the "other" row are zero, the hide the row
> [QA] Fix hide other when all its values are zero

- src/stories/components/CoreUnitCard/CoreUnitCard.tsx
- src/stories/components/CustomTable/ItemCoreUnit/ItemCoreUnit.tsx
All the spaces in the CU items of the CU table go to the CU Profile page, except the expense data and the last activity that goes to expense reports and activity respectively
> Fix Core Unit item links

- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/CardLegend.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DoughnutChartFinances.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/ItemLegendDoughnut.tsx
- src/stories/containers/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
Add a decimal place to the percent in the doughnut chart. Also adjusted the legend container width to fit the legend width
> [QA] Fix doughnut chart percentage

- src/stories/containers/Finances/components/DelegateExpenseTrend/DelegateExpenseTrendItem.tsx
Previously the delegate's budgets were going to the ecosystem actors page instead of its own reporting page
> [QA] Fix delegates link in the buget statement section

- src/core/utils/dictionary.js
- src/stories/components/svg/RadioInputSVG.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/CumulativeFilter/CumulativeFilter.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/CumulativeFilter/CumulativeSelectItem.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/TitleFilterComponent.tsx
https://trello.com/c/tnG3VXBf/373-user-story-eml-21-cumulative-metric-check-for-expense-line-chart
Added the UI of the cumulative select item
> [EML] Add cumulative select button

- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/CardNavigationMobile/CardNavigationMobile.stories.tsx
- src/stories/containers/Finances/components/CardNavigationMobile/CardNavigationMobile.tsx
- src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/InformationBudgetCapOverView/InformationBudgetCapOverView.tsx
- src/stories/containers/Finances/components/SectionPages/CardsNavigation/CardsNavigation.tsx
- src/stories/containers/Finances/useFinances.tsx
- src/stories/containers/Finances/utils/types.ts
> [QA] Navigation percentage & values in mobile

- src/stories/containers/Finances/components/FinacesTable/FinancesTable.tsx
When annually was selected the last columns had the styles of the total column that is not present in annually
> [QA] Fix remove total color when annually is selected

- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/CumulativeFilter/CumulativeFilter.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/MakerDAOExpenseMetrics.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/TitleFilterComponent.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/useMakerDAOExpenseMetrics.tsx
https://trello.com/c/tnG3VXBf/373-user-story-eml-21-cumulative-metric-check-for-expense-line-chart
Implement the Expense metrics cumulative filter to show the correct data in the chart
> [EML] Implement cumulative expenses metric filter

- src/stories/components/WalletTableCell/WalletTableCell.tsx
- src/stories/containers/TransparencyReport/transparencyReportUtils.tsx
> Fix gnosis link

- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChart/BreakdownChart.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/MakerDAOChartMetrics/MakerDAOChartMetrics.tsx
Fix the spacing between the Q' and the number of the quarter in the tooltip
> [QA] Fix quarterly tooltip spacing in title

- src/stories/containers/Finances/components/BudgetMetricsModal/BudgetMetricsModal.tsx
Changed the font size of the title of the metric modal
> [QA] Change the modal title font size

- src/stories/containers/Finances/components/FinacesTable/FinancesTable.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
- src/stories/containers/Finances/utils/types.ts
Add a subtable for the uncategorized items
> [QA] Add uncategorized sub-table

- src/stories/containers/Finances/components/SectionPages/ReservesWaterfallChartSection/utils.ts
Change the format of the bar legend on the reserves chart
> [QA] Fix reserves chart bar legend format

- src/stories/components/TransparencyReporting/BudgetStatementPager/BudgetStatementPager.tsx
- src/stories/containers/Finances/components/CardNavigationMobile/CardNavigationMobile.tsx
- src/stories/containers/TransparencyReport/TransparencyReport.tsx
- src/stories/containers/TransparencyReport/components/ExpenseReportStatusIndicator/ExpenseReportStatusIndicator.tsx
Hide the Budget statement status if it is `undefined`
> [QA] Hide the budget status when there is no status in the budget statement

- src/core/utils/colors.ts
Avoid red tones in the color palette generation
> [QA] Avoid red colors in the breakdown chart

- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChart/BreakdownChart.tsx
- src/stories/containers/Finances/components/CardNavigationMobile/CardNavigationMobile.tsx
- src/stories/containers/Finances/components/SectionPages/CardsNavigation/CardsNavigation.tsx
- src/stories/containers/Finances/useFinances.tsx
Previously it was showing 6 y-lines in the breakdown chart, now it is showing 12
> [QA] Double chart y-lines

- src/stories/components/svg/select-chevron-down.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/CumulativeFilter/CumulativeFilter.tsx
Replaced the dropdown indication icon in the cumulative filter to make it more obvious
> [QA] Change cumulative dropdown icon more obvious

- src/stories/components/Pagination/BreadCrumbWithIcons.tsx
remove the separator arrow in the breadcrumb on mobile
> [QA] Remove tiny breadcrumb arrow on mobile

- src/core/utils/dictionary.js
- src/stories/components/ExternalLink/ExternalLink.tsx
- src/stories/containers/Endgame/EndgameContainer.tsx
- src/stories/containers/Endgame/components/KeyChangesSections/KeyChangesSections.tsx
- src/stories/containers/Endgame/components/LatestUpdatesSection/ImportantLinks.tsx
- src/stories/containers/Endgame/components/LatestUpdatesSection/LatestUpdatesSection.tsx
- src/stories/containers/Endgame/components/LatestUpdatesSection/PhaseCard.tsx
- src/stories/containers/Endgame/components/NavigationTabs/NavigationTabs.tsx
- src/stories/containers/Endgame/useEndgameContainer.ts
https://trello.com/c/ikyCL3Ex/393-user-story-met-15-endgame-latest-updates
Add the latest updates section to the endgame transition page
> [MET-1.5] Add latest updates section

- src/stories/components/LinkButton/LinkButton.tsx
- src/stories/components/NavigationCard/CardExpenses.tsx
- src/stories/containers/ActorsAbout/ActorAboutContainer.tsx
https://trello.com/c/42azojmG/407-apply-new-changes-to-the-ecosystem-actors-details-view
Change copies in the expenses (now finances) card
> [QA] Fix expenses card in about page

- .github/workflows/staging-deploy.yaml
https://trello.com/c/wwVo7aTn/382-apply-new-setup-for-fusion-dashboard
> Fix remove scheduled release to staging

- src/stories/containers/ActorProjects/components/ProjectStatusChip/ProjectStatusChip.tsx
- src/stories/containers/ActorProjects/utils/colors.ts
- src/stories/containers/Endgame/components/EndgameStatusChip/EndgameStatusChip.tsx
- src/stories/containers/Endgame/components/LatestUpdatesSection/PhaseCard.tsx
https://trello.com/c/ikyCL3Ex/393-user-story-met-15-endgame-latest-updates
Fix the background and font weight in the last update endgame page
The background should have color: rgba(255, 249, 237, 1). **Current Output:** The status displays background color:     rgba(255, 251, 245, 0.50). 
The status component should display the height defined in the design.  **Current Output:** The view displays the status   component higher than the design shows.  ** Visual Proof:** [design.png]
> [MET-393] Fix the colors for background and fix the weight in the font

- src/stories/components/Markdown/MdViewerPage.tsx
- src/stories/components/NavigationCard/CardExpenses.tsx
- src/stories/containers/ActorsAbout/ActorAboutContainer.tsx
- src/stories/containers/ActorsAbout/components/ActorMdViewer/ActorMdViewPage.tsx
- src/stories/containers/ActorsTransparencyReport/ActorsTransparencyReportContainer.tsx
- src/stories/containers/TransparencyReport/TransparencyReport.tsx
https://trello.com/c/tTURGnnV/422-change-the-name-of-the-expense-reports-view-to-budget-statements
Change the name of the "Expense Reports" view to Budget Statements
> [QA-422] Change the name of the "Expense Reports" view to Budget Statements in EA and CU

- src/stories/containers/RecognizedDelegates/RecognizedDelegatesContainer.tsx
https://trello.com/c/tTURGnnV/422-change-the-name-of-the-expense-reports-view-to-budget-statements
Change the name of the "Expense Reports" view to Budget Statements
> [QA-422-] Rename budget per expense in delegate button

- src/stories/containers/Finances/components/FinacesTable/FinancesTable.tsx
- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
https://trello.com/c/iDmNeoEO/434-qa-item
ALL SCREENS // Uncategorized should have no children. 1. If the uncategorized line item is the only one for the table or subsections of the table, then hide it and include it in the totals row for that specific table and/or subsection of the table. 1.1. So if Uncategorized line item is the only one for e.g., Support Scope, then include the values of the uncategorized in the Support Scope totals row. 2. If uncategorized is not the only one then show it with other line items. 2.1. If Support Scope has other line items on top of Uncategorized: it has e.g., Uncategorized, Incubation budget etc..., then show these all as line items under Support Scope. 3. Uncategorized as a line item subsumes every subline item, i.e., it does not have any children.
> [QA] Fix uncategorized rules

- src/stories/containers/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
https://trello.com/c/MRjfL60I/430-hide-line-items-with-0-value
Hide all the "uncategorized" subtables and the uncategorized rows which have all the values of the selected metrics zero
> [QA] Hide uncategorized subtables/rows where all values are zero

- src/views/Endgame/useEndgameView.ts
https://trello.com/c/ki5J9mbH/429-endgame-budget-structure-item-is-not-highlighted-on-the-endgame-page
> [QA-429]: fix issue with the navigation tab on the Endgame page

- src/views/Endgame/components/NavigationTabs/NavigationTabs.tsx
https://trello.com/c/04eKxJok/426-apply-reskin-design-to-the-key-changes-section-met
Updated the hover statuses in the endgame navbar
> [MET] Endgame nav hover

- src/stories/containers/Finances/utils/types.ts
- src/views/Endgame/components/BudgetDoughnutChart/BudgetDoughnutChart.tsx
https://trello.com/c/ySUDvo2c/431-apply-reskin-design-to-the-endgame-budget-structure-section-met
> [Reskin-431] Add the tooltip to endgame pie chart page

- src/components/CustomSelect/CustomSelect.stories.tsx
- src/components/CustomSelect/CustomSelect.tsx
- src/components/CustomSelect/type.ts
- src/components/CustomSelect/useCustomSelect.ts
- src/components/FiltersBundle/FilterSheet.tsx
- src/components/FiltersBundle/FiltersBundle.tsx
- src/views/Endgame/components/BudgetStructureSection/BudgetStructureSection.stories.tsx
https://trello.com/c/UGndl7pm/446-create-a-reusable-year-component-filtersbundle-for-the-endgame-view
> [Reskin-446]: new select component

- src/components/Footer/Footer.tsx
- src/components/Footer/data.ts
https://trello.com/c/6o1WKifL/435-feature-fdf-1-fusion-dashboard-footer
> [Fix-435] links open in a new tab

- src/components/Footer/data.ts
https://trello.com/c/6o1WKifL/435-feature-fdf-1-fusion-dashboard-footer
> [Reskin-435]: link changes and hide buttons in the footer

- pages/ecosystem-actors/index.tsx
- src/components/FiltersBundle/FilterDesktop.tsx
- src/components/FiltersBundle/FilterTablet.tsx
- src/views/Actors/ActorsView.stories.tsx
- src/views/Actors/ActorsView.tsx
- src/views/Actors/useActorsView.tsx
- src/views/Actors/utils/utils.ts
Show the reset filter button with the enable/disable statuses. Also renamed the actors container to ActorsView to follow the naming convention
> [T-450] Fix reset button statuses

- src/components/ScopeChip/useScopeColors.tsx
Fixed the all option border color
> [T-450] Fix the all option for the scopes filter

- src/components/CustomSheet/CustomSheet.tsx
Fixed the Modal sheet top padding
> [T-450] Fix modal sheet top margin

- src/components/CustomSheet/CustomSheet.tsx
- src/components/FiltersBundle/FilterMobile.tsx
- src/components/FiltersBundle/FiltersBundle.tsx
- src/components/FiltersBundle/types.ts
- src/views/Actors/ActorsView.tsx
- src/views/Endgame/components/BudgetStructureSection/BudgetStructureSection.tsx
Fixed the scroll of the filter and improve the filter height in endgame budget structure section.
> [T-450] Fix modal sheet scroll

- src/components/FiltersBundle/FilterMobile.tsx
- src/views/Actors/ActorsView.tsx
Updated the colors of the reset filter on mobile
> [T-450] Fix reset button colors in mobile

- src/components/FiltersBundle/FilterMobile.tsx
Fixed the colors of the reset button under certain circumstances
> [Reskin-450] Fix reset button on disabled status in mobile

- src/components/CategoryChip/CategoryChip.tsx
- src/components/StatusChip/StatusChip.tsx
- src/core/enums/cuCategoryEnum.ts
> [Reskin-440] Add mobile padding for category and status

- src/components/Breadcrumb/Breadcrumb.stories.tsx
- src/components/Breadcrumb/Breadcrumb.tsx
- src/components/Breadcrumb/DotsSegment.tsx
https://trello.com/c/YiRim70Y/448-create-a-reusable-breadcrumb-for-cu-ea
If the items doesn't fit in the breadcrumb container, then compress it in a three dots menu to allow them to fit
> [Reskin-448] Compact breadcrumb if needed

- src/stories/containers/TransparencyReport/components/AccountsSnapshot/utils/expenseComparisonUtils.tsx
https://trello.com/c/zduYB36q/475-wrong-value-in-the-reported-expenses-comparison-table
Fixed the formula to calculate the difference
> [Issue-475] Fix difference percentage in the snapshot comparison

- src/components/CustomSelect/CustomSelect.tsx
> [Fix-440] Fix the background in the filter when its open

- src/core/enums/expenditureLevelEnum.ts
- src/stories/components/CustomBarChart/CustomBarChart.tsx
- src/stories/containers/TransparencyReport/components/PopverForecastDescription/PopoverForecastDescription.tsx
- src/stories/containers/TransparencyReport/utils/forecastHelper.ts
- src/views/CoreUnits/components/ToolTips/SummaryToolTip.tsx
> [Reskin-440] Add style for button in light mode and links in dark mode in summary tooltip

- src/components/Breadcrumb/DotsSegment.tsx
https://trello.com/c/YiRim70Y/448-create-a-reusable-breadcrumb-for-cu-ea
The dropdown in mobile should be a modal sheet instead
> [Reskin-448] Update mobile dropdown behavior

- src/components/Breadcrumb/Breadcrumb.stories.tsx
- src/components/Breadcrumb/Breadcrumb.tsx
- src/components/Breadcrumb/CustomContents/TeamBreadcrumbContent.tsx
- src/components/TeamHeader/TeamHeader.stories.tsx
- src/components/TeamHeader/TeamHeader.tsx
- src/views/EAAbout/EAAboutView.tsx
- src/views/EAAbout/api/queries.ts
- src/views/EAAbout/components/ActorSummary/ActorSummary.tsx
- src/views/EAAbout/useEAAboutView.ts
https://trello.com/c/PM1BO2VY/449-apply-reskin-to-the-main-header-for-cu-ea-about
Added the breadcrumb and team header to the EA about page. Improved both components and integrated the header with the team object
> [Reskin-449] Add breadcrumb and header to the EA landing page

- src/views/CUAbout/CustomSheetFinances.tsx
- src/views/CUAbout/NavigationCard/CardExpenses.tsx
- src/views/EAAbout/components/Auditors/Auditors.tsx
- src/views/EAAbout/components/CustomSheetProjects.tsx
> [Reskin-447] Add sheet button for Finances and Project Cards

- src/stories/containers/ActorProjects/components/DeliverableCard/DeliverableCard.tsx
- src/views/RoadmapMilestones/components/MilestoneDetailsCard/DeliverablesSection.tsx
- src/views/RoadmapMilestones/components/MilestoneDetailsCard/MilestoneProgress.tsx
- src/views/RoadmapMilestones/components/MilestoneDetailsCard/StatsData.tsx
> [PH24-1] Disabled some milestone elements

- src/components/TeamHeader/TeamHeader.tsx
- src/core/utils/dictionary.js
https://trello.com/c/ZmnYYI8X/496-content-is-not-visible-on-mobile-when-scrolling-up-down
Fix the height issue that hides the page content
> [Reskin-496] Fix hidden content below the header on mobile devices

- src/views/RoadmapMilestones/components/MilestoneCard/MilestoneCard.tsx
- src/views/RoadmapMilestones/components/MilestoneDetailsCard/MilestoneDetailsCard.tsx
- src/views/RoadmapMilestones/staticData.ts
Improved the card title to show it in only one line, at the same level as the code adding better support for longer titles. Also improved the mocked data for the default view (no ph roadmap)
> [PH24-1] Improve milestones card title and mocked data

- src/components/Breadcrumb/CustomContents/TeamBreadcrumbContent.tsx
https://trello.com/c/4weAM0uV/503-incorrect-visualization-of-ecosystem-actors-core-units-navigation-in-safari
Fix the breadcrumb on Apple devices
> [Reskin-503] Fix breadcrumb text on iOS devices

- src/stories/containers/Finances/components/DelegateExpenseTrend/DelegateExpenseTrendItem.tsx
- src/views/BudgetStatement/BudgetStatementView.tsx
- src/views/BudgetStatement/components/BudgetStatementSummary/BudgetStatementSummary.tsx
- src/views/BudgetStatement/useBudgetStatementView.ts
https://trello.com/c/KoM0xita/406-bss-11-budget-statement-pages-for-keepers-legacy-design
Complete the header and page integration
> [BSS-1] Complete budget statement page integration

- src/views/CUAbout/CuAboutView.tsx
- src/views/CUAbout/Markdown/renderUtils.tsx
- src/views/EAAbout/components/ActorMdViewer/ActorMdViewPage.tsx
> [Fix-447] Fix space in md for heading and fix container

- src/stories/components/CustomBarChart/CustomBarChart.tsx
> [Fix-447] Fix the size of the bars fix the container

- src/core/utils/const.ts
- src/views/CUAbout/CuAboutView.tsx
- src/views/CUAbout/NavigationCard/CardSomethingWrong.stories.tsx
- src/views/EAAbout/EAAboutView.tsx
https://trello.com/c/ZTrmxnP1/505-remove-typeform-link-from-the-cu-ea-profile-view
Remove the typeform link in the "something wrong" card
> [Reskin-505] Remove Typeform link

- src/views/Teams/TeamsView.tsx
- src/views/Teams/components/TeamTypeCard/TeamTypeCard.tsx
- src/views/Teams/components/TeamsSections/TeamsSections.tsx
- src/views/Teams/staticData.ts
https://trello.com/c/k5QpQzQr/506-change-request-in-the-team-categories-view
Modify numbers style and introduce contributes type
> [Reskin-506] Modify team numbers styles

- src/components/Container/PageContainer.tsx
- src/stories/containers/ActorProjects/ActorProjectsContainer.tsx
- src/stories/containers/ActorProjects/useActorProjectsContainer.tsx
- src/stories/containers/ActorsTransparencyReport/ActorsTransparencyReportContainer.tsx
- src/stories/containers/Finances/FinancesContainer.tsx
- src/stories/containers/TransparencyReport/TransparencyReport.tsx
https://trello.com/c/16pG9Esv/497-change-background-color-to-the-pages
Fix page backgrounds that still have the legacy backgrounds
> [Reskin-497] CU/EA reporting page background

- src/components/TopBarNavigation/TopBarNavigation.tsx
- src/components/TopBarNavigation/types.ts
- src/components/TopBarNavigation/useTopBarNavigation.tsx
https://trello.com/c/EHGVkCf3/428-tnb-0-top-navigation-bar-for-fusion
> [Resin-428] Add link to the logo in desk resolutions

- src/views/CoreUnitAbout/CoreUnitAboutView.tsx
- src/views/CoreUnitAbout/components/NavigationCard/CardSomethingWrong.stories.tsx
- src/views/CoreUnitAbout/components/NavigationCard/CardSomethingWrong.tsx
- src/views/EcosystemActorAbout/EcosystemActorAboutView.tsx
https://trello.com/c/ZTrmxnP1/505-remove-typeform-link-from-the-cu-ea-profile-view
> [CR-5050] Remove important links sections

- src/views/Contributors/staticData.ts
https://trello.com/c/QcHZz9lN/511-set-the-default-year-2024-for-the-sparse-budget-categories
> [CR-511] Change the mock data

- src/components/TopBarNavigation/TopBarNavigation.tsx
- src/components/TopBarNavigation/useTopBarNavigation.tsx
- src/views/Endgame/components/NavigationTabs/NavigationTabs.tsx
https://trello.com/c/EHGVkCf3/428-tnb-0-top-navigation-bar-for-fusion
> [FIX-428] Fix/remove undefined when page refresh

- src/components/TopBarNavigation/TopBarNavigation.tsx
- src/views/Endgame/components/NavigationTabs/NavigationTabs.tsx
https://trello.com/c/EHGVkCf3/428-tnb-0-top-navigation-bar-for-fusion
> [Fix-428] Fix the gap in endgame page

- src/components/TopBarNavigation/TopBarNavigation.tsx
- src/stories/components/UserBadge/UserBadge.tsx
https://trello.com/c/smptd4rr/470-apply-reskin-to-the-actual-tab-for-cu-ea
This add the behavior when the user is logged and its in 1024 viewport then should be show the letter component
> [Reskin-470] Show letter in 1024 when user is logged

- src/stories/containers/Finances/components/BreakdownChartSection/BreakdownChart/BreakdownChart.tsx
- src/stories/containers/Finances/components/SectionPages/MakerDAOExpenseMetrics/MakerDAOChartMetrics/MakerDAOChartMetrics.tsx
https://trello.com/c/e1aXau10/518-wrong-number-of-decimals-in-the-breakdown-chart
Fixed the decimal places rounding of the values of the tooltips in the charts on the finances page
> [Demo-518] Fix number format in tooltip of the charts

- src/components/AdvancedInnerTable/AdvancedInnerTable.tsx
- src/components/AdvancedInnerTable/TextCell/TextCell.tsx
- src/components/AdvancedInnerTable/TransparencyCard/TransparencyCard.tsx
- src/components/AdvancedInnerTable/types.ts
- src/views/CoreUnitBudgetStatement/CoreUnitBudgetStatementView.tsx
- src/views/CoreUnitBudgetStatement/utils/actualsTableHelpers.tsx
> [Reskin-470] Add style for the mobile resolutions in table

- src/components/AdvancedInnerTable/BasicModal/CategoryItem/ArrowAccordionCategory.tsx
- src/components/AdvancedInnerTable/BasicModal/ContainerModal.tsx
- src/views/CoreUnitBudgetStatement/components/CuHeadlineText/CuHeadlineText.tsx
> [Reskin-470] Fix the colors of the arrows in modal

- src/components/AdditionalNotesSection/AdditionalNotesSection.stories.tsx
- src/components/AdditionalNotesSection/AdditionalNotesSection.tsx
- src/components/AdvancedInnerTable/AdvancedInnerTable.tsx
- src/components/AdvancedInnerTable/BasicModal/CategoryItem/ArrowAccordionCategory.tsx
- src/components/AdvancedInnerTable/BasicModal/ContainerModal.tsx
- src/components/AdvancedInnerTable/TransparencyCard/TransparencyCard.tsx
- src/components/CuHeadlineText/CuHeadlineText.stories.tsx
- src/components/Tabs/Tab.stories.tsx
- src/components/WalletTableCell/WalletTableCell.stories.tsx
https://trello.com/c/smptd4rr/470-apply-reskin-to-the-actual-tab-for-cu-ea
> [Reskin-470] Add styles for the modal 

- src/components/AdditionalNotesSection/AdditionalNotesSection.stories.tsx
- src/components/AdvancedInnerTable/AdvancedInnerTable.tsx
- src/components/AdvancedInnerTable/TransparencyCard/TransparencyCard.tsx
- src/components/AdvancedInnerTable/types.ts
- src/components/BudgetStatement/BudgetStatementActuals/BudgetStatementActuals.tsx
- src/components/BudgetStatement/BudgetStatementActuals/useBudgetStatementActuals.ts
- src/views/CoreUnitBudgetStatement/utils/actualsTableHelpers.tsx
- src/views/CoreUnitBudgetStatement/utils/helpers.tsx
- src/views/EcosystemActorAbout/components/CardProjects/ItemCustomProject.tsx
> [Reskin-470] Reskin the Canonical Expense Categories  and Improve the space in the cards

- src/components/AccountsSnapshot/AccountsSnapshot.tsx
- src/components/AccountsSnapshot/components/AccordionArrow/AccordionArrow.tsx
- src/components/AccountsSnapshot/components/CUReserves/CUReserves.tsx
- src/components/AccountsSnapshot/components/FundingOverview/FundingOverview.stories.tsx
- src/components/AccountsSnapshot/components/FundingOverview/FundingOverviewSkeleton.stories.tsx
- src/components/AccountsSnapshot/components/SVG/GreenArrowDown.tsx
- src/components/AccountsSnapshot/components/SVG/RedArrowUp.tsx
- src/components/AccountsSnapshot/components/SectionHeader/SectionHeader.tsx
- src/components/AccountsSnapshot/components/Transaction/MobileTransaction.stories.tsx
- src/components/AccountsSnapshot/components/Transaction/MobileTransaction.tsx
- src/components/AccountsSnapshot/components/Transaction/Transaction.tsx
- src/components/AccountsSnapshot/components/Transaction/TransactionWalletInfo.tsx
- src/components/AccountsSnapshot/components/Transaction/segments/TransactionAmount.tsx
- src/components/AccountsSnapshot/components/Transaction/segments/TransactionCounterParty.tsx
- src/components/AccountsSnapshot/components/Transaction/segments/TransactionHeader.tsx
- src/components/AccountsSnapshot/components/TransactionHistory/TransactionHistory.tsx
- src/components/AccountsSnapshot/components/TransactionList/TransactionList.tsx
- src/components/AccountsSnapshot/components/TxHash/TxHash.tsx
https://trello.com/c/ktA33FyI/479-reskin-budget-statements-cu-ea-accounts-snapshot-tab
> [Reskin-479] Reskin transaction history

- src/components/AdvancedInnerTable/AdvancedInnerTable.tsx
- src/components/AdvancedInnerTable/TransparencyCard/TransparencyCard.tsx
- src/components/BudgetStatement/BudgetStatementActuals/useBudgetStatementActuals.ts
- src/components/BudgetStatement/BudgetStatementForecast/BudgetStatementForecast.tsx
- src/components/BudgetStatement/BudgetStatementForecast/ForecastBreakdownSection/ForecastBreakdownSection.tsx
- src/components/BudgetStatement/BudgetStatementForecast/HeaderWithIcon/HeaderWithIcon.tsx
- src/components/BudgetStatement/BudgetStatementForecast/HeaderWithIcon/TooltipHeader.tsx
- src/components/BudgetStatement/BudgetStatementForecast/TotalForecastSection/TotalForecastSection.tsx
https://trello.com/c/JUvtoViK/476-reskin-budget-statements-cu-ea-forecast-tab
> [Reskin-476] Update the space between tables

- src/components/AdvancedInnerTable/AdvancedInnerTable.tsx
- src/components/AdvancedInnerTable/NumberCell/NumberCell.tsx
- src/components/Breadcrumb/Breadcrumb.tsx
- src/components/BudgetStatement/BudgetStatementPager/BudgetStatementPager.tsx
> [Reskin-470] Fix fonts issues relate with actuals tab

- src/components/AccountsSnapshot/components/ExpensesComparison/ExpensesComparison.stories.tsx
- src/components/AccountsSnapshot/components/ExpensesComparison/ExpensesComparison.tsx
- src/components/AccountsSnapshot/components/ExpensesComparison/headers.tsx
- src/components/AccountsSnapshot/useAccountsSnapshot.tsx
- src/components/AccountsSnapshot/utils/expenseComparisonUtils.tsx
- src/components/AdvanceTable/BuiltIn/Cells/BasicTHCell.tsx
- src/components/AdvanceTable/BuiltIn/Cells/BoldTextCell.tsx
- src/components/AdvanceTable/BuiltIn/Cells/NumberCell.tsx
- src/components/AdvanceTable/BuiltIn/Cells/TextCell.tsx
- src/components/AdvanceTable/utils.ts
https://trello.com/c/ktA33FyI/479-reskin-budget-statements-cu-ea-accounts-snapshot-tab
Applied the reskin to the Expense Comparison section of the snapshots
> [Reskin-479] Reskin expense comparison table

- src/components/AdvancedInnerTable/AdvancedInnerTable.tsx
- src/components/BudgetStatement/BudgetStatementMkrVesting/BudgetStatementMkrVesting.tsx
- src/components/BudgetStatement/BudgetStatementMkrVesting/MkrVestingTotalFTE.tsx
- src/components/BudgetStatement/BudgetStatementMkrVesting/ToolTipMkrVesting.tsx
- src/components/BudgetStatement/BudgetStatementMkrVesting/useBudgetStatementMkrVesting.tsx
- src/views/CoreUnitBudgetStatement/CoreUnitBudgetStatementView.tsx
- src/views/EcosystemActorBudgetStatement/EcosystemActorBudgetStatementView.tsx
https://trello.com/c/1A1BltB6/478-reskin-budget-statements-cu-ea-mkr-vesting-tab
> [Reskin-478] Add icon to difference columns

- src/views/EcosystemActorsIndex/components/ActorItem/ActorItem.tsx
- src/views/EcosystemActorsIndex/components/EcosystemActorDescription/EcosystemActorDescription.tsx
- src/views/EcosystemActorsIndex/components/RoleItem/RoleItem.tsx
- src/views/EcosystemActorsIndex/components/ScopeItem/ScopeItem.tsx
- src/views/EcosystemActorsIndex/components/SocialArrowLinks/SocialArrowLinks.tsx
https://trello.com/c/ukLWiU1h/546-make-each-contributors-row-clickable
> Split the card per component and merge into item

- src/views/CoreUnitsIndex/components/ToolTips/SummaryToolTip.tsx
https://trello.com/c/R6wqimqX/477-reskin-budget-statements-cu-ea-transfer-requests-tab
[X] Should fix issues from QC.
Fix issue when hover on CU item that don't have any category
> [Issue-477]Hidden category section when there is not one

- src/components/BudgetStatement/BudgetStatementMkrVesting/BudgetStatementMkrVestingSection/BudgetStatementMkrVestingTableSection.tsx
- src/components/BudgetStatement/BudgetStatementMkrVesting/MkrVestingTotalFTE.tsx
- src/components/BudgetStatement/ExpenseReport/ExpenseReport.tsx
- src/components/BudgetStatement/ExpenseReport/components/ExpenseSection/ExpenseSection.tsx
- src/components/BudgetStatement/ExpenseReport/components/SectionTitle/SectionTitle.tsx
- src/components/CuHeadlineText/CuHeadlineText.tsx
> [Reskin-501]Add styles for auditor view

- src/views/CoreUnitsIndex/components/CuTableColumnExpenditures/CuTableColumnExpenditures.tsx
- src/views/CoreUnitsIndex/components/CuTableColumnSummary/CuTableColumnSummary.tsx
https://trello.com/c/47RkwnO6/549-update-the-expenditure-section-link-in-the-core-units-index
> Update the link and target link in core unit item

- src/views/CoreUnitsIndex/components/CuTableColumnSummary/CuTableColumnSummary.tsx
https://trello.com/c/47RkwnO6/549-update-the-expenditure-section-link-in-the-core-units-index
> [Reskin-49] Delete the flag target blank in the text

- src/components/BudgetStatement/ExpenseReport/ExpenseReport.tsx
- src/components/BudgetStatement/ExpenseReport/components/ExpenseSection/ExpenseSection.tsx
- src/components/BudgetStatement/ExpenseReport/components/SectionTitle/SectionTitle.tsx
> Add styles for the auditios view

- src/components/BudgetStatement/ExpenseReport/ExpenseReport.tsx
- src/components/Tabs/Tabs.tsx
> Add the styles for the arrow in the tab

- src/views/Finances/FinancesView.tsx
- src/views/Finances/components/SectionPages/OverviewSection/OverviewSection.tsx
- src/views/Finances/components/SectionPages/OverviewSection/UtilizationChart/FilterTabs/FilterTabs.tsx
- src/views/Finances/components/SectionPages/OverviewSection/UtilizationChart/MobileChart/LegendItem.tsx
- src/views/Finances/components/SectionPages/OverviewSection/UtilizationChart/MobileChart/MobileChart.tsx
- src/views/Finances/components/SectionPages/OverviewSection/UtilizationChart/UtilizationChart.tsx
https://trello.com/c/lHsgd1Nv/485-reskin-finances-main-section
Implemented base for the mobile chart in the overview section
> Mobile chart in the overview section

- src/components/BudgetStatement/BudgetStatementAuditorComments/AuditorCommentsContainer/AuditorCommentsContainer.tsx
- src/components/BudgetStatement/BudgetStatementAuditorComments/ParticipantRoles.tsx
https://trello.com/c/lYYlK9W4/551-apply-background-to-the-participant-roles-in-the-comments-view
> Add the background to the auditor card comments

- src/components/BudgetStatement/BudgetStatementForecast/BarWithDottedLine.tsx
- src/components/BudgetStatement/ExpenseReport/ExpenseReport.tsx
- src/components/BudgetStatement/ExpenseReport/components/ExpenseSection/ExpenseSection.tsx
> [Reskin-501] Add the styles for forecast

- src/components/Tabs/Tabs.tsx
- src/views/CoreUnitBudgetStatement/CoreUnitBudgetStatementView.tsx
- src/views/CoreUnitBudgetStatement/useCoreUnitBudgetStatementView.tsx
- src/views/EcosystemActorBudgetStatement/EcosystemActorBudgetStatementView.tsx
- src/views/EcosystemActorBudgetStatement/useEcosystemActorBudgetStatementView.tsx
https://trello.com/c/7g6oATpI/554-fix-general-issues-in-cu-ea-contributors-endgame-views
> [FIX-554] Avoid show tooltip for mobile

- .vscode/settings.json
- src/views/Home/components/GovernanceSection/GovernanceSection.tsx
- src/views/Home/components/GovernanceSection/Proposal/Proposal.stories.tsx
- src/views/Home/components/GovernanceSection/Proposal/Proposal.tsx
- src/views/Home/components/GovernanceSection/Proposals/Proposals.tsx
https://trello.com/c/fKv0jCGG/538-hom-13-governance-homepage-section
Implement the Proposals UI in the Governance section of homepage
> [HOM-1.3] Governance proposals UI

- src/views/Home/components/Contributors/ContributorsSection.tsx
- src/views/Home/components/Contributors/TabDescriptions.tsx
> [QA-539] Fix QA issues in contributors section

- src/views/CoreUnitsIndex/useCoreUnitsTableView.tsx
https://trello.com/c/gpE4auII/559-fix-redirect-issue-in-core-units-activity-feed-view
> [Fix-559] Avoid redirect to core unit from the activity feed button

- src/views/CoreUnitsIndex/useCoreUnitsTableView.tsx
- src/views/EcosystemActorsIndex/useEcosystemActorsIndexView.tsx
- src/views/Home/components/Contributors/TabDescriptions.tsx
https://trello.com/c/NrvjMpYJ/560-fix-reset-functionality-in-the-cu-ea-index
> [Fix-560] Redirect issue in core units activity feed view

- src/views/Home/components/FinancesBarChartCard/FinancesBarChartCard.tsx
- src/views/Home/components/FinancesSection/FinancesSection.tsx
> [Home-537] Move the description above of the titlle of the page

- src/views/Home/components/FinancesBarChartCard/FinancesBarChartCard.tsx
- src/views/Home/components/FinancesLineChart/FinancesLineChart.tsx
> [Home-537] Add the tooltip in the line chart

- src/views/Home/components/FinancesLineChartCard/FinancesLineChartCard.tsx
> [Home-537] Add correct height for the button in line chart
